/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Wiki-style document — rich-text body, hierarchical via parent self-FK,\ngrouped into a DocumentSpace OR attached to a Project / Task.\n\nSoft-delete + workspace scope + versioning all standard. Content lives\nin `body` as text; `bodyFormat` tells clients how to render it. For the\nMVP we ship markdown; richtext (JSON tree) is reserved for when we\npick a structured editor.\n\nPrivacy & sharing:\n  isPrivate=true  → only the author + explicit DocumentContributors see it\n  isPrivate=false → workspace members see it (additionally restricted by\n                    isHiddenForConnectUsers for external Project members)\n  Contributors via DocumentContributor entity grant read/manage to specific\n  users beyond the default rules.
 */
export const documentHtmlSchema = z.object({
    "name": z.optional(z.string().default("Untitled")),
"emoji": z.string().nullish(),
"body": z.string().nullish(),
"bodyFormat": z.optional(z.enum(["markdown", "html", "richtext"]).default("markdown")),
"space": z.string().nullish(),
"parent": z.string().nullish(),
"project": z.string().nullish(),
"task": z.string().nullish(),
"position": z.optional(z.number().default(0)),
"isPrivate": z.optional(z.boolean().default(false)),
"isHiddenForConnectUsers": z.optional(z.boolean().default(false)),
"isArchived": z.optional(z.boolean().default(false)),
"contributors": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"private": z.optional(z.boolean()),
"hiddenForConnectUsers": z.optional(z.boolean()),
"archived": z.optional(z.boolean()),
"deleted": z.optional(z.boolean())
    }).describe("Wiki-style document — rich-text body, hierarchical via parent self-FK,\ngrouped into a DocumentSpace OR attached to a Project / Task.\n\nSoft-delete + workspace scope + versioning all standard. Content lives\nin `body` as text; `bodyFormat` tells clients how to render it. For the\nMVP we ship markdown; richtext (JSON tree) is reserved for when we\npick a structured editor.\n\nPrivacy & sharing:\n  isPrivate=true  → only the author + explicit DocumentContributors see it\n  isPrivate=false → workspace members see it (additionally restricted by\n                    isHiddenForConnectUsers for external Project members)\n  Contributors via DocumentContributor entity grant read/manage to specific\n  users beyond the default rules.")