/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Explicit per-user access to a Document — overrides workspace defaults for\nprivate documents. Mirrors awork\'s DocumentContributorModel.\n\nAccess levels: read | manage. Add a user as \'read\' on a private doc to\nshare it with them; \'manage\' lets them also edit + invite further people.\n\nVoter resolution: DocumentVoter checks for an explicit contributor row\nbefore falling back to workspace-membership rules.
 */
export const documentContributorJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "document": z.optional(z.string()),
"user": z.optional(z.string()),
"access": z.optional(z.enum(["read", "manage"]).default("read")),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish()
    })).describe("Explicit per-user access to a Document — overrides workspace defaults for\nprivate documents. Mirrors awork's DocumentContributorModel.\n\nAccess levels: read | manage. Add a user as 'read' on a private doc to\nshare it with them; 'manage' lets them also edit + invite further people.\n\nVoter resolution: DocumentVoter checks for an explicit contributor row\nbefore falling back to workspace-membership rules.")