/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TimeEntryHtml = {
    /**
     * @type string | undefined, iri-reference
    */
    user?: string;
    /**
     * @description Nullable to support time tracked against a \"private\" task (a task that\nitself has no project FK) and free-form workspace-level time entries\nwithout a project pin. Reporting queries that group by project simply\nbucket null-project rows as \"(no project)\".
     * @type string,null, iri-reference
    */
    project?: string | null;
    /**
     * @type string,null, iri-reference
    */
    typeOfWork?: string | null;
    /**
     * @description Awork-style: timesheet entry has been \"billed\" (invoice sent) — separate\nconcept from isBillable (eligible for billing).
     * @default false
     * @type boolean | undefined
    */
    isBilled?: boolean;
    /**
     * @type string,null, iri-reference
    */
    task?: string | null;
    /**
     * @type string | undefined, date-time
    */
    startsAt?: string;
    /**
     * @type string,null, date-time
    */
    endsAt?: string | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    durationMinutes?: number;
    /**
     * @type string,null
    */
    note?: string | null;
    /**
     * @default true
     * @type boolean | undefined
    */
    isBillable?: boolean;
    /**
     * @default false
     * @type boolean | undefined
    */
    isLocked?: boolean;
    /**
     * @description Entry created via an external integration (Connect-Mailbox, awork\nimport, public API). Mirrors Project.isExternal so cross-workspace\nreports can filter integration noise out.
     * @default false
     * @type boolean | undefined
    */
    isExternal?: boolean;
    /**
     * @description IANA timezone identifier at the moment of capture\n(e.g. `Europe/Berlin`, `America/New_York`). Lets the UI render the\nentry in its original local time even after the user travelled or\nDST flipped between save and read.
     * @type string,null
    */
    timezone?: string | null;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type string,null
    */
    externalSource?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly billed?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly billable?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly locked?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly external?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly running?: boolean;
    /**
     * @type string,null
    */
    readonly externalRef?: string | null;
};