/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

/**
 * @description A billable service the agency provides to one Customer. Optionally pinned\nto a specific CustomerSystem when the service is system-bound\n(hosting for the Foo TYPO3 instance) vs. customer-wide (general\nmaintenance retainer covering all of Foo\'s sites).\n\nMoney is stored as integer cents in the {@see self::$priceCents} column;\nno float column, no Decimal cast — multiplication and rounding stays\nexact. {@see self::$currency} is an ISO 4217 alpha-3 code in lowercase.\n\nLifecycle:\n  Trial → Active → (Paused) → Cancelled\n\n`nextBillingOn` is auto-recomputed by the prePersist/preUpdate listener\nfrom (startedOn, billingCycle, status). When the subscription is\nCancelled or Once-billed, nextBillingOn becomes null.
 */
export const serviceSubscriptionJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "customer": z.optional(z.string()),
"system": z.string().describe("Optional — when null, the subscription belongs to the customer as a\nwhole rather than one specific system. Use cases:\n  - system-bound:   hosting for the Acme TYPO3 instance\n  - customer-wide:  monthly support retainer covering every Acme site").nullish(),
"name": z.string(),
"description": z.string().nullish(),
"priceCents": z.optional(z.int().min(0).default(0).describe("Price for ONE billing cycle, in the smallest currency unit (cents/Rappen/etc).")),
"currency": z.optional(z.string().min(3).max(3).default("eur").describe("ISO 4217 alpha-3 in lowercase (\"eur\", \"chf\", \"usd\").")),
"billingCycle": z.optional(z.enum(["monthly", "quarterly", "half_yearly", "yearly", "once"]).default("monthly")),
"status": z.optional(z.enum(["trial", "active", "paused", "cancelled"]).default("active")),
"startedOn": z.optional(z.iso.datetime()),
"endedOn": z.iso.datetime().nullish(),
"autoRenew": z.optional(z.boolean().default(true)),
"nextBillingOn": z.iso.datetime().describe("Computed by computeNextBilling() in prePersist / preUpdate. Stored so\nthe upcoming-billing queries (and the planned dunning command) can\nindex this column instead of recomputing on every row.").nullish(),
"notes": z.string().nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"deleted": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    })).describe("A billable service the agency provides to one Customer. Optionally pinned\nto a specific CustomerSystem when the service is system-bound\n(hosting for the Foo TYPO3 instance) vs. customer-wide (general\nmaintenance retainer covering all of Foo's sites).\n\nMoney is stored as integer cents in the {@see self::$priceCents} column;\nno float column, no Decimal cast — multiplication and rounding stays\nexact. {@see self::$currency} is an ISO 4217 alpha-3 code in lowercase.\n\nLifecycle:\n  Trial → Active → (Paused) → Cancelled\n\n`nextBillingOn` is auto-recomputed by the prePersist/preUpdate listener\nfrom (startedOn, billingCycle, status). When the subscription is\nCancelled or Once-billed, nextBillingOn becomes null.")