/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CustomerHtmlStatusEnum = "prospect" | "active" | "inactive" | "churned" | "archived";

/**
 * @description A workspace-scoped customer record — the agency\'s view of one client.\n\nThis is *deliberately* not modeled like awork\'s `Company` entity, which\nexisted only as an FK on Project (no first-class customer DB). In Worktide\neach Workspace owns a full CRM of Customers; Projects optionally link to a\nCustomer, ServiceSubscriptions hang off CustomerSystems (Phase 3 block 2),\nand the TYPO3 client portal will read this same table.\n\n`isCompany` flips the schema between \"company with VAT and legalName\" and\n\"private person with first/last name\". The flat `addressLine1/2/zip/city/\ncountry` fields are good enough for the MVP — a future block can move\naddresses into a polymorphic Address entity if we need multi-address\n(billing / shipping / visit).\n\nLifecycle: Prospect → Active → Inactive | Churned → Archived. The status\nfield is informational — no automated transitions yet; an operator\npatches it as the relationship evolves.
*/
export type CustomerHtml = {
    /**
     * @description Display name — usually the company name; for individuals, \"Lastname, Firstname\".
     * @type string
    */
    name: string;
    /**
     * @description Formal company name for invoices (\"Foo GmbH & Co. KG\") — only meaningful when isCompany.
     * @type string,null
    */
    legalName?: string | null;
    /**
     * @default true
     * @type boolean | undefined
    */
    isCompany?: boolean;
    /**
     * @type string,null
    */
    vatId?: string | null;
    /**
     * @type string,null, email
    */
    email?: string | null;
    /**
     * @type string,null
    */
    phone?: string | null;
    /**
     * @type string,null, uri
    */
    website?: string | null;
    /**
     * @type string,null
    */
    industry?: string | null;
    /**
     * @type string,null
    */
    addressLine1?: string | null;
    /**
     * @type string,null
    */
    addressLine2?: string | null;
    /**
     * @type string,null
    */
    zip?: string | null;
    /**
     * @type string,null
    */
    city?: string | null;
    /**
     * @description ISO 3166-1 alpha-2 (e.g. \"DE\", \"AT\") — optional, stored uppercase.
     * @type string,null
    */
    country?: string | null;
    /**
     * @default "active"
     * @type string | undefined
    */
    status?: CustomerHtmlStatusEnum;
    /**
     * @type string,null
    */
    notes?: string | null;
    /**
     * @description Picks the primary engagement owner / account manager for this customer.
     * @type string,null, iri-reference
    */
    accountManager?: string | null;
    /**
     * @description Customers may be tagged (\"retainer\", \"vip\", \"ngo\") for filtering. We reuse\nthe workspace-wide Tag entity (scope=customer) rather than a Customer-only\ntag schema; that way Project / Task / Customer share one tag pool.
     * @type array | undefined
    */
    tags?: string[];
    /**
     * @type array | undefined
    */
    readonly contacts?: string[];
    /**
     * @type array | undefined
    */
    readonly projects?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type string,null
    */
    externalSource?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly company?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
    /**
     * @type string,null
    */
    readonly externalRef?: string | null;
};