/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Append-only snapshot of a Document at one save-point. Lets the wiki\nUI walk back through history and restore older bodies.\n\nCreated by DocumentRevisionListener whenever a Document\'s name or\nbody changes (preUpdate). The pre-existing values are snapshotted —\nthe listener writes the LAST KNOWN state, not the new one, so the\nrevision list reads like a real history (\"Stand vom Datum X\").\n\nRevisions are read-only — no Patch/Post via the API. Restoring goes\nthrough a custom action on Document, not by mutating the revision.
 */
export const documentRevisionJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "document": z.optional(z.string()),
"name": z.optional(z.string().default("").describe("Document name at the snapshot moment.")),
"body": z.string().describe("Body content at the snapshot moment. JSON for richtext, plain string for markdown/html.").nullish(),
"bodyFormat": z.optional(z.enum(["markdown", "html", "richtext"]).default("markdown")),
"author": z.string().describe("The user who authored THIS specific version (= the saver\nimmediately before the snapshot). Distinct from\nDocument.createdByUser which always points at the original\ncreator.").nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string())
    })).describe("Append-only snapshot of a Document at one save-point. Lets the wiki\nUI walk back through history and restore older bodies.\n\nCreated by DocumentRevisionListener whenever a Document's name or\nbody changes (preUpdate). The pre-existing values are snapshotted —\nthe listener writes the LAST KNOWN state, not the new one, so the\nrevision list reads like a real history (\"Stand vom Datum X\").\n\nRevisions are read-only — no Patch/Post via the API. Restoring goes\nthrough a custom action on Document, not by mutating the revision.")