/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const workspaceJsonMergePatchSchema = z.object({
    "name": z.optional(z.string()),
"slug": z.optional(z.string()),
"locale": z.optional(z.string().default("de")),
"timezone": z.optional(z.string().default("Europe/Berlin")),
"members": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"deleted": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    })