/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { fileVersionJsonldSchema } from "../fileVersion/jsonldSchema.ts";
import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Polymorphic file attachment. The \"file\" itself is metadata only — actual\nbytes live on Flysystem-managed storage and are addressed through\nFileVersion entries (one File can have N revisions; the latest is the\n\"current\" version, kept on this row for fast lookups).\n\nUploads happen through FileUploadController (multipart) and become version 1\nof a new File row. Subsequent versions add new FileVersion rows without\nmutating the File metadata.\n\nCross-tenant safety: workspace-scoped + voter delegates to the target entity.
 */
export const fileJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "target": z.optional(z.enum(["project", "task", "workspace", "user", "comment", "document"])),
"targetId": z.optional(z.uuid()),
"name": z.optional(z.string().describe("Display name (defaults to original filename, editable).")),
"description": z.string().nullish(),
"mimeType": z.string().describe("MIME type of the current version (denormalised for fast filtering).").nullish(),
"uploadedBy": z.string().nullish(),
"externalProvider": z.string().describe("For files imported from external storage (Google Drive, OneDrive,\nDropbox, …). When set, no FileVersion bytes are stored — the file is\na pointer.").nullish(),
"externalUrl": z.string().nullish(),
"isExternal": z.optional(z.boolean().default(false)),
"isHiddenForConnectUsers": z.optional(z.boolean().default(false)),
get "currentVersion"(){
                return z.union([fileVersionJsonldSchema, z.null()]).optional()
              },
get "versions"(){
                return z.array(fileVersionJsonldSchema).optional()
              },
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"external": z.optional(z.boolean()),
"hiddenForConnectUsers": z.optional(z.boolean()),
"size": z.int().describe("Convenience: byte size of the current version (or null for external/empty).").nullish(),
"deleted": z.optional(z.boolean())
    })).describe("Polymorphic file attachment. The \"file\" itself is metadata only — actual\nbytes live on Flysystem-managed storage and are addressed through\nFileVersion entries (one File can have N revisions; the latest is the\n\"current\" version, kept on this row for fast lookups).\n\nUploads happen through FileUploadController (multipart) and become version 1\nof a new File row. Subsequent versions add new FileVersion rows without\nmutating the File metadata.\n\nCross-tenant safety: workspace-scoped + voter delegates to the target entity.")