/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Something Worktide wants to send out through a {@see Channel}.\n\nLives independently of {@see InboundEvent} so the outbound\nlifecycle (queue → send → ack → bounce → open/click) has its\nown first-class state machine without mixing concerns. Reply-to-\nthread is expressed as `conversationId` + `inReplyToInboundEvent`,\nnot by mutating an inbound row.\n\nCreation paths:\n  1. User reply in the SPA conversation view\n  2. System notification (watcher fired, maintenance reminder)\n  3. AIRecommendation that the user approved\n\n`createdByUser` is required for messages to external recipients.\nThe OutboundQueue worker enforces this — auto-sending to a\ncustomer without a named operator is forbidden by policy (see\nAI-Vision: human-in-the-loop for external comms).\n\n`createdByRecommendation` (nullable) links back to the\nAIRecommendation row when the message originated from an AI\nsuggestion — useful for audit and for showing \"drafted by AI,\n * approved by Sven\" in the activity feed.\n\n`externalId` is the provider\'s tracking-id (SMTP queue-id,\nGraph internetMessageId, Mailgun message-id) — populated on send.
 */
export const outboundMessageJsonMergePatchSchema = z.object({
    "channel": z.optional(z.string()),
"recipientRaw": z.optional(z.string().describe("Raw recipient address as the operator typed it / as the\nsource thread captured it. Kept verbatim for audit even after\n`recipientContact` resolves to a Contact record.")),
"recipientContact": z.string().nullish(),
"additionalRecipients": z.optional(z.array(z.object({
    
    }).catchall(z.string().nullable())).describe("Additional recipients — Cc/Bcc for mail, mentioned-users for\nslack, etc. JSON list of {address, contactIri?, kind: 'cc'|'bcc'}.")),
"subject": z.string().nullish(),
"body": z.optional(z.string().default("")),
"attachments": z.optional(z.array(z.object({
    
    }).catchall(z.string().nullable())).describe("list of {fileIri, filename, mimeType, sizeBytes}")),
"conversation": z.string().nullish(),
"inReplyToInboundEvent": z.string().describe("The specific inbound event this message answers — drives the\nIn-Reply-To header for mail, the thread_ts for slack.").nullish(),
"createdByUser": z.string().nullish(),
"createdByRecommendationId": z.uuid().describe("Free-form FK to an AIRecommendation row (entity arrives in\nPhase D). Stored as a UUID column so this entity can ship\nbefore the AI tier exists; the FK constraint lands in the\nPhase-D migration.").nullish(),
"status": z.optional(z.enum(["queued", "sending", "sent", "failed", "bounced"]).default("queued")),
"statusReason": z.string().nullish(),
"attemptCount": z.optional(z.int().default(0)),
"sentAt": z.iso.datetime().nullish(),
"externalId": z.string().nullish(),
"openedAt": z.iso.datetime().nullish(),
"clickedAt": z.iso.datetime().nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"updatedByUser": z.string().nullish()
    }).describe("Something Worktide wants to send out through a {@see Channel}.\n\nLives independently of {@see InboundEvent} so the outbound\nlifecycle (queue → send → ack → bounce → open/click) has its\nown first-class state machine without mixing concerns. Reply-to-\nthread is expressed as `conversationId` + `inReplyToInboundEvent`,\nnot by mutating an inbound row.\n\nCreation paths:\n  1. User reply in the SPA conversation view\n  2. System notification (watcher fired, maintenance reminder)\n  3. AIRecommendation that the user approved\n\n`createdByUser` is required for messages to external recipients.\nThe OutboundQueue worker enforces this — auto-sending to a\ncustomer without a named operator is forbidden by policy (see\nAI-Vision: human-in-the-loop for external comms).\n\n`createdByRecommendation` (nullable) links back to the\nAIRecommendation row when the message originated from an AI\nsuggestion — useful for audit and for showing \"drafted by AI,\n * approved by Sven\" in the activity feed.\n\n`externalId` is the provider's tracking-id (SMTP queue-id,\nGraph internetMessageId, Mailgun message-id) — populated on send.")