/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Per-user weekly working capacity in MINUTES per weekday. Replaces awork\'s\n`UserWeeklyCapacity` object — flattened into the row so reporting queries\ndon\'t need to join an embedded.\n\nOne row per user, enforced by the unique constraint on user_id. Default\n= 0 minutes everywhere; UI should pre-fill 480 (8h) on weekdays for new\nusers.
*/
export type UserCapacityHtml = {
    /**
     * @type string | undefined, iri-reference
    */
    user?: string;
    /**
     * @default 0
     * @type integer | undefined
    */
    monMinutes?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    tueMinutes?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    wedMinutes?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    thuMinutes?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    friMinutes?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    satMinutes?: number;
    /**
     * @default 0
     * @type integer | undefined
    */
    sunMinutes?: number;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type integer | undefined
    */
    readonly weeklyMinutes?: number;
};