/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Reusable blueprint for a Project. Captures the project\'s \"defaults\"\n(name, description, color, projectType, billing flags) plus a reference\nto a TaskBundle whose templates become the initial Tasks when this\nproject template is instantiated.\n\n`instantiate` (controller action) creates a new Project + copies bundle\ntemplates into real Tasks, dueDates relative to the new project\'s start.
 */
export const projectTemplateJsonMergePatchSchema = z.object({
    "name": z.optional(z.string()),
"description": z.string().nullish(),
"color": z.optional(z.string().default("#6366f1")),
"projectType": z.string().nullish(),
"taskBundle": z.string().nullish(),
"defaultBudgetMinutes": z.int().describe("Defaults that flow into the instantiated Project.").nullish(),
"defaultIsBillableByDefault": z.optional(z.boolean().default(true)),
"defaultDeductNonBillableHours": z.optional(z.boolean().default(false)),
"defaultIsMultiAssignmentAllowed": z.optional(z.boolean().default(true)),
"defaultIsRetainer": z.optional(z.boolean().default(false)),
"isPublished": z.optional(z.boolean().default(true)),
"isArchived": z.optional(z.boolean().default(false)),
"tags": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"published": z.optional(z.boolean()),
"archived": z.optional(z.boolean()),
"deleted": z.optional(z.boolean())
    }).describe("Reusable blueprint for a Project. Captures the project's \"defaults\"\n(name, description, color, projectType, billing flags) plus a reference\nto a TaskBundle whose templates become the initial Tasks when this\nproject template is instantiated.\n\n`instantiate` (controller action) creates a new Project + copies bundle\ntemplates into real Tasks, dueDates relative to the new project's start.")