/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type EntityChangeOutboxJsonMergePatchStatusEnum = "pending" | "sending" | "sent" | "partial" | "failed" | "conflict" | "dead";

/**
 * @description Outbox table that records every Worktide-side change to an\nentity that\'s mirrored in at least one external system.\n\nSame pattern as {@see OutboundMessage} for mail: write the\nintent transactionally with the entity change, let a separate\nworker dispatch to the adapters. Decouples the API request\nlatency from the external-system reachability — a slow Jira\nnever blocks a Worktide save.\n\nThe row is fanned out to ALL EntitySync mappings for the\n(entityType, entityId) at processing time, not at write time.\nThat way a mapping added between change and dispatch still\nreceives the update.\n\n`changedFields` + `previousValues` are sparse: only the fields\nthat actually changed in this Doctrine flush. Adapters use this\nto construct minimal PATCH requests and for conflict detection\n(if previousValue !== externalCurrentValue → conflict).\n\nRe-entry guard: the {@see \\App\\Channels\\SyncReentryGuard} flag\nis set while inbound sync writes are being applied; the\nlistener that creates these rows skips writes during that\nwindow so an inbound update doesn\'t bounce right back to the\nsource.
*/
export type EntityChangeOutboxJsonMergePatch = {
    /**
     * @type string | undefined
    */
    entityType?: string;
    /**
     * @type string | undefined, uuid
    */
    entityId?: string;
    /**
     * @type object | undefined
    */
    changedFields?: {
        [key: string]: string | null;
    };
    /**
     * @type object | undefined
    */
    previousValues?: {
        [key: string]: string | null;
    };
    /**
     * @default false
     * @type boolean | undefined
    */
    isDelete?: boolean;
    /**
     * @default "pending"
     * @type string | undefined
    */
    status?: EntityChangeOutboxJsonMergePatchStatusEnum;
    /**
     * @default 0
     * @type integer | undefined
    */
    attemptCount?: number;
    /**
     * @description Earliest time the worker is allowed to claim this row again.
     * @type string | undefined, date-time
    */
    nextAttemptAt?: string;
    /**
     * @type string,null
    */
    lastError?: string | null;
    /**
     * @type string,null, date-time
    */
    processedAt?: string | null;
    /**
     * @description Per-mapping outcome — JSON map `entitySyncId → {result, etag,\nexternalUpdatedAt, error}` so the worker can do partial\nretries (only the failed mappings) without re-pushing to the\nadapters that already succeeded.
     * @type object | undefined
    */
    perMappingState?: {
        [key: string]: string | null;
    };
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly delete?: boolean;
};