/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Workspace invitation: an owner/admin types an email + role, this entity\nstores a unique opaque accept-token, and the invitee turns into a\nWorkspaceMember once they hit POST /v1/workspace_invitations/{token}/accept.\n\nFlow:\n  POST /v1/workspace_invitations    →  status=pending, token returned ONCE\n  POST .../{token}/accept           →  creates User if needed, links membership\n                                       with the chosen role, status=accepted\n  DELETE /v1/workspace_invitations/{id}  →  revokes a pending invite\n\nThe token plaintext is shown only in the creation response so the operator\ncan ship a magic link to the invitee. After that, the DB column is the\nopaque value we compare against incoming accepts (no hashing here — the\nthreat model is leaked email content, not a leaked DB dump; the token\'s\nvalue is its unguessability, and acceptance permanently consumes it).\n\nRole validation prevents creating Owner invitations — workspace owners are\nset by the workspace-creation flow, not handed out on email.
 */
export const workspaceInvitationHtmlSchema = z.object({
    "email": z.email(),
"role": z.optional(z.enum(["owner", "admin", "member", "guest"]).default("member")),
"status": z.optional(z.enum(["pending", "accepted", "expired", "revoked"]).default("pending")),
"expiresAt": z.optional(z.iso.datetime()),
"acceptedAt": z.iso.datetime().nullish(),
"acceptedBy": z.string().nullish(),
"plaintextToken": z.string().describe("Plaintext invite URL (or just the raw token) — only populated on POST\nso the response body carries it to the operator for copy-paste / mail\ndispatch. Never persisted, never returned afterwards.").nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish()
    }).describe("Workspace invitation: an owner/admin types an email + role, this entity\nstores a unique opaque accept-token, and the invitee turns into a\nWorkspaceMember once they hit POST /v1/workspace_invitations/{token}/accept.\n\nFlow:\n  POST /v1/workspace_invitations    →  status=pending, token returned ONCE\n  POST .../{token}/accept           →  creates User if needed, links membership\n                                       with the chosen role, status=accepted\n  DELETE /v1/workspace_invitations/{id}  →  revokes a pending invite\n\nThe token plaintext is shown only in the creation response so the operator\ncan ship a magic link to the invitee. After that, the DB column is the\nopaque value we compare against incoming accepts (no hashing here — the\nthreat model is leaked email content, not a leaked DB dump; the token's\nvalue is its unguessability, and acceptance permanently consumes it).\n\nRole validation prevents creating Owner invitations — workspace owners are\nset by the workspace-creation flow, not handed out on email.")