/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Personal absence — vacation, sick leave, etc. Linked to a user; counts\nagainst their UserCapacity when computing availability.\n\nBeyond awork: we have a `type` enum (vacation / sick / personal /\nholiday / other) for filtering and reporting. awork doesn\'t model this,\nso its UI relies on `description` heuristics.\n\nHalf-day flags follow awork\'s semantics: if both start and end are the\nsame date, only one half-day flag matters.
 */
export const absenceJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "user": z.optional(z.string()),
"startsOn": z.optional(z.iso.datetime()),
"endsOn": z.optional(z.iso.datetime()),
"type": z.optional(z.string().default("vacation")),
"description": z.string().nullish(),
"isHalfDayOnStart": z.optional(z.boolean().default(false)),
"isHalfDayOnEnd": z.optional(z.boolean().default(false)),
"isReadOnly": z.optional(z.boolean().default(false).describe("Imported from an external calendar — editable only via re-import.")),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"halfDayOnStart": z.optional(z.boolean()),
"halfDayOnEnd": z.optional(z.boolean()),
"readOnly": z.optional(z.boolean()),
"deleted": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    })).describe("Personal absence — vacation, sick leave, etc. Linked to a user; counts\nagainst their UserCapacity when computing availability.\n\nBeyond awork: we have a `type` enum (vacation / sick / personal /\nholiday / other) for filtering and reporting. awork doesn't model this,\nso its UI relies on `description` heuristics.\n\nHalf-day flags follow awork's semantics: if both start and end are the\nsame date, only one half-day flag matters.")