/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Sub-todo on a Task. Lightweight by design — for proper sub-work items use\nTask.parent (subtasks). Checklists are visual tick-boxes shown inside the\ntask detail panel.\n\nGoing beyond awork: we track who checked the item off and when, so the\nactivity feed can attribute the tick to a user (awork\'s schema doesn\'t\nexpose checkedBy / checkedOn).
*/
export type ChecklistItemJsonMergePatch = {
    /**
     * @type string | undefined, iri-reference
    */
    task?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    isDone?: boolean;
    /**
     * @default 0
     * @type number | undefined
    */
    position?: number;
    /**
     * @type string,null, iri-reference
    */
    checkedBy?: string | null;
    /**
     * @type string,null, date-time
    */
    readonly checkedOn?: string | null;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly done?: boolean;
};