/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description A workspace-scoped customer record — the agency\'s view of one client.\n\nThis is *deliberately* not modeled like awork\'s `Company` entity, which\nexisted only as an FK on Project (no first-class customer DB). In Worktide\neach Workspace owns a full CRM of Customers; Projects optionally link to a\nCustomer, ServiceSubscriptions hang off CustomerSystems (Phase 3 block 2),\nand the TYPO3 client portal will read this same table.\n\n`isCompany` flips the schema between \"company with VAT and legalName\" and\n\"private person with first/last name\". The flat `addressLine1/2/zip/city/\ncountry` fields are good enough for the MVP — a future block can move\naddresses into a polymorphic Address entity if we need multi-address\n(billing / shipping / visit).\n\nLifecycle: Prospect → Active → Inactive | Churned → Archived. The status\nfield is informational — no automated transitions yet; an operator\npatches it as the relationship evolves.
 */
export const customerJsonMergePatchSchema = z.object({
    "name": z.optional(z.string().describe("Display name — usually the company name; for individuals, \"Lastname, Firstname\".")),
"legalName": z.string().describe("Formal company name for invoices (\"Foo GmbH & Co. KG\") — only meaningful when isCompany.").nullish(),
"isCompany": z.optional(z.boolean().default(true)),
"vatId": z.string().nullish(),
"email": z.email().nullish(),
"phone": z.string().nullish(),
"website": z.url().nullish(),
"industry": z.string().nullish(),
"addressLine1": z.string().nullish(),
"addressLine2": z.string().nullish(),
"zip": z.string().nullish(),
"city": z.string().nullish(),
"country": z.string().describe("ISO 3166-1 alpha-2 (e.g. \"DE\", \"AT\") — optional, stored uppercase.").nullish(),
"status": z.optional(z.enum(["prospect", "active", "inactive", "churned", "archived"]).default("active")),
"notes": z.string().nullish(),
"accountManager": z.string().describe("Picks the primary engagement owner / account manager for this customer.").nullish(),
"tags": z.optional(z.array(z.string()).describe("Customers may be tagged (\"retainer\", \"vip\", \"ngo\") for filtering. We reuse\nthe workspace-wide Tag entity (scope=customer) rather than a Customer-only\ntag schema; that way Project / Task / Customer share one tag pool.")),
"contacts": z.optional(z.array(z.string())),
"projects": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"company": z.optional(z.boolean()),
"deleted": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    }).describe("A workspace-scoped customer record — the agency's view of one client.\n\nThis is *deliberately* not modeled like awork's `Company` entity, which\nexisted only as an FK on Project (no first-class customer DB). In Worktide\neach Workspace owns a full CRM of Customers; Projects optionally link to a\nCustomer, ServiceSubscriptions hang off CustomerSystems (Phase 3 block 2),\nand the TYPO3 client portal will read this same table.\n\n`isCompany` flips the schema between \"company with VAT and legalName\" and\n\"private person with first/last name\". The flat `addressLine1/2/zip/city/\ncountry` fields are good enough for the MVP — a future block can move\naddresses into a polymorphic Address entity if we need multi-address\n(billing / shipping / visit).\n\nLifecycle: Prospect → Active → Inactive | Churned → Archived. The status\nfield is informational — no automated transitions yet; an operator\npatches it as the relationship evolves.")