/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const taskStatusHtmlSchema = z.object({
    "name": z.optional(z.string()),
"color": z.optional(z.string().default("#94a3b8")),
"position": z.optional(z.int().default(0)),
"isCompleted": z.optional(z.boolean().default(false)),
"isDefault": z.optional(z.boolean().default(false)),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"completed": z.optional(z.boolean()),
"default": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    })