/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Reusable group of TaskTemplates. Bundles are the unit that gets \"applied\"\nto a project (via apply-bundle) and the building block ProjectTemplate\nuses to define what tasks come with a new project.\n\nMirrors awork\'s TaskBundle category — they call this \"the 29-op heavy\" but\n80% of those ops are CRUD on the nested TaskTemplate; our flat /v1/task_templates\ncollection covers it with workspace-aware filters.
*/
export type TaskBundleJsonMergePatch = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    description?: string | null;
    /**
     * @default "#6366f1"
     * @type string | undefined
    */
    color?: string;
    /**
     * @default false
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @type array | undefined
    */
    readonly taskTemplates?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly archived?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
};