/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../HydraItemBaseSchema.ts";

export type UserJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    password?: string;
    /**
     * @type array | undefined
    */
    roles?: string[];
    /**
     * @default ""
     * @type string | undefined
    */
    firstName?: string;
    /**
     * @default ""
     * @type string | undefined
    */
    lastName?: string;
    /**
     * @type string,null, date-time
    */
    lastLoginAt?: string | null;
    /**
     * @type array | undefined
    */
    readonly workspaceMemberships?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null
    */
    externalSource?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @type string | undefined
    */
    readonly userIdentifier?: string;
    /**
     * @type string | undefined
    */
    readonly fullName?: string;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
    /**
     * @type string,null
    */
    readonly externalRef?: string | null;
});