/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description One step the Automation runs when triggered. Multiple Actions per\nAutomation run in `position` order; if one fails the remainder still\nexecute (best-effort). config shape is type-specific:\n\n  task.set_status      { statusId: uuid }\n  task.set_priority    { priority: low|normal|high|urgent }\n  task.add_tag         { tagId: uuid }\n  task.assign_user     { userId: uuid }\n  task.post_comment    { content: string }\n  task.close           — no config\n\nAction targets the Task that triggered the parent Automation (we don\'t\ncross-target yet; in awork actions can fan out — that\'s a future block).
 */
export const automationActionJsonMergePatchSchema = z.object({
    "automation": z.optional(z.string()),
"type": z.optional(z.enum(["task.set_status", "task.set_priority", "task.add_tag", "task.assign_user", "task.post_comment", "task.close"])),
"config": z.optional(z.object({
    
    }).catchall(z.string().nullable())),
"position": z.optional(z.int().default(0)),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish()
    }).describe("One step the Automation runs when triggered. Multiple Actions per\nAutomation run in `position` order; if one fails the remainder still\nexecute (best-effort). config shape is type-specific:\n\n  task.set_status      { statusId: uuid }\n  task.set_priority    { priority: low|normal|high|urgent }\n  task.add_tag         { tagId: uuid }\n  task.assign_user     { userId: uuid }\n  task.post_comment    { content: string }\n  task.close           — no config\n\nAction targets the Task that triggered the parent Automation (we don't\ncross-target yet; in awork actions can fan out — that's a future block).")