/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../HydraItemBaseSchema.ts";

/**
 * @description Membership of a Task in a TaskList, with per-list ordering.\n\nModelled as an explicit join entity (rather than a plain ManyToMany\njunction) so each placement carries its own ordering — moving a task\nbetween lists doesn\'t lose its position in the others.\n\nUnique constraint on (list, task) prevents the same task being added\nto the same list twice.
*/
export type TaskListEntryJsonld = (HydraItemBaseSchema & {
    /**
     * @type string | undefined, iri-reference
    */
    list?: string;
    /**
     * @type string | undefined, iri-reference
    */
    task?: string;
    /**
     * @default 0
     * @type number | undefined
    */
    position?: number;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
});