/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CommentReactionJsonld = {
    /**
     * @type string | undefined, iri-reference
    */
    comment?: string;
    /**
     * @type string | undefined, iri-reference
    */
    user?: string;
    /**
     * @type string | undefined
    */
    emoji?: string;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
};