/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const commentReactionHtmlSchema = z.object({
    "comment": z.optional(z.string()),
"user": z.optional(z.string()),
"emoji": z.optional(z.string()),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime())
    })