/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AutomationJsonld } from "./automation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiAutomationsIdGetPathParams = {
    /**
     * @description Automation identifier
     * @type string
    */
    id: string;
};

/**
 * @description Automation resource
*/
export type ApiAutomationsIdGet200 = AutomationJsonld;

/**
 * @description Forbidden
*/
export type ApiAutomationsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiAutomationsIdGet404 = ErrorJsonld;

export type ApiAutomationsIdGetQueryResponse = ApiAutomationsIdGet200;

export type ApiAutomationsIdGetQuery = {
    Response: ApiAutomationsIdGet200;
    PathParams: ApiAutomationsIdGetPathParams;
    Errors: ApiAutomationsIdGet403 | ApiAutomationsIdGet404;
};