/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Absence } from "./Absence.ts";
import type { AbsenceJsonld } from "./absence/Jsonld.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

/**
 * @description Absence resource created
*/
export type ApiAbsencesPost201 = AbsenceJsonld;

/**
 * @description Invalid input
*/
export type ApiAbsencesPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiAbsencesPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiAbsencesPost422 = ConstraintViolationJsonld;

/**
 * @description The new Absence resource
*/
export type ApiAbsencesPostMutationRequest = Omit<NonNullable<Absence>, "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "halfDayOnStart" | "halfDayOnEnd" | "readOnly" | "deleted" | "externalRef">;

export type ApiAbsencesPostMutationResponse = ApiAbsencesPost201;

export type ApiAbsencesPostMutation = {
    Response: ApiAbsencesPost201;
    Request: ApiAbsencesPostMutationRequest;
    Errors: ApiAbsencesPost400 | ApiAbsencesPost403 | ApiAbsencesPost422;
};