/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AutomationActionJsonld } from "./automationAction/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiAutomationActionsIdGetPathParams = {
    /**
     * @description AutomationAction identifier
     * @type string
    */
    id: string;
};

/**
 * @description AutomationAction resource
*/
export type ApiAutomationActionsIdGet200 = AutomationActionJsonld;

/**
 * @description Forbidden
*/
export type ApiAutomationActionsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiAutomationActionsIdGet404 = ErrorJsonld;

export type ApiAutomationActionsIdGetQueryResponse = ApiAutomationActionsIdGet200;

export type ApiAutomationActionsIdGetQuery = {
    Response: ApiAutomationActionsIdGet200;
    PathParams: ApiAutomationActionsIdGetPathParams;
    Errors: ApiAutomationActionsIdGet403 | ApiAutomationActionsIdGet404;
};