/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AutomationJsonMergePatch } from "./automation/JsonMergePatch.ts";
import type { AutomationJsonld } from "./automation/Jsonld.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiAutomationsIdPatchPathParams = {
    /**
     * @description Automation identifier
     * @type string
    */
    id: string;
};

/**
 * @description Automation resource updated
*/
export type ApiAutomationsIdPatch200 = AutomationJsonld;

/**
 * @description Invalid input
*/
export type ApiAutomationsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiAutomationsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiAutomationsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiAutomationsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Automation resource
*/
export type ApiAutomationsIdPatchMutationRequest = Omit<NonNullable<AutomationJsonMergePatch>, "actions" | "id" | "createdAt" | "updatedAt" | "version" | "enabled">;

export type ApiAutomationsIdPatchMutationResponse = ApiAutomationsIdPatch200;

export type ApiAutomationsIdPatchMutation = {
    Response: ApiAutomationsIdPatch200;
    Request: ApiAutomationsIdPatchMutationRequest;
    PathParams: ApiAutomationsIdPatchPathParams;
    Errors: ApiAutomationsIdPatch400 | ApiAutomationsIdPatch403 | ApiAutomationsIdPatch404 | ApiAutomationsIdPatch422;
};