/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ActiveTimerJsonld } from "./activeTimer/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiActiveTimersIdGetPathParams = {
    /**
     * @description ActiveTimer identifier
     * @type string
    */
    id: string;
};

/**
 * @description ActiveTimer resource
*/
export type ApiActiveTimersIdGet200 = ActiveTimerJsonld;

/**
 * @description Forbidden
*/
export type ApiActiveTimersIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiActiveTimersIdGet404 = ErrorJsonld;

export type ApiActiveTimersIdGetQueryResponse = ApiActiveTimersIdGet200;

export type ApiActiveTimersIdGetQuery = {
    Response: ApiActiveTimersIdGet200;
    PathParams: ApiActiveTimersIdGetPathParams;
    Errors: ApiActiveTimersIdGet403 | ApiActiveTimersIdGet404;
};