/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AbsenceRegionJsonMergePatch } from "./absenceRegion/JsonMergePatch.ts";
import type { AbsenceRegionJsonld } from "./absenceRegion/Jsonld.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiAbsenceRegionsIdPatchPathParams = {
    /**
     * @description AbsenceRegion identifier
     * @type string
    */
    id: string;
};

/**
 * @description AbsenceRegion resource updated
*/
export type ApiAbsenceRegionsIdPatch200 = AbsenceRegionJsonld;

/**
 * @description Invalid input
*/
export type ApiAbsenceRegionsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiAbsenceRegionsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiAbsenceRegionsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiAbsenceRegionsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated AbsenceRegion resource
*/
export type ApiAbsenceRegionsIdPatchMutationRequest = Omit<NonNullable<AbsenceRegionJsonMergePatch>, "users" | "id" | "createdAt" | "updatedAt" | "version">;

export type ApiAbsenceRegionsIdPatchMutationResponse = ApiAbsenceRegionsIdPatch200;

export type ApiAbsenceRegionsIdPatchMutation = {
    Response: ApiAbsenceRegionsIdPatch200;
    Request: ApiAbsenceRegionsIdPatchMutationRequest;
    PathParams: ApiAbsenceRegionsIdPatchPathParams;
    Errors: ApiAbsenceRegionsIdPatch400 | ApiAbsenceRegionsIdPatch403 | ApiAbsenceRegionsIdPatch404 | ApiAbsenceRegionsIdPatch422;
};