/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AbsenceJsonMergePatch } from "./absence/JsonMergePatch.ts";
import type { AbsenceJsonld } from "./absence/Jsonld.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiAbsencesIdPatchPathParams = {
    /**
     * @description Absence identifier
     * @type string
    */
    id: string;
};

/**
 * @description Absence resource updated
*/
export type ApiAbsencesIdPatch200 = AbsenceJsonld;

/**
 * @description Invalid input
*/
export type ApiAbsencesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiAbsencesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiAbsencesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiAbsencesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Absence resource
*/
export type ApiAbsencesIdPatchMutationRequest = Omit<NonNullable<AbsenceJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "halfDayOnStart" | "halfDayOnEnd" | "readOnly" | "deleted" | "externalRef">;

export type ApiAbsencesIdPatchMutationResponse = ApiAbsencesIdPatch200;

export type ApiAbsencesIdPatchMutation = {
    Response: ApiAbsencesIdPatch200;
    Request: ApiAbsencesIdPatchMutationRequest;
    PathParams: ApiAbsencesIdPatchPathParams;
    Errors: ApiAbsencesIdPatch400 | ApiAbsencesIdPatch403 | ApiAbsencesIdPatch404 | ApiAbsencesIdPatch422;
};