/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CustomerSystemJsonld } from "./customerSystem/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomerSystemsIdGetPathParams = {
    /**
     * @description CustomerSystem identifier
     * @type string
    */
    id: string;
};

/**
 * @description CustomerSystem resource
*/
export type ApiCustomerSystemsIdGet200 = CustomerSystemJsonld;

/**
 * @description Forbidden
*/
export type ApiCustomerSystemsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCustomerSystemsIdGet404 = ErrorJsonld;

export type ApiCustomerSystemsIdGetQueryResponse = ApiCustomerSystemsIdGet200;

export type ApiCustomerSystemsIdGetQuery = {
    Response: ApiCustomerSystemsIdGet200;
    PathParams: ApiCustomerSystemsIdGetPathParams;
    Errors: ApiCustomerSystemsIdGet403 | ApiCustomerSystemsIdGet404;
};