/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiContactsIdDeletePathParams = {
    /**
     * @description Contact identifier
     * @type string
    */
    id: string;
};

/**
 * @description Contact resource deleted
*/
export type ApiContactsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiContactsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiContactsIdDelete404 = ErrorJsonld;

export type ApiContactsIdDeleteMutationResponse = ApiContactsIdDelete204;

export type ApiContactsIdDeleteMutation = {
    Response: ApiContactsIdDelete204;
    PathParams: ApiContactsIdDeletePathParams;
    Errors: ApiContactsIdDelete403 | ApiContactsIdDelete404;
};