/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ContactJsonld } from "./contact/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiContactsIdGetPathParams = {
    /**
     * @description Contact identifier
     * @type string
    */
    id: string;
};

/**
 * @description Contact resource
*/
export type ApiContactsIdGet200 = ContactJsonld;

/**
 * @description Forbidden
*/
export type ApiContactsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiContactsIdGet404 = ErrorJsonld;

export type ApiContactsIdGetQueryResponse = ApiContactsIdGet200;

export type ApiContactsIdGetQuery = {
    Response: ApiContactsIdGet200;
    PathParams: ApiContactsIdGetPathParams;
    Errors: ApiContactsIdGet403 | ApiContactsIdGet404;
};