/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CustomFieldValueJsonld } from "./customFieldValue/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomFieldValuesIdGetPathParams = {
    /**
     * @description CustomFieldValue identifier
     * @type string
    */
    id: string;
};

/**
 * @description CustomFieldValue resource
*/
export type ApiCustomFieldValuesIdGet200 = CustomFieldValueJsonld;

/**
 * @description Not found
*/
export type ApiCustomFieldValuesIdGet404 = ErrorJsonld;

export type ApiCustomFieldValuesIdGetQueryResponse = ApiCustomFieldValuesIdGet200;

export type ApiCustomFieldValuesIdGetQuery = {
    Response: ApiCustomFieldValuesIdGet200;
    PathParams: ApiCustomFieldValuesIdGetPathParams;
    Errors: ApiCustomFieldValuesIdGet404;
};