/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiConversationsIdDeletePathParams = {
    /**
     * @description Conversation identifier
     * @type string
    */
    id: string;
};

/**
 * @description Conversation resource deleted
*/
export type ApiConversationsIdDelete204 = unknown;

/**
 * @description Not found
*/
export type ApiConversationsIdDelete404 = ErrorJsonld;

export type ApiConversationsIdDeleteMutationResponse = ApiConversationsIdDelete204;

export type ApiConversationsIdDeleteMutation = {
    Response: ApiConversationsIdDelete204;
    PathParams: ApiConversationsIdDeletePathParams;
    Errors: ApiConversationsIdDelete404;
};