/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CustomFieldDefinition } from "./CustomFieldDefinition.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { CustomFieldDefinitionJsonld } from "./customFieldDefinition/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

/**
 * @description CustomFieldDefinition resource created
*/
export type ApiCustomFieldDefinitionsPost201 = CustomFieldDefinitionJsonld;

/**
 * @description Invalid input
*/
export type ApiCustomFieldDefinitionsPost400 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiCustomFieldDefinitionsPost422 = ConstraintViolationJsonld;

/**
 * @description The new CustomFieldDefinition resource
*/
export type ApiCustomFieldDefinitionsPostMutationRequest = Omit<NonNullable<CustomFieldDefinition>, "id" | "createdAt" | "updatedAt" | "version" | "required" | "archived">;

export type ApiCustomFieldDefinitionsPostMutationResponse = ApiCustomFieldDefinitionsPost201;

export type ApiCustomFieldDefinitionsPostMutation = {
    Response: ApiCustomFieldDefinitionsPost201;
    Request: ApiCustomFieldDefinitionsPostMutationRequest;
    Errors: ApiCustomFieldDefinitionsPost400 | ApiCustomFieldDefinitionsPost422;
};