/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Comment } from "./Comment.ts";
import type { CommentJsonld } from "./comment/Jsonld.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

/**
 * @description Comment resource created
*/
export type ApiCommentsPost201 = CommentJsonld;

/**
 * @description Invalid input
*/
export type ApiCommentsPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiCommentsPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiCommentsPost422 = ConstraintViolationJsonld;

/**
 * @description The new Comment resource
*/
export type ApiCommentsPostMutationRequest = Omit<NonNullable<Comment>, "editedAt" | "pinnedAt" | "pinnedBy" | "reactions" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "pinned" | "resolved" | "hiddenForConnectUsers" | "deleted">;

export type ApiCommentsPostMutationResponse = ApiCommentsPost201;

export type ApiCommentsPostMutation = {
    Response: ApiCommentsPost201;
    Request: ApiCommentsPostMutationRequest;
    Errors: ApiCommentsPost400 | ApiCommentsPost403 | ApiCommentsPost422;
};