/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CustomFieldDefinitionJsonld } from "./customFieldDefinition/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomFieldDefinitionsIdGetPathParams = {
    /**
     * @description CustomFieldDefinition identifier
     * @type string
    */
    id: string;
};

/**
 * @description CustomFieldDefinition resource
*/
export type ApiCustomFieldDefinitionsIdGet200 = CustomFieldDefinitionJsonld;

/**
 * @description Not found
*/
export type ApiCustomFieldDefinitionsIdGet404 = ErrorJsonld;

export type ApiCustomFieldDefinitionsIdGetQueryResponse = ApiCustomFieldDefinitionsIdGet200;

export type ApiCustomFieldDefinitionsIdGetQuery = {
    Response: ApiCustomFieldDefinitionsIdGet200;
    PathParams: ApiCustomFieldDefinitionsIdGetPathParams;
    Errors: ApiCustomFieldDefinitionsIdGet404;
};