/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CommentJsonMergePatch } from "./comment/JsonMergePatch.ts";
import type { CommentJsonld } from "./comment/Jsonld.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCommentsIdPatchPathParams = {
    /**
     * @description Comment identifier
     * @type string
    */
    id: string;
};

/**
 * @description Comment resource updated
*/
export type ApiCommentsIdPatch200 = CommentJsonld;

/**
 * @description Invalid input
*/
export type ApiCommentsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiCommentsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCommentsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiCommentsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Comment resource
*/
export type ApiCommentsIdPatchMutationRequest = Omit<NonNullable<CommentJsonMergePatch>, "editedAt" | "pinnedAt" | "pinnedBy" | "reactions" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "pinned" | "resolved" | "hiddenForConnectUsers" | "deleted">;

export type ApiCommentsIdPatchMutationResponse = ApiCommentsIdPatch200;

export type ApiCommentsIdPatchMutation = {
    Response: ApiCommentsIdPatch200;
    Request: ApiCommentsIdPatchMutationRequest;
    PathParams: ApiCommentsIdPatchPathParams;
    Errors: ApiCommentsIdPatch400 | ApiCommentsIdPatch403 | ApiCommentsIdPatch404 | ApiCommentsIdPatch422;
};