/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomerSystemsIdDeletePathParams = {
    /**
     * @description CustomerSystem identifier
     * @type string
    */
    id: string;
};

/**
 * @description CustomerSystem resource deleted
*/
export type ApiCustomerSystemsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiCustomerSystemsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCustomerSystemsIdDelete404 = ErrorJsonld;

export type ApiCustomerSystemsIdDeleteMutationResponse = ApiCustomerSystemsIdDelete204;

export type ApiCustomerSystemsIdDeleteMutation = {
    Response: ApiCustomerSystemsIdDelete204;
    PathParams: ApiCustomerSystemsIdDeletePathParams;
    Errors: ApiCustomerSystemsIdDelete403 | ApiCustomerSystemsIdDelete404;
};