/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChecklistItemJsonld } from "./checklistItem/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiChecklistItemsIdGetPathParams = {
    /**
     * @description ChecklistItem identifier
     * @type string
    */
    id: string;
};

/**
 * @description ChecklistItem resource
*/
export type ApiChecklistItemsIdGet200 = ChecklistItemJsonld;

/**
 * @description Forbidden
*/
export type ApiChecklistItemsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiChecklistItemsIdGet404 = ErrorJsonld;

export type ApiChecklistItemsIdGetQueryResponse = ApiChecklistItemsIdGet200;

export type ApiChecklistItemsIdGetQuery = {
    Response: ApiChecklistItemsIdGet200;
    PathParams: ApiChecklistItemsIdGetPathParams;
    Errors: ApiChecklistItemsIdGet403 | ApiChecklistItemsIdGet404;
};