/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ContactJsonld } from "./contact/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiContactsGetCollectionQueryParamsOrderlastNameEnum = "asc" | "desc";

export type ApiContactsGetCollectionQueryParamsOrderfirstNameEnum = "asc" | "desc";

export type ApiContactsGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiContactsGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    customer?: string;
    /**
     * @type array | undefined
    */
    "customer[]"?: string[];
    /**
     * @type string | undefined
    */
    firstName?: string;
    /**
     * @type string | undefined
    */
    lastName?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type boolean | undefined
    */
    isPrimary?: boolean;
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[lastName]"?: ApiContactsGetCollectionQueryParamsOrderlastNameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[firstName]"?: ApiContactsGetCollectionQueryParamsOrderfirstNameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiContactsGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description Contact collection
*/
export type ApiContactsGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: ContactJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiContactsGetCollection403 = ErrorJsonld;

export type ApiContactsGetCollectionQueryResponse = ApiContactsGetCollection200;

export type ApiContactsGetCollectionQuery = {
    Response: ApiContactsGetCollection200;
    QueryParams: ApiContactsGetCollectionQueryParams;
    Errors: ApiContactsGetCollection403;
};