/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CommentJsonld } from "./comment/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCommentsIdGetPathParams = {
    /**
     * @description Comment identifier
     * @type string
    */
    id: string;
};

/**
 * @description Comment resource
*/
export type ApiCommentsIdGet200 = CommentJsonld;

/**
 * @description Forbidden
*/
export type ApiCommentsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCommentsIdGet404 = ErrorJsonld;

export type ApiCommentsIdGetQueryResponse = ApiCommentsIdGet200;

export type ApiCommentsIdGetQuery = {
    Response: ApiCommentsIdGet200;
    PathParams: ApiCommentsIdGetPathParams;
    Errors: ApiCommentsIdGet403 | ApiCommentsIdGet404;
};