/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConversationJsonld } from "./conversation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiConversationsIdGetPathParams = {
    /**
     * @description Conversation identifier
     * @type string
    */
    id: string;
};

/**
 * @description Conversation resource
*/
export type ApiConversationsIdGet200 = ConversationJsonld;

/**
 * @description Not found
*/
export type ApiConversationsIdGet404 = ErrorJsonld;

export type ApiConversationsIdGetQueryResponse = ApiConversationsIdGet200;

export type ApiConversationsIdGetQuery = {
    Response: ApiConversationsIdGet200;
    PathParams: ApiConversationsIdGetPathParams;
    Errors: ApiConversationsIdGet404;
};