/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { CustomerJsonld } from "./customer/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomersGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiCustomersGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiCustomersGetCollectionQueryParamsOrderupdatedAtEnum = "asc" | "desc";

export type ApiCustomersGetCollectionQueryParamsOrderstatusEnum = "asc" | "desc";

export type ApiCustomersGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    legalName?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    status?: string;
    /**
     * @type array | undefined
    */
    "status[]"?: string[];
    /**
     * @type string | undefined
    */
    industry?: string;
    /**
     * @type string | undefined
    */
    "tags.id"?: string;
    /**
     * @type array | undefined
    */
    "tags.id[]"?: string[];
    /**
     * @type boolean | undefined
    */
    isCompany?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[deletedAt]"?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiCustomersGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiCustomersGetCollectionQueryParamsOrdercreatedAtEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[updatedAt]"?: ApiCustomersGetCollectionQueryParamsOrderupdatedAtEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[status]"?: ApiCustomersGetCollectionQueryParamsOrderstatusEnum;
};

/**
 * @description Customer collection
*/
export type ApiCustomersGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: CustomerJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiCustomersGetCollection403 = ErrorJsonld;

export type ApiCustomersGetCollectionQueryResponse = ApiCustomersGetCollection200;

export type ApiCustomersGetCollectionQuery = {
    Response: ApiCustomersGetCollection200;
    QueryParams: ApiCustomersGetCollectionQueryParams;
    Errors: ApiCustomersGetCollection403;
};