/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { CustomerJsonMergePatch } from "./customer/JsonMergePatch.ts";
import type { CustomerJsonld } from "./customer/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomersIdPatchPathParams = {
    /**
     * @description Customer identifier
     * @type string
    */
    id: string;
};

/**
 * @description Customer resource updated
*/
export type ApiCustomersIdPatch200 = CustomerJsonld;

/**
 * @description Invalid input
*/
export type ApiCustomersIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiCustomersIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCustomersIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiCustomersIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Customer resource
*/
export type ApiCustomersIdPatchMutationRequest = Omit<NonNullable<CustomerJsonMergePatch>, "contacts" | "projects" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "company" | "deleted" | "externalRef">;

export type ApiCustomersIdPatchMutationResponse = ApiCustomersIdPatch200;

export type ApiCustomersIdPatchMutation = {
    Response: ApiCustomersIdPatch200;
    Request: ApiCustomersIdPatchMutationRequest;
    PathParams: ApiCustomersIdPatchPathParams;
    Errors: ApiCustomersIdPatch400 | ApiCustomersIdPatch403 | ApiCustomersIdPatch404 | ApiCustomersIdPatch422;
};