/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { CustomFieldValueJsonld } from "./customFieldValue/Jsonld.ts";

export type ApiCustomFieldValuesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    definition?: string;
    /**
     * @type array | undefined
    */
    "definition[]"?: string[];
    /**
     * @type string | undefined
    */
    target?: string;
    /**
     * @type array | undefined
    */
    "target[]"?: string[];
    /**
     * @type string | undefined
    */
    targetId?: string;
    /**
     * @type array | undefined
    */
    "targetId[]"?: string[];
};

/**
 * @description CustomFieldValue collection
*/
export type ApiCustomFieldValuesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: CustomFieldValueJsonld[];
});

export type ApiCustomFieldValuesGetCollectionQueryResponse = ApiCustomFieldValuesGetCollection200;

export type ApiCustomFieldValuesGetCollectionQuery = {
    Response: ApiCustomFieldValuesGetCollection200;
    QueryParams: ApiCustomFieldValuesGetCollectionQueryParams;
    Errors: any;
};