/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { CustomFieldDefinitionJsonMergePatch } from "./customFieldDefinition/JsonMergePatch.ts";
import type { CustomFieldDefinitionJsonld } from "./customFieldDefinition/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiCustomFieldDefinitionsIdPatchPathParams = {
    /**
     * @description CustomFieldDefinition identifier
     * @type string
    */
    id: string;
};

/**
 * @description CustomFieldDefinition resource updated
*/
export type ApiCustomFieldDefinitionsIdPatch200 = CustomFieldDefinitionJsonld;

/**
 * @description Invalid input
*/
export type ApiCustomFieldDefinitionsIdPatch400 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiCustomFieldDefinitionsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiCustomFieldDefinitionsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated CustomFieldDefinition resource
*/
export type ApiCustomFieldDefinitionsIdPatchMutationRequest = Omit<NonNullable<CustomFieldDefinitionJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "required" | "archived">;

export type ApiCustomFieldDefinitionsIdPatchMutationResponse = ApiCustomFieldDefinitionsIdPatch200;

export type ApiCustomFieldDefinitionsIdPatchMutation = {
    Response: ApiCustomFieldDefinitionsIdPatch200;
    Request: ApiCustomFieldDefinitionsIdPatchMutationRequest;
    PathParams: ApiCustomFieldDefinitionsIdPatchPathParams;
    Errors: ApiCustomFieldDefinitionsIdPatch400 | ApiCustomFieldDefinitionsIdPatch404 | ApiCustomFieldDefinitionsIdPatch422;
};