/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { DocumentJsonld } from "./document/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiDocumentsGetCollectionQueryParamsOrderpositionEnum = "asc" | "desc";

export type ApiDocumentsGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiDocumentsGetCollectionQueryParamsOrderupdatedAtEnum = "asc" | "desc";

export type ApiDocumentsGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    space?: string;
    /**
     * @type array | undefined
    */
    "space[]"?: string[];
    /**
     * @type string | undefined
    */
    parent?: string;
    /**
     * @type array | undefined
    */
    "parent[]"?: string[];
    /**
     * @type string | undefined
    */
    project?: string;
    /**
     * @type array | undefined
    */
    "project[]"?: string[];
    /**
     * @type string | undefined
    */
    task?: string;
    /**
     * @type array | undefined
    */
    "task[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isPrivate?: boolean;
    /**
     * @type boolean | undefined
    */
    isHiddenForConnectUsers?: boolean;
    /**
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[parent]"?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[space]"?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[project]"?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[task]"?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[deletedAt]"?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[position]"?: ApiDocumentsGetCollectionQueryParamsOrderpositionEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiDocumentsGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[updatedAt]"?: ApiDocumentsGetCollectionQueryParamsOrderupdatedAtEnum;
};

/**
 * @description Document collection
*/
export type ApiDocumentsGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: DocumentJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiDocumentsGetCollection403 = ErrorJsonld;

export type ApiDocumentsGetCollectionQueryResponse = ApiDocumentsGetCollection200;

export type ApiDocumentsGetCollectionQuery = {
    Response: ApiDocumentsGetCollection200;
    QueryParams: ApiDocumentsGetCollectionQueryParams;
    Errors: ApiDocumentsGetCollection403;
};