/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DocumentJsonld } from "./document/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiDocumentsIdGetPathParams = {
    /**
     * @description Document identifier
     * @type string
    */
    id: string;
};

/**
 * @description Document resource
*/
export type ApiDocumentsIdGet200 = DocumentJsonld;

/**
 * @description Forbidden
*/
export type ApiDocumentsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiDocumentsIdGet404 = ErrorJsonld;

export type ApiDocumentsIdGetQueryResponse = ApiDocumentsIdGet200;

export type ApiDocumentsIdGetQuery = {
    Response: ApiDocumentsIdGet200;
    PathParams: ApiDocumentsIdGetPathParams;
    Errors: ApiDocumentsIdGet403 | ApiDocumentsIdGet404;
};