/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DomainEventJsonld } from "./domainEvent/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiDomainEventsIdGetPathParams = {
    /**
     * @description DomainEvent identifier
     * @type string
    */
    id: string;
};

/**
 * @description DomainEvent resource
*/
export type ApiDomainEventsIdGet200 = DomainEventJsonld;

/**
 * @description Not found
*/
export type ApiDomainEventsIdGet404 = ErrorJsonld;

export type ApiDomainEventsIdGetQueryResponse = ApiDomainEventsIdGet200;

export type ApiDomainEventsIdGetQuery = {
    Response: ApiDomainEventsIdGet200;
    PathParams: ApiDomainEventsIdGetPathParams;
    Errors: ApiDomainEventsIdGet404;
};