/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiDocumentContributorsIdDeletePathParams = {
    /**
     * @description DocumentContributor identifier
     * @type string
    */
    id: string;
};

/**
 * @description DocumentContributor resource deleted
*/
export type ApiDocumentContributorsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiDocumentContributorsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiDocumentContributorsIdDelete404 = ErrorJsonld;

export type ApiDocumentContributorsIdDeleteMutationResponse = ApiDocumentContributorsIdDelete204;

export type ApiDocumentContributorsIdDeleteMutation = {
    Response: ApiDocumentContributorsIdDelete204;
    PathParams: ApiDocumentContributorsIdDeletePathParams;
    Errors: ApiDocumentContributorsIdDelete403 | ApiDocumentContributorsIdDelete404;
};