/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { DocumentContributorJsonld } from "./documentContributor/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiDocumentContributorsGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    document?: string;
    /**
     * @type array | undefined
    */
    "document[]"?: string[];
    /**
     * @type string | undefined
    */
    user?: string;
    /**
     * @type array | undefined
    */
    "user[]"?: string[];
    /**
     * @type string | undefined
    */
    access?: string;
    /**
     * @type array | undefined
    */
    "access[]"?: string[];
};

/**
 * @description DocumentContributor collection
*/
export type ApiDocumentContributorsGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: DocumentContributorJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiDocumentContributorsGetCollection403 = ErrorJsonld;

export type ApiDocumentContributorsGetCollectionQueryResponse = ApiDocumentContributorsGetCollection200;

export type ApiDocumentContributorsGetCollectionQuery = {
    Response: ApiDocumentContributorsGetCollection200;
    QueryParams: ApiDocumentContributorsGetCollectionQueryParams;
    Errors: ApiDocumentContributorsGetCollection403;
};