/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DocumentSpace } from "./DocumentSpace.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { DocumentSpaceJsonld } from "./documentSpace/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

/**
 * @description DocumentSpace resource created
*/
export type ApiDocumentSpacesPost201 = DocumentSpaceJsonld;

/**
 * @description Invalid input
*/
export type ApiDocumentSpacesPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiDocumentSpacesPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiDocumentSpacesPost422 = ConstraintViolationJsonld;

/**
 * @description The new DocumentSpace resource
*/
export type ApiDocumentSpacesPostMutationRequest = Omit<NonNullable<DocumentSpace>, "documents" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "archived" | "deleted">;

export type ApiDocumentSpacesPostMutationResponse = ApiDocumentSpacesPost201;

export type ApiDocumentSpacesPostMutation = {
    Response: ApiDocumentSpacesPost201;
    Request: ApiDocumentSpacesPostMutationRequest;
    Errors: ApiDocumentSpacesPost400 | ApiDocumentSpacesPost403 | ApiDocumentSpacesPost422;
};