/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { EntitySyncJsonMergePatch } from "./entitySync/JsonMergePatch.ts";
import type { EntitySyncJsonld } from "./entitySync/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiEntitySyncsIdPatchPathParams = {
    /**
     * @description EntitySync identifier
     * @type string
    */
    id: string;
};

/**
 * @description EntitySync resource updated
*/
export type ApiEntitySyncsIdPatch200 = EntitySyncJsonld;

/**
 * @description Invalid input
*/
export type ApiEntitySyncsIdPatch400 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiEntitySyncsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiEntitySyncsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated EntitySync resource
*/
export type ApiEntitySyncsIdPatchMutationRequest = Omit<NonNullable<EntitySyncJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version">;

export type ApiEntitySyncsIdPatchMutationResponse = ApiEntitySyncsIdPatch200;

export type ApiEntitySyncsIdPatchMutation = {
    Response: ApiEntitySyncsIdPatch200;
    Request: ApiEntitySyncsIdPatchMutationRequest;
    PathParams: ApiEntitySyncsIdPatchPathParams;
    Errors: ApiEntitySyncsIdPatch400 | ApiEntitySyncsIdPatch404 | ApiEntitySyncsIdPatch422;
};