/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { FileJsonld } from "./file/Jsonld.ts";

export type ApiFilesIdGetPathParams = {
    /**
     * @description File identifier
     * @type string
    */
    id: string;
};

/**
 * @description File resource
*/
export type ApiFilesIdGet200 = FileJsonld;

/**
 * @description Forbidden
*/
export type ApiFilesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiFilesIdGet404 = ErrorJsonld;

export type ApiFilesIdGetQueryResponse = ApiFilesIdGet200;

export type ApiFilesIdGetQuery = {
    Response: ApiFilesIdGet200;
    PathParams: ApiFilesIdGetPathParams;
    Errors: ApiFilesIdGet403 | ApiFilesIdGet404;
};