/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { FileJsonld } from "./file/Jsonld.ts";

export type ApiFilesGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiFilesGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiFilesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    target?: string;
    /**
     * @type array | undefined
    */
    "target[]"?: string[];
    /**
     * @type string | undefined
    */
    targetId?: string;
    /**
     * @type array | undefined
    */
    "targetId[]"?: string[];
    /**
     * @type string | undefined
    */
    mimeType?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    uploadedBy?: string;
    /**
     * @type array | undefined
    */
    "uploadedBy[]"?: string[];
    /**
     * @type boolean | undefined
    */
    isExternal?: boolean;
    /**
     * @type boolean | undefined
    */
    isHiddenForConnectUsers?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiFilesGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiFilesGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description File collection
*/
export type ApiFilesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: FileJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiFilesGetCollection403 = ErrorJsonld;

export type ApiFilesGetCollectionQueryResponse = ApiFilesGetCollection200;

export type ApiFilesGetCollectionQuery = {
    Response: ApiFilesGetCollection200;
    QueryParams: ApiFilesGetCollectionQueryParams;
    Errors: ApiFilesGetCollection403;
};