/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { OutboundMessageJsonMergePatch } from "./outboundMessage/JsonMergePatch.ts";
import type { OutboundMessageJsonld } from "./outboundMessage/Jsonld.ts";

export type ApiOutboundMessagesIdPatchPathParams = {
    /**
     * @description OutboundMessage identifier
     * @type string
    */
    id: string;
};

/**
 * @description OutboundMessage resource updated
*/
export type ApiOutboundMessagesIdPatch200 = OutboundMessageJsonld;

/**
 * @description Invalid input
*/
export type ApiOutboundMessagesIdPatch400 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiOutboundMessagesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiOutboundMessagesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated OutboundMessage resource
*/
export type ApiOutboundMessagesIdPatchMutationRequest = Omit<NonNullable<OutboundMessageJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version">;

export type ApiOutboundMessagesIdPatchMutationResponse = ApiOutboundMessagesIdPatch200;

export type ApiOutboundMessagesIdPatchMutation = {
    Response: ApiOutboundMessagesIdPatch200;
    Request: ApiOutboundMessagesIdPatchMutationRequest;
    PathParams: ApiOutboundMessagesIdPatchPathParams;
    Errors: ApiOutboundMessagesIdPatch400 | ApiOutboundMessagesIdPatch404 | ApiOutboundMessagesIdPatch422;
};