/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiOutboundMessagesIdDeletePathParams = {
    /**
     * @description OutboundMessage identifier
     * @type string
    */
    id: string;
};

/**
 * @description OutboundMessage resource deleted
*/
export type ApiOutboundMessagesIdDelete204 = unknown;

/**
 * @description Not found
*/
export type ApiOutboundMessagesIdDelete404 = ErrorJsonld;

export type ApiOutboundMessagesIdDeleteMutationResponse = ApiOutboundMessagesIdDelete204;

export type ApiOutboundMessagesIdDeleteMutation = {
    Response: ApiOutboundMessagesIdDelete204;
    PathParams: ApiOutboundMessagesIdDeletePathParams;
    Errors: ApiOutboundMessagesIdDelete404;
};