/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectTypeJsonMergePatch } from "./projectType/JsonMergePatch.ts";
import type { ProjectTypeJsonld } from "./projectType/Jsonld.ts";

export type ApiProjectTypesIdPatchPathParams = {
    /**
     * @description ProjectType identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectType resource updated
*/
export type ApiProjectTypesIdPatch200 = ProjectTypeJsonld;

/**
 * @description Invalid input
*/
export type ApiProjectTypesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiProjectTypesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectTypesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiProjectTypesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated ProjectType resource
*/
export type ApiProjectTypesIdPatchMutationRequest = Omit<NonNullable<ProjectTypeJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "archived" | "externalRef">;

export type ApiProjectTypesIdPatchMutationResponse = ApiProjectTypesIdPatch200;

export type ApiProjectTypesIdPatchMutation = {
    Response: ApiProjectTypesIdPatch200;
    Request: ApiProjectTypesIdPatchMutationRequest;
    PathParams: ApiProjectTypesIdPatchPathParams;
    Errors: ApiProjectTypesIdPatch400 | ApiProjectTypesIdPatch403 | ApiProjectTypesIdPatch404 | ApiProjectTypesIdPatch422;
};