/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectMemberJsonld } from "./projectMember/Jsonld.ts";

export type ApiProjectMembersIdGetPathParams = {
    /**
     * @description ProjectMember identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectMember resource
*/
export type ApiProjectMembersIdGet200 = ProjectMemberJsonld;

/**
 * @description Not found
*/
export type ApiProjectMembersIdGet404 = ErrorJsonld;

export type ApiProjectMembersIdGetQueryResponse = ApiProjectMembersIdGet200;

export type ApiProjectMembersIdGetQuery = {
    Response: ApiProjectMembersIdGet200;
    PathParams: ApiProjectMembersIdGetPathParams;
    Errors: ApiProjectMembersIdGet404;
};