/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectTypeJsonld } from "./projectType/Jsonld.ts";

export type ApiProjectTypesIdGetPathParams = {
    /**
     * @description ProjectType identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectType resource
*/
export type ApiProjectTypesIdGet200 = ProjectTypeJsonld;

/**
 * @description Forbidden
*/
export type ApiProjectTypesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectTypesIdGet404 = ErrorJsonld;

export type ApiProjectTypesIdGetQueryResponse = ApiProjectTypesIdGet200;

export type ApiProjectTypesIdGetQuery = {
    Response: ApiProjectTypesIdGet200;
    PathParams: ApiProjectTypesIdGetPathParams;
    Errors: ApiProjectTypesIdGet403 | ApiProjectTypesIdGet404;
};