/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectTemplateJsonld } from "./projectTemplate/Jsonld.ts";

export type ApiProjectTemplatesIdGetPathParams = {
    /**
     * @description ProjectTemplate identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectTemplate resource
*/
export type ApiProjectTemplatesIdGet200 = ProjectTemplateJsonld;

/**
 * @description Forbidden
*/
export type ApiProjectTemplatesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectTemplatesIdGet404 = ErrorJsonld;

export type ApiProjectTemplatesIdGetQueryResponse = ApiProjectTemplatesIdGet200;

export type ApiProjectTemplatesIdGetQuery = {
    Response: ApiProjectTemplatesIdGet200;
    PathParams: ApiProjectTemplatesIdGetPathParams;
    Errors: ApiProjectTemplatesIdGet403 | ApiProjectTemplatesIdGet404;
};