/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectMilestoneJsonMergePatch } from "./projectMilestone/JsonMergePatch.ts";
import type { ProjectMilestoneJsonld } from "./projectMilestone/Jsonld.ts";

export type ApiProjectMilestonesIdPatchPathParams = {
    /**
     * @description ProjectMilestone identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectMilestone resource updated
*/
export type ApiProjectMilestonesIdPatch200 = ProjectMilestoneJsonld;

/**
 * @description Invalid input
*/
export type ApiProjectMilestonesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiProjectMilestonesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectMilestonesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiProjectMilestonesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated ProjectMilestone resource
*/
export type ApiProjectMilestonesIdPatchMutationRequest = Omit<NonNullable<ProjectMilestoneJsonMergePatch>, "reachedOn" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "reached" | "archived" | "deleted">;

export type ApiProjectMilestonesIdPatchMutationResponse = ApiProjectMilestonesIdPatch200;

export type ApiProjectMilestonesIdPatchMutation = {
    Response: ApiProjectMilestonesIdPatch200;
    Request: ApiProjectMilestonesIdPatchMutationRequest;
    PathParams: ApiProjectMilestonesIdPatchPathParams;
    Errors: ApiProjectMilestonesIdPatch400 | ApiProjectMilestonesIdPatch403 | ApiProjectMilestonesIdPatch404 | ApiProjectMilestonesIdPatch422;
};