/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiPersonalAccessTokensIdDeletePathParams = {
    /**
     * @description PersonalAccessToken identifier
     * @type string
    */
    id: string;
};

/**
 * @description PersonalAccessToken resource deleted
*/
export type ApiPersonalAccessTokensIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiPersonalAccessTokensIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiPersonalAccessTokensIdDelete404 = ErrorJsonld;

export type ApiPersonalAccessTokensIdDeleteMutationResponse = ApiPersonalAccessTokensIdDelete204;

export type ApiPersonalAccessTokensIdDeleteMutation = {
    Response: ApiPersonalAccessTokensIdDelete204;
    PathParams: ApiPersonalAccessTokensIdDeletePathParams;
    Errors: ApiPersonalAccessTokensIdDelete403 | ApiPersonalAccessTokensIdDelete404;
};