/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ProjectStatusJsonld } from "./projectStatus/Jsonld.ts";

export type ApiProjectStatusesGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiProjectStatusesGetCollectionQueryParamsOrderpositionEnum = "asc" | "desc";

export type ApiProjectStatusesGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiProjectStatusesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type boolean | undefined
    */
    isCompleted?: boolean;
    /**
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiProjectStatusesGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[position]"?: ApiProjectStatusesGetCollectionQueryParamsOrderpositionEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiProjectStatusesGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description ProjectStatus collection
*/
export type ApiProjectStatusesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: ProjectStatusJsonld[];
});

export type ApiProjectStatusesGetCollectionQueryResponse = ApiProjectStatusesGetCollection200;

export type ApiProjectStatusesGetCollectionQuery = {
    Response: ApiProjectStatusesGetCollection200;
    QueryParams: ApiProjectStatusesGetCollectionQueryParams;
    Errors: any;
};