/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiProjectTemplatesIdDeletePathParams = {
    /**
     * @description ProjectTemplate identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectTemplate resource deleted
*/
export type ApiProjectTemplatesIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiProjectTemplatesIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectTemplatesIdDelete404 = ErrorJsonld;

export type ApiProjectTemplatesIdDeleteMutationResponse = ApiProjectTemplatesIdDelete204;

export type ApiProjectTemplatesIdDeleteMutation = {
    Response: ApiProjectTemplatesIdDelete204;
    PathParams: ApiProjectTemplatesIdDeletePathParams;
    Errors: ApiProjectTemplatesIdDelete403 | ApiProjectTemplatesIdDelete404;
};