/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { PersonalAccessTokenJsonMergePatch } from "./personalAccessToken/JsonMergePatch.ts";
import type { PersonalAccessTokenJsonld } from "./personalAccessToken/Jsonld.ts";

export type ApiPersonalAccessTokensIdPatchPathParams = {
    /**
     * @description PersonalAccessToken identifier
     * @type string
    */
    id: string;
};

/**
 * @description PersonalAccessToken resource updated
*/
export type ApiPersonalAccessTokensIdPatch200 = PersonalAccessTokenJsonld;

/**
 * @description Invalid input
*/
export type ApiPersonalAccessTokensIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiPersonalAccessTokensIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiPersonalAccessTokensIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiPersonalAccessTokensIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated PersonalAccessToken resource
*/
export type ApiPersonalAccessTokensIdPatchMutationRequest = Omit<NonNullable<PersonalAccessTokenJsonMergePatch>, "revokedAt" | "plaintextToken" | "id" | "createdAt" | "updatedAt" | "revoked">;

export type ApiPersonalAccessTokensIdPatchMutationResponse = ApiPersonalAccessTokensIdPatch200;

export type ApiPersonalAccessTokensIdPatchMutation = {
    Response: ApiPersonalAccessTokensIdPatch200;
    Request: ApiPersonalAccessTokensIdPatchMutationRequest;
    PathParams: ApiPersonalAccessTokensIdPatchPathParams;
    Errors: ApiPersonalAccessTokensIdPatch400 | ApiPersonalAccessTokensIdPatch403 | ApiPersonalAccessTokensIdPatch404 | ApiPersonalAccessTokensIdPatch422;
};