/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiProjectsIdDeletePathParams = {
    /**
     * @description Project identifier
     * @type string
    */
    id: string;
};

/**
 * @description Project resource deleted
*/
export type ApiProjectsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiProjectsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectsIdDelete404 = ErrorJsonld;

export type ApiProjectsIdDeleteMutationResponse = ApiProjectsIdDelete204;

export type ApiProjectsIdDeleteMutation = {
    Response: ApiProjectsIdDelete204;
    PathParams: ApiProjectsIdDeletePathParams;
    Errors: ApiProjectsIdDelete403 | ApiProjectsIdDelete404;
};