/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectStatusJsonMergePatch } from "./projectStatus/JsonMergePatch.ts";
import type { ProjectStatusJsonld } from "./projectStatus/Jsonld.ts";

export type ApiProjectStatusesIdPatchPathParams = {
    /**
     * @description ProjectStatus identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectStatus resource updated
*/
export type ApiProjectStatusesIdPatch200 = ProjectStatusJsonld;

/**
 * @description Invalid input
*/
export type ApiProjectStatusesIdPatch400 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectStatusesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiProjectStatusesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated ProjectStatus resource
*/
export type ApiProjectStatusesIdPatchMutationRequest = Omit<NonNullable<ProjectStatusJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "completed" | "archived" | "externalRef">;

export type ApiProjectStatusesIdPatchMutationResponse = ApiProjectStatusesIdPatch200;

export type ApiProjectStatusesIdPatchMutation = {
    Response: ApiProjectStatusesIdPatch200;
    Request: ApiProjectStatusesIdPatchMutationRequest;
    PathParams: ApiProjectStatusesIdPatchPathParams;
    Errors: ApiProjectStatusesIdPatch400 | ApiProjectStatusesIdPatch404 | ApiProjectStatusesIdPatch422;
};