/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ProjectMemberJsonld } from "./projectMember/Jsonld.ts";

export type ApiProjectMembersGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    project?: string;
    /**
     * @type array | undefined
    */
    "project[]"?: string[];
    /**
     * @type string | undefined
    */
    user?: string;
    /**
     * @type array | undefined
    */
    "user[]"?: string[];
    /**
     * @type string | undefined
    */
    role?: string;
    /**
     * @type array | undefined
    */
    "role[]"?: string[];
};

/**
 * @description ProjectMember collection
*/
export type ApiProjectMembersGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: ProjectMemberJsonld[];
});

export type ApiProjectMembersGetCollectionQueryResponse = ApiProjectMembersGetCollection200;

export type ApiProjectMembersGetCollectionQuery = {
    Response: ApiProjectMembersGetCollection200;
    QueryParams: ApiProjectMembersGetCollectionQueryParams;
    Errors: any;
};