/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PersonalAccessToken } from "./PersonalAccessToken.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { PersonalAccessTokenJsonld } from "./personalAccessToken/Jsonld.ts";

/**
 * @description PersonalAccessToken resource created
*/
export type ApiPersonalAccessTokensPost201 = PersonalAccessTokenJsonld;

/**
 * @description Invalid input
*/
export type ApiPersonalAccessTokensPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiPersonalAccessTokensPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiPersonalAccessTokensPost422 = ConstraintViolationJsonld;

/**
 * @description The new PersonalAccessToken resource
*/
export type ApiPersonalAccessTokensPostMutationRequest = Omit<NonNullable<PersonalAccessToken>, "revokedAt" | "plaintextToken" | "id" | "createdAt" | "updatedAt" | "revoked">;

export type ApiPersonalAccessTokensPostMutationResponse = ApiPersonalAccessTokensPost201;

export type ApiPersonalAccessTokensPostMutation = {
    Response: ApiPersonalAccessTokensPost201;
    Request: ApiPersonalAccessTokensPostMutationRequest;
    Errors: ApiPersonalAccessTokensPost400 | ApiPersonalAccessTokensPost403 | ApiPersonalAccessTokensPost422;
};