/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiProjectVersionsIdDeletePathParams = {
    /**
     * @description ProjectVersion identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectVersion resource deleted
*/
export type ApiProjectVersionsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiProjectVersionsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectVersionsIdDelete404 = ErrorJsonld;

export type ApiProjectVersionsIdDeleteMutationResponse = ApiProjectVersionsIdDelete204;

export type ApiProjectVersionsIdDeleteMutation = {
    Response: ApiProjectVersionsIdDelete204;
    PathParams: ApiProjectVersionsIdDeletePathParams;
    Errors: ApiProjectVersionsIdDelete403 | ApiProjectVersionsIdDelete404;
};