/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectTemplate } from "./ProjectTemplate.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectTemplateJsonld } from "./projectTemplate/Jsonld.ts";

/**
 * @description ProjectTemplate resource created
*/
export type ApiProjectTemplatesPost201 = ProjectTemplateJsonld;

/**
 * @description Invalid input
*/
export type ApiProjectTemplatesPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiProjectTemplatesPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiProjectTemplatesPost422 = ConstraintViolationJsonld;

/**
 * @description The new ProjectTemplate resource
*/
export type ApiProjectTemplatesPostMutationRequest = Omit<NonNullable<ProjectTemplate>, "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "published" | "archived" | "deleted">;

export type ApiProjectTemplatesPostMutationResponse = ApiProjectTemplatesPost201;

export type ApiProjectTemplatesPostMutation = {
    Response: ApiProjectTemplatesPost201;
    Request: ApiProjectTemplatesPostMutationRequest;
    Errors: ApiProjectTemplatesPost400 | ApiProjectTemplatesPost403 | ApiProjectTemplatesPost422;
};