/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ProjectVersionJsonld } from "./projectVersion/Jsonld.ts";

export type ApiProjectVersionsIdGetPathParams = {
    /**
     * @description ProjectVersion identifier
     * @type string
    */
    id: string;
};

/**
 * @description ProjectVersion resource
*/
export type ApiProjectVersionsIdGet200 = ProjectVersionJsonld;

/**
 * @description Forbidden
*/
export type ApiProjectVersionsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiProjectVersionsIdGet404 = ErrorJsonld;

export type ApiProjectVersionsIdGetQueryResponse = ApiProjectVersionsIdGet200;

export type ApiProjectVersionsIdGetQuery = {
    Response: ApiProjectVersionsIdGet200;
    PathParams: ApiProjectVersionsIdGetPathParams;
    Errors: ApiProjectVersionsIdGet403 | ApiProjectVersionsIdGet404;
};