/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ServiceSubscriptionJsonMergePatch } from "./serviceSubscription/JsonMergePatch.ts";
import type { ServiceSubscriptionJsonld } from "./serviceSubscription/Jsonld.ts";

export type ApiServiceSubscriptionsIdPatchPathParams = {
    /**
     * @description ServiceSubscription identifier
     * @type string
    */
    id: string;
};

/**
 * @description ServiceSubscription resource updated
*/
export type ApiServiceSubscriptionsIdPatch200 = ServiceSubscriptionJsonld;

/**
 * @description Invalid input
*/
export type ApiServiceSubscriptionsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiServiceSubscriptionsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiServiceSubscriptionsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiServiceSubscriptionsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated ServiceSubscription resource
*/
export type ApiServiceSubscriptionsIdPatchMutationRequest = Omit<NonNullable<ServiceSubscriptionJsonMergePatch>, "nextBillingOn" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "deleted" | "externalRef">;

export type ApiServiceSubscriptionsIdPatchMutationResponse = ApiServiceSubscriptionsIdPatch200;

export type ApiServiceSubscriptionsIdPatchMutation = {
    Response: ApiServiceSubscriptionsIdPatch200;
    Request: ApiServiceSubscriptionsIdPatchMutationRequest;
    PathParams: ApiServiceSubscriptionsIdPatchPathParams;
    Errors: ApiServiceSubscriptionsIdPatch400 | ApiServiceSubscriptionsIdPatch403 | ApiServiceSubscriptionsIdPatch404 | ApiServiceSubscriptionsIdPatch422;
};