/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { ServiceSubscriptionJsonld } from "./serviceSubscription/Jsonld.ts";

export type ApiServiceSubscriptionsIdGetPathParams = {
    /**
     * @description ServiceSubscription identifier
     * @type string
    */
    id: string;
};

/**
 * @description ServiceSubscription resource
*/
export type ApiServiceSubscriptionsIdGet200 = ServiceSubscriptionJsonld;

/**
 * @description Forbidden
*/
export type ApiServiceSubscriptionsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiServiceSubscriptionsIdGet404 = ErrorJsonld;

export type ApiServiceSubscriptionsIdGetQueryResponse = ApiServiceSubscriptionsIdGet200;

export type ApiServiceSubscriptionsIdGetQuery = {
    Response: ApiServiceSubscriptionsIdGet200;
    PathParams: ApiServiceSubscriptionsIdGetPathParams;
    Errors: ApiServiceSubscriptionsIdGet403 | ApiServiceSubscriptionsIdGet404;
};