/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskScheduleJsonMergePatch } from "./taskSchedule/JsonMergePatch.ts";
import type { TaskScheduleJsonld } from "./taskSchedule/Jsonld.ts";

export type ApiTaskSchedulesIdPatchPathParams = {
    /**
     * @description TaskSchedule identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskSchedule resource updated
*/
export type ApiTaskSchedulesIdPatch200 = TaskScheduleJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskSchedulesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskSchedulesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskSchedulesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskSchedulesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated TaskSchedule resource
*/
export type ApiTaskSchedulesIdPatchMutationRequest = Omit<NonNullable<TaskScheduleJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "enabled">;

export type ApiTaskSchedulesIdPatchMutationResponse = ApiTaskSchedulesIdPatch200;

export type ApiTaskSchedulesIdPatchMutation = {
    Response: ApiTaskSchedulesIdPatch200;
    Request: ApiTaskSchedulesIdPatchMutationRequest;
    PathParams: ApiTaskSchedulesIdPatchPathParams;
    Errors: ApiTaskSchedulesIdPatch400 | ApiTaskSchedulesIdPatch403 | ApiTaskSchedulesIdPatch404 | ApiTaskSchedulesIdPatch422;
};