/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskTemplateJsonld } from "./taskTemplate/Jsonld.ts";

export type ApiTaskTemplatesIdGetPathParams = {
    /**
     * @description TaskTemplate identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskTemplate resource
*/
export type ApiTaskTemplatesIdGet200 = TaskTemplateJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskTemplatesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskTemplatesIdGet404 = ErrorJsonld;

export type ApiTaskTemplatesIdGetQueryResponse = ApiTaskTemplatesIdGet200;

export type ApiTaskTemplatesIdGetQuery = {
    Response: ApiTaskTemplatesIdGet200;
    PathParams: ApiTaskTemplatesIdGetPathParams;
    Errors: ApiTaskTemplatesIdGet403 | ApiTaskTemplatesIdGet404;
};