/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskView } from "./TaskView.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskViewJsonld } from "./taskView/Jsonld.ts";

/**
 * @description TaskView resource created
*/
export type ApiTaskViewsPost201 = TaskViewJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskViewsPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskViewsPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskViewsPost422 = ConstraintViolationJsonld;

/**
 * @description The new TaskView resource
*/
export type ApiTaskViewsPostMutationRequest = Omit<NonNullable<TaskView>, "id" | "createdAt" | "updatedAt" | "version" | "shared">;

export type ApiTaskViewsPostMutationResponse = ApiTaskViewsPost201;

export type ApiTaskViewsPostMutation = {
    Response: ApiTaskViewsPost201;
    Request: ApiTaskViewsPostMutationRequest;
    Errors: ApiTaskViewsPost400 | ApiTaskViewsPost403 | ApiTaskViewsPost422;
};