/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskBundle } from "./TaskBundle.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskBundleJsonld } from "./taskBundle/Jsonld.ts";

/**
 * @description TaskBundle resource created
*/
export type ApiTaskBundlesPost201 = TaskBundleJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskBundlesPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskBundlesPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskBundlesPost422 = ConstraintViolationJsonld;

/**
 * @description The new TaskBundle resource
*/
export type ApiTaskBundlesPostMutationRequest = Omit<NonNullable<TaskBundle>, "taskTemplates" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "archived" | "deleted">;

export type ApiTaskBundlesPostMutationResponse = ApiTaskBundlesPost201;

export type ApiTaskBundlesPostMutation = {
    Response: ApiTaskBundlesPost201;
    Request: ApiTaskBundlesPostMutationRequest;
    Errors: ApiTaskBundlesPost400 | ApiTaskBundlesPost403 | ApiTaskBundlesPost422;
};