/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskTemplateJsonMergePatch } from "./taskTemplate/JsonMergePatch.ts";
import type { TaskTemplateJsonld } from "./taskTemplate/Jsonld.ts";

export type ApiTaskTemplatesIdPatchPathParams = {
    /**
     * @description TaskTemplate identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskTemplate resource updated
*/
export type ApiTaskTemplatesIdPatch200 = TaskTemplateJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskTemplatesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskTemplatesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskTemplatesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskTemplatesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated TaskTemplate resource
*/
export type ApiTaskTemplatesIdPatchMutationRequest = Omit<NonNullable<TaskTemplateJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version">;

export type ApiTaskTemplatesIdPatchMutationResponse = ApiTaskTemplatesIdPatch200;

export type ApiTaskTemplatesIdPatchMutation = {
    Response: ApiTaskTemplatesIdPatch200;
    Request: ApiTaskTemplatesIdPatchMutationRequest;
    PathParams: ApiTaskTemplatesIdPatchPathParams;
    Errors: ApiTaskTemplatesIdPatch400 | ApiTaskTemplatesIdPatch403 | ApiTaskTemplatesIdPatch404 | ApiTaskTemplatesIdPatch422;
};