/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TimeEntryJsonMergePatch } from "./timeEntry/JsonMergePatch.ts";
import type { TimeEntryJsonld } from "./timeEntry/Jsonld.ts";

export type ApiTimeEntriesIdPatchPathParams = {
    /**
     * @description TimeEntry identifier
     * @type string
    */
    id: string;
};

/**
 * @description TimeEntry resource updated
*/
export type ApiTimeEntriesIdPatch200 = TimeEntryJsonld;

/**
 * @description Invalid input
*/
export type ApiTimeEntriesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTimeEntriesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTimeEntriesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTimeEntriesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated TimeEntry resource
*/
export type ApiTimeEntriesIdPatchMutationRequest = Omit<NonNullable<TimeEntryJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "billed" | "billable" | "locked" | "running" | "externalRef">;

export type ApiTimeEntriesIdPatchMutationResponse = ApiTimeEntriesIdPatch200;

export type ApiTimeEntriesIdPatchMutation = {
    Response: ApiTimeEntriesIdPatch200;
    Request: ApiTimeEntriesIdPatchMutationRequest;
    PathParams: ApiTimeEntriesIdPatchPathParams;
    Errors: ApiTimeEntriesIdPatch400 | ApiTimeEntriesIdPatch403 | ApiTimeEntriesIdPatch404 | ApiTimeEntriesIdPatch422;
};