/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiTaskListsIdDeletePathParams = {
    /**
     * @description TaskList identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskList resource deleted
*/
export type ApiTaskListsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiTaskListsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskListsIdDelete404 = ErrorJsonld;

export type ApiTaskListsIdDeleteMutationResponse = ApiTaskListsIdDelete204;

export type ApiTaskListsIdDeleteMutation = {
    Response: ApiTaskListsIdDelete204;
    PathParams: ApiTaskListsIdDeletePathParams;
    Errors: ApiTaskListsIdDelete403 | ApiTaskListsIdDelete404;
};