/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TypeOfWorkJsonld } from "./typeOfWork/Jsonld.ts";

export type ApiTypesOfWorkGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiTypesOfWorkGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiTypesOfWorkGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @type boolean | undefined
    */
    isBillableByDefault?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiTypesOfWorkGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiTypesOfWorkGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description TypeOfWork collection
*/
export type ApiTypesOfWorkGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: TypeOfWorkJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiTypesOfWorkGetCollection403 = ErrorJsonld;

export type ApiTypesOfWorkGetCollectionQueryResponse = ApiTypesOfWorkGetCollection200;

export type ApiTypesOfWorkGetCollectionQuery = {
    Response: ApiTypesOfWorkGetCollection200;
    QueryParams: ApiTypesOfWorkGetCollectionQueryParams;
    Errors: ApiTypesOfWorkGetCollection403;
};