/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiTeamsIdDeletePathParams = {
    /**
     * @description Team identifier
     * @type string
    */
    id: string;
};

/**
 * @description Team resource deleted
*/
export type ApiTeamsIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiTeamsIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTeamsIdDelete404 = ErrorJsonld;

export type ApiTeamsIdDeleteMutationResponse = ApiTeamsIdDelete204;

export type ApiTeamsIdDeleteMutation = {
    Response: ApiTeamsIdDelete204;
    PathParams: ApiTeamsIdDeletePathParams;
    Errors: ApiTeamsIdDelete403 | ApiTeamsIdDelete404;
};