/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TrackerJsonld } from "./tracker/Jsonld.ts";

export type ApiTrackersIdGetPathParams = {
    /**
     * @description Tracker identifier
     * @type string
    */
    id: string;
};

/**
 * @description Tracker resource
*/
export type ApiTrackersIdGet200 = TrackerJsonld;

/**
 * @description Not found
*/
export type ApiTrackersIdGet404 = ErrorJsonld;

export type ApiTrackersIdGetQueryResponse = ApiTrackersIdGet200;

export type ApiTrackersIdGetQuery = {
    Response: ApiTrackersIdGet200;
    PathParams: ApiTrackersIdGetPathParams;
    Errors: ApiTrackersIdGet404;
};