/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskAssigneeJsonld } from "./taskAssignee/Jsonld.ts";

export type ApiTaskAssigneesIdGetPathParams = {
    /**
     * @description TaskAssignee identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskAssignee resource
*/
export type ApiTaskAssigneesIdGet200 = TaskAssigneeJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskAssigneesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskAssigneesIdGet404 = ErrorJsonld;

export type ApiTaskAssigneesIdGetQueryResponse = ApiTaskAssigneesIdGet200;

export type ApiTaskAssigneesIdGetQuery = {
    Response: ApiTaskAssigneesIdGet200;
    PathParams: ApiTaskAssigneesIdGetPathParams;
    Errors: ApiTaskAssigneesIdGet403 | ApiTaskAssigneesIdGet404;
};