/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Team } from "./Team.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TeamJsonld } from "./team/Jsonld.ts";

/**
 * @description Team resource created
*/
export type ApiTeamsPost201 = TeamJsonld;

/**
 * @description Invalid input
*/
export type ApiTeamsPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTeamsPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTeamsPost422 = ConstraintViolationJsonld;

/**
 * @description The new Team resource
*/
export type ApiTeamsPostMutationRequest = Omit<NonNullable<Team>, "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "archived" | "deleted">;

export type ApiTeamsPostMutationResponse = ApiTeamsPost201;

export type ApiTeamsPostMutation = {
    Response: ApiTeamsPost201;
    Request: ApiTeamsPostMutationRequest;
    Errors: ApiTeamsPost400 | ApiTeamsPost403 | ApiTeamsPost422;
};