/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { TaskStatusJsonld } from "./taskStatus/Jsonld.ts";

export type ApiTaskStatusesGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiTaskStatusesGetCollectionQueryParamsOrderpositionEnum = "asc" | "desc";

export type ApiTaskStatusesGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiTaskStatusesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type boolean | undefined
    */
    isCompleted?: boolean;
    /**
     * @type boolean | undefined
    */
    isDefault?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiTaskStatusesGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[position]"?: ApiTaskStatusesGetCollectionQueryParamsOrderpositionEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiTaskStatusesGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description TaskStatus collection
*/
export type ApiTaskStatusesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: TaskStatusJsonld[];
});

export type ApiTaskStatusesGetCollectionQueryResponse = ApiTaskStatusesGetCollection200;

export type ApiTaskStatusesGetCollectionQuery = {
    Response: ApiTaskStatusesGetCollection200;
    QueryParams: ApiTaskStatusesGetCollectionQueryParams;
    Errors: any;
};