/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiTaskSchedulesIdDeletePathParams = {
    /**
     * @description TaskSchedule identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskSchedule resource deleted
*/
export type ApiTaskSchedulesIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiTaskSchedulesIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskSchedulesIdDelete404 = ErrorJsonld;

export type ApiTaskSchedulesIdDeleteMutationResponse = ApiTaskSchedulesIdDelete204;

export type ApiTaskSchedulesIdDeleteMutation = {
    Response: ApiTaskSchedulesIdDelete204;
    PathParams: ApiTaskSchedulesIdDeletePathParams;
    Errors: ApiTaskSchedulesIdDelete403 | ApiTaskSchedulesIdDelete404;
};