/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TimeEntryJsonld } from "./timeEntry/Jsonld.ts";

export type ApiTimeEntriesIdGetPathParams = {
    /**
     * @description TimeEntry identifier
     * @type string
    */
    id: string;
};

/**
 * @description TimeEntry resource
*/
export type ApiTimeEntriesIdGet200 = TimeEntryJsonld;

/**
 * @description Forbidden
*/
export type ApiTimeEntriesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTimeEntriesIdGet404 = ErrorJsonld;

export type ApiTimeEntriesIdGetQueryResponse = ApiTimeEntriesIdGet200;

export type ApiTimeEntriesIdGetQuery = {
    Response: ApiTimeEntriesIdGet200;
    PathParams: ApiTimeEntriesIdGetPathParams;
    Errors: ApiTimeEntriesIdGet403 | ApiTimeEntriesIdGet404;
};