/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskSchedule } from "./TaskSchedule.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskScheduleJsonld } from "./taskSchedule/Jsonld.ts";

/**
 * @description TaskSchedule resource created
*/
export type ApiTaskSchedulesPost201 = TaskScheduleJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskSchedulesPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskSchedulesPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskSchedulesPost422 = ConstraintViolationJsonld;

/**
 * @description The new TaskSchedule resource
*/
export type ApiTaskSchedulesPostMutationRequest = Omit<NonNullable<TaskSchedule>, "id" | "createdAt" | "updatedAt" | "version" | "enabled">;

export type ApiTaskSchedulesPostMutationResponse = ApiTaskSchedulesPost201;

export type ApiTaskSchedulesPostMutation = {
    Response: ApiTaskSchedulesPost201;
    Request: ApiTaskSchedulesPostMutationRequest;
    Errors: ApiTaskSchedulesPost400 | ApiTaskSchedulesPost403 | ApiTaskSchedulesPost422;
};