/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskViewJsonMergePatch } from "./taskView/JsonMergePatch.ts";
import type { TaskViewJsonld } from "./taskView/Jsonld.ts";

export type ApiTaskViewsIdPatchPathParams = {
    /**
     * @description TaskView identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskView resource updated
*/
export type ApiTaskViewsIdPatch200 = TaskViewJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskViewsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskViewsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskViewsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskViewsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated TaskView resource
*/
export type ApiTaskViewsIdPatchMutationRequest = Omit<NonNullable<TaskViewJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "shared">;

export type ApiTaskViewsIdPatchMutationResponse = ApiTaskViewsIdPatch200;

export type ApiTaskViewsIdPatchMutation = {
    Response: ApiTaskViewsIdPatch200;
    Request: ApiTaskViewsIdPatchMutationRequest;
    PathParams: ApiTaskViewsIdPatchPathParams;
    Errors: ApiTaskViewsIdPatch400 | ApiTaskViewsIdPatch403 | ApiTaskViewsIdPatch404 | ApiTaskViewsIdPatch422;
};