/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiTaskListEntriesIdDeletePathParams = {
    /**
     * @description TaskListEntry identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskListEntry resource deleted
*/
export type ApiTaskListEntriesIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiTaskListEntriesIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskListEntriesIdDelete404 = ErrorJsonld;

export type ApiTaskListEntriesIdDeleteMutationResponse = ApiTaskListEntriesIdDelete204;

export type ApiTaskListEntriesIdDeleteMutation = {
    Response: ApiTaskListEntriesIdDelete204;
    PathParams: ApiTaskListEntriesIdDeletePathParams;
    Errors: ApiTaskListEntriesIdDelete403 | ApiTaskListEntriesIdDelete404;
};