/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskListJsonld } from "./taskList/Jsonld.ts";

export type ApiTaskListsGetCollectionQueryParamsOrderpositionEnum = "asc" | "desc";

export type ApiTaskListsGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiTaskListsGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiTaskListsGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    project?: string;
    /**
     * @type array | undefined
    */
    "project[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @type boolean | undefined
    */
    isHiddenForConnectUsers?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[position]"?: ApiTaskListsGetCollectionQueryParamsOrderpositionEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiTaskListsGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiTaskListsGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description TaskList collection
*/
export type ApiTaskListsGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: TaskListJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiTaskListsGetCollection403 = ErrorJsonld;

export type ApiTaskListsGetCollectionQueryResponse = ApiTaskListsGetCollection200;

export type ApiTaskListsGetCollectionQuery = {
    Response: ApiTaskListsGetCollection200;
    QueryParams: ApiTaskListsGetCollectionQueryParams;
    Errors: ApiTaskListsGetCollection403;
};