/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TimeTrackingSettingsJsonld } from "./timeTrackingSettings/Jsonld.ts";

export type ApiTimeTrackingSettingsIdGetPathParams = {
    /**
     * @description TimeTrackingSettings identifier
     * @type string
    */
    id: string;
};

/**
 * @description TimeTrackingSettings resource
*/
export type ApiTimeTrackingSettingsIdGet200 = TimeTrackingSettingsJsonld;

/**
 * @description Forbidden
*/
export type ApiTimeTrackingSettingsIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTimeTrackingSettingsIdGet404 = ErrorJsonld;

export type ApiTimeTrackingSettingsIdGetQueryResponse = ApiTimeTrackingSettingsIdGet200;

export type ApiTimeTrackingSettingsIdGetQuery = {
    Response: ApiTimeTrackingSettingsIdGet200;
    PathParams: ApiTimeTrackingSettingsIdGetPathParams;
    Errors: ApiTimeTrackingSettingsIdGet403 | ApiTimeTrackingSettingsIdGet404;
};