/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskBundleJsonld } from "./taskBundle/Jsonld.ts";

export type ApiTaskBundlesGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiTaskBundlesGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiTaskBundlesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiTaskBundlesGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiTaskBundlesGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description TaskBundle collection
*/
export type ApiTaskBundlesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: TaskBundleJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiTaskBundlesGetCollection403 = ErrorJsonld;

export type ApiTaskBundlesGetCollectionQueryResponse = ApiTaskBundlesGetCollection200;

export type ApiTaskBundlesGetCollectionQuery = {
    Response: ApiTaskBundlesGetCollection200;
    QueryParams: ApiTaskBundlesGetCollectionQueryParams;
    Errors: ApiTaskBundlesGetCollection403;
};