/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { TrackerJsonld } from "./tracker/Jsonld.ts";

export type ApiTrackersGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiTrackersGetCollectionQueryParamsOrderpositionEnum = "asc" | "desc";

export type ApiTrackersGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiTrackersGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isDefault?: boolean;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiTrackersGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[position]"?: ApiTrackersGetCollectionQueryParamsOrderpositionEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiTrackersGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description Tracker collection
*/
export type ApiTrackersGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: TrackerJsonld[];
});

export type ApiTrackersGetCollectionQueryResponse = ApiTrackersGetCollection200;

export type ApiTrackersGetCollectionQuery = {
    Response: ApiTrackersGetCollection200;
    QueryParams: ApiTrackersGetCollectionQueryParams;
    Errors: any;
};