/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Task } from "./Task.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskJsonld } from "./task/Jsonld.ts";

/**
 * @description Task resource created
*/
export type ApiTasksPost201 = TaskJsonld;

/**
 * @description Invalid input
*/
export type ApiTasksPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTasksPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTasksPost422 = ConstraintViolationJsonld;

/**
 * @description The new Task resource
*/
export type ApiTasksPostMutationRequest = Omit<NonNullable<Task>, "listEntries" | "checklistItems" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "checklistItemsCount" | "checklistItemsDoneCount" | "primaryAssignee" | "prio" | "hiddenForConnectUsers" | "deleted" | "externalRef">;

export type ApiTasksPostMutationResponse = ApiTasksPost201;

export type ApiTasksPostMutation = {
    Response: ApiTasksPost201;
    Request: ApiTasksPostMutationRequest;
    Errors: ApiTasksPost400 | ApiTasksPost403 | ApiTasksPost422;
};