/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiTimeEntriesIdDeletePathParams = {
    /**
     * @description TimeEntry identifier
     * @type string
    */
    id: string;
};

/**
 * @description TimeEntry resource deleted
*/
export type ApiTimeEntriesIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiTimeEntriesIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTimeEntriesIdDelete404 = ErrorJsonld;

export type ApiTimeEntriesIdDeleteMutationResponse = ApiTimeEntriesIdDelete204;

export type ApiTimeEntriesIdDeleteMutation = {
    Response: ApiTimeEntriesIdDelete204;
    PathParams: ApiTimeEntriesIdDeletePathParams;
    Errors: ApiTimeEntriesIdDelete403 | ApiTimeEntriesIdDelete404;
};