/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TypeOfWorkJsonMergePatch } from "./typeOfWork/JsonMergePatch.ts";
import type { TypeOfWorkJsonld } from "./typeOfWork/Jsonld.ts";

export type ApiTypesOfWorkIdPatchPathParams = {
    /**
     * @description TypeOfWork identifier
     * @type string
    */
    id: string;
};

/**
 * @description TypeOfWork resource updated
*/
export type ApiTypesOfWorkIdPatch200 = TypeOfWorkJsonld;

/**
 * @description Invalid input
*/
export type ApiTypesOfWorkIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTypesOfWorkIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTypesOfWorkIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTypesOfWorkIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated TypeOfWork resource
*/
export type ApiTypesOfWorkIdPatchMutationRequest = Omit<NonNullable<TypeOfWorkJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "billableByDefault" | "archived" | "externalRef">;

export type ApiTypesOfWorkIdPatchMutationResponse = ApiTypesOfWorkIdPatch200;

export type ApiTypesOfWorkIdPatchMutation = {
    Response: ApiTypesOfWorkIdPatch200;
    Request: ApiTypesOfWorkIdPatchMutationRequest;
    PathParams: ApiTypesOfWorkIdPatchPathParams;
    Errors: ApiTypesOfWorkIdPatch400 | ApiTypesOfWorkIdPatch403 | ApiTypesOfWorkIdPatch404 | ApiTypesOfWorkIdPatch422;
};