/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TimeEntryJsonld } from "./timeEntry/Jsonld.ts";

export type ApiTimeEntriesGetCollectionQueryParamsOrderstartsAtEnum = "asc" | "desc";

export type ApiTimeEntriesGetCollectionQueryParamsOrderendsAtEnum = "asc" | "desc";

export type ApiTimeEntriesGetCollectionQueryParamsOrderdurationMinutesEnum = "asc" | "desc";

export type ApiTimeEntriesGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiTimeEntriesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    user?: string;
    /**
     * @type array | undefined
    */
    "user[]"?: string[];
    /**
     * @type string | undefined
    */
    project?: string;
    /**
     * @type array | undefined
    */
    "project[]"?: string[];
    /**
     * @type string | undefined
    */
    task?: string;
    /**
     * @type array | undefined
    */
    "task[]"?: string[];
    /**
     * @type string | undefined
    */
    typeOfWork?: string;
    /**
     * @type array | undefined
    */
    "typeOfWork[]"?: string[];
    /**
     * @type string | undefined
    */
    note?: string;
    /**
     * @type boolean | undefined
    */
    isBillable?: boolean;
    /**
     * @type boolean | undefined
    */
    isBilled?: boolean;
    /**
     * @type boolean | undefined
    */
    isLocked?: boolean;
    /**
     * @type string | undefined
    */
    "startsAt[before]"?: string;
    /**
     * @type string | undefined
    */
    "startsAt[strictly_before]"?: string;
    /**
     * @type string | undefined
    */
    "startsAt[after]"?: string;
    /**
     * @type string | undefined
    */
    "startsAt[strictly_after]"?: string;
    /**
     * @type string | undefined
    */
    "endsAt[before]"?: string;
    /**
     * @type string | undefined
    */
    "endsAt[strictly_before]"?: string;
    /**
     * @type string | undefined
    */
    "endsAt[after]"?: string;
    /**
     * @type string | undefined
    */
    "endsAt[strictly_after]"?: string;
    /**
     * @type string | undefined
    */
    "createdAt[before]"?: string;
    /**
     * @type string | undefined
    */
    "createdAt[strictly_before]"?: string;
    /**
     * @type string | undefined
    */
    "createdAt[after]"?: string;
    /**
     * @type string | undefined
    */
    "createdAt[strictly_after]"?: string;
    /**
     * @type boolean | undefined
    */
    "exists[task]"?: boolean;
    /**
     * @type boolean | undefined
    */
    "exists[endsAt]"?: boolean;
    /**
     * @type string | undefined
    */
    "durationMinutes[between]"?: string;
    /**
     * @type string | undefined
    */
    "durationMinutes[gt]"?: string;
    /**
     * @type string | undefined
    */
    "durationMinutes[gte]"?: string;
    /**
     * @type string | undefined
    */
    "durationMinutes[lt]"?: string;
    /**
     * @type string | undefined
    */
    "durationMinutes[lte]"?: string;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[startsAt]"?: ApiTimeEntriesGetCollectionQueryParamsOrderstartsAtEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[endsAt]"?: ApiTimeEntriesGetCollectionQueryParamsOrderendsAtEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[durationMinutes]"?: ApiTimeEntriesGetCollectionQueryParamsOrderdurationMinutesEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiTimeEntriesGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description TimeEntry collection
*/
export type ApiTimeEntriesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: TimeEntryJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiTimeEntriesGetCollection403 = ErrorJsonld;

export type ApiTimeEntriesGetCollectionQueryResponse = ApiTimeEntriesGetCollection200;

export type ApiTimeEntriesGetCollectionQuery = {
    Response: ApiTimeEntriesGetCollection200;
    QueryParams: ApiTimeEntriesGetCollectionQueryParams;
    Errors: ApiTimeEntriesGetCollection403;
};