/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiTagsIdDeletePathParams = {
    /**
     * @description Tag identifier
     * @type string
    */
    id: string;
};

/**
 * @description Tag resource deleted
*/
export type ApiTagsIdDelete204 = unknown;

/**
 * @description Not found
*/
export type ApiTagsIdDelete404 = ErrorJsonld;

export type ApiTagsIdDeleteMutationResponse = ApiTagsIdDelete204;

export type ApiTagsIdDeleteMutation = {
    Response: ApiTagsIdDelete204;
    PathParams: ApiTagsIdDeletePathParams;
    Errors: ApiTagsIdDelete404;
};