/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskListEntryJsonMergePatch } from "./taskListEntry/JsonMergePatch.ts";
import type { TaskListEntryJsonld } from "./taskListEntry/Jsonld.ts";

export type ApiTaskListEntriesIdPatchPathParams = {
    /**
     * @description TaskListEntry identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskListEntry resource updated
*/
export type ApiTaskListEntriesIdPatch200 = TaskListEntryJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskListEntriesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskListEntriesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskListEntriesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskListEntriesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated TaskListEntry resource
*/
export type ApiTaskListEntriesIdPatchMutationRequest = Omit<NonNullable<TaskListEntryJsonMergePatch>, "id" | "createdAt" | "updatedAt">;

export type ApiTaskListEntriesIdPatchMutationResponse = ApiTaskListEntriesIdPatch200;

export type ApiTaskListEntriesIdPatchMutation = {
    Response: ApiTaskListEntriesIdPatch200;
    Request: ApiTaskListEntriesIdPatchMutationRequest;
    PathParams: ApiTaskListEntriesIdPatchPathParams;
    Errors: ApiTaskListEntriesIdPatch400 | ApiTaskListEntriesIdPatch403 | ApiTaskListEntriesIdPatch404 | ApiTaskListEntriesIdPatch422;
};