/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskBundleJsonld } from "./taskBundle/Jsonld.ts";

export type ApiTaskBundlesIdGetPathParams = {
    /**
     * @description TaskBundle identifier
     * @type string
    */
    id: string;
};

/**
 * @description TaskBundle resource
*/
export type ApiTaskBundlesIdGet200 = TaskBundleJsonld;

/**
 * @description Forbidden
*/
export type ApiTaskBundlesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiTaskBundlesIdGet404 = ErrorJsonld;

export type ApiTaskBundlesIdGetQueryResponse = ApiTaskBundlesIdGet200;

export type ApiTaskBundlesIdGetQuery = {
    Response: ApiTaskBundlesIdGet200;
    PathParams: ApiTaskBundlesIdGetPathParams;
    Errors: ApiTaskBundlesIdGet403 | ApiTaskBundlesIdGet404;
};