/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskStatus } from "./TaskStatus.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { TaskStatusJsonld } from "./taskStatus/Jsonld.ts";

/**
 * @description TaskStatus resource created
*/
export type ApiTaskStatusesPost201 = TaskStatusJsonld;

/**
 * @description Invalid input
*/
export type ApiTaskStatusesPost400 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiTaskStatusesPost422 = ConstraintViolationJsonld;

/**
 * @description The new TaskStatus resource
*/
export type ApiTaskStatusesPostMutationRequest = Omit<NonNullable<TaskStatus>, "id" | "createdAt" | "updatedAt" | "version" | "completed" | "default" | "externalRef">;

export type ApiTaskStatusesPostMutationResponse = ApiTaskStatusesPost201;

export type ApiTaskStatusesPostMutation = {
    Response: ApiTaskStatusesPost201;
    Request: ApiTaskStatusesPostMutationRequest;
    Errors: ApiTaskStatusesPost400 | ApiTaskStatusesPost422;
};