/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserContactInfo } from "./UserContactInfo.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { UserContactInfoJsonld } from "./userContactInfo/Jsonld.ts";

/**
 * @description UserContactInfo resource created
*/
export type ApiUserContactInfosPost201 = UserContactInfoJsonld;

/**
 * @description Invalid input
*/
export type ApiUserContactInfosPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiUserContactInfosPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiUserContactInfosPost422 = ConstraintViolationJsonld;

/**
 * @description The new UserContactInfo resource
*/
export type ApiUserContactInfosPostMutationRequest = Omit<NonNullable<UserContactInfo>, "id" | "createdAt" | "updatedAt" | "version">;

export type ApiUserContactInfosPostMutationResponse = ApiUserContactInfosPost201;

export type ApiUserContactInfosPostMutation = {
    Response: ApiUserContactInfosPost201;
    Request: ApiUserContactInfosPostMutationRequest;
    Errors: ApiUserContactInfosPost400 | ApiUserContactInfosPost403 | ApiUserContactInfosPost422;
};