/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { UserCapacityJsonMergePatch } from "./userCapacity/JsonMergePatch.ts";
import type { UserCapacityJsonld } from "./userCapacity/Jsonld.ts";

export type ApiUserCapacitiesIdPatchPathParams = {
    /**
     * @description UserCapacity identifier
     * @type string
    */
    id: string;
};

/**
 * @description UserCapacity resource updated
*/
export type ApiUserCapacitiesIdPatch200 = UserCapacityJsonld;

/**
 * @description Invalid input
*/
export type ApiUserCapacitiesIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiUserCapacitiesIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiUserCapacitiesIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiUserCapacitiesIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated UserCapacity resource
*/
export type ApiUserCapacitiesIdPatchMutationRequest = Omit<NonNullable<UserCapacityJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "weeklyMinutes">;

export type ApiUserCapacitiesIdPatchMutationResponse = ApiUserCapacitiesIdPatch200;

export type ApiUserCapacitiesIdPatchMutation = {
    Response: ApiUserCapacitiesIdPatch200;
    Request: ApiUserCapacitiesIdPatchMutationRequest;
    PathParams: ApiUserCapacitiesIdPatchPathParams;
    Errors: ApiUserCapacitiesIdPatch400 | ApiUserCapacitiesIdPatch403 | ApiUserCapacitiesIdPatch404 | ApiUserCapacitiesIdPatch422;
};