/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { UserCapacityJsonld } from "./userCapacity/Jsonld.ts";

export type ApiUserCapacitiesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    user?: string;
    /**
     * @type array | undefined
    */
    "user[]"?: string[];
};

/**
 * @description UserCapacity collection
*/
export type ApiUserCapacitiesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: UserCapacityJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiUserCapacitiesGetCollection403 = ErrorJsonld;

export type ApiUserCapacitiesGetCollectionQueryResponse = ApiUserCapacitiesGetCollection200;

export type ApiUserCapacitiesGetCollectionQuery = {
    Response: ApiUserCapacitiesGetCollection200;
    QueryParams: ApiUserCapacitiesGetCollectionQueryParams;
    Errors: ApiUserCapacitiesGetCollection403;
};