/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiUsersIdDeletePathParams = {
    /**
     * @description User identifier
     * @type string
    */
    id: string;
};

/**
 * @description User resource deleted
*/
export type ApiUsersIdDelete204 = unknown;

/**
 * @description Not found
*/
export type ApiUsersIdDelete404 = ErrorJsonld;

export type ApiUsersIdDeleteMutationResponse = ApiUsersIdDelete204;

export type ApiUsersIdDeleteMutation = {
    Response: ApiUsersIdDelete204;
    PathParams: ApiUsersIdDeletePathParams;
    Errors: ApiUsersIdDelete404;
};