/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./User.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { UserJsonld } from "./user/Jsonld.ts";

/**
 * @description User resource created
*/
export type ApiUsersPost201 = UserJsonld;

/**
 * @description Invalid input
*/
export type ApiUsersPost400 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiUsersPost422 = ConstraintViolationJsonld;

/**
 * @description The new User resource
*/
export type ApiUsersPostMutationRequest = Omit<NonNullable<User>, "workspaceMemberships" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "userIdentifier" | "fullName" | "deleted" | "externalRef">;

export type ApiUsersPostMutationResponse = ApiUsersPost201;

export type ApiUsersPostMutation = {
    Response: ApiUsersPost201;
    Request: ApiUsersPostMutationRequest;
    Errors: ApiUsersPost400 | ApiUsersPost422;
};