/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { UserContactInfoJsonMergePatch } from "./userContactInfo/JsonMergePatch.ts";
import type { UserContactInfoJsonld } from "./userContactInfo/Jsonld.ts";

export type ApiUserContactInfosIdPatchPathParams = {
    /**
     * @description UserContactInfo identifier
     * @type string
    */
    id: string;
};

/**
 * @description UserContactInfo resource updated
*/
export type ApiUserContactInfosIdPatch200 = UserContactInfoJsonld;

/**
 * @description Invalid input
*/
export type ApiUserContactInfosIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiUserContactInfosIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiUserContactInfosIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiUserContactInfosIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated UserContactInfo resource
*/
export type ApiUserContactInfosIdPatchMutationRequest = Omit<NonNullable<UserContactInfoJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version">;

export type ApiUserContactInfosIdPatchMutationResponse = ApiUserContactInfosIdPatch200;

export type ApiUserContactInfosIdPatchMutation = {
    Response: ApiUserContactInfosIdPatch200;
    Request: ApiUserContactInfosIdPatchMutationRequest;
    PathParams: ApiUserContactInfosIdPatchPathParams;
    Errors: ApiUserContactInfosIdPatch400 | ApiUserContactInfosIdPatch403 | ApiUserContactInfosIdPatch404 | ApiUserContactInfosIdPatch422;
};