/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserCapacity } from "./UserCapacity.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { UserCapacityJsonld } from "./userCapacity/Jsonld.ts";

/**
 * @description UserCapacity resource created
*/
export type ApiUserCapacitiesPost201 = UserCapacityJsonld;

/**
 * @description Invalid input
*/
export type ApiUserCapacitiesPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiUserCapacitiesPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiUserCapacitiesPost422 = ConstraintViolationJsonld;

/**
 * @description The new UserCapacity resource
*/
export type ApiUserCapacitiesPostMutationRequest = Omit<NonNullable<UserCapacity>, "id" | "createdAt" | "updatedAt" | "version" | "weeklyMinutes">;

export type ApiUserCapacitiesPostMutationResponse = ApiUserCapacitiesPost201;

export type ApiUserCapacitiesPostMutation = {
    Response: ApiUserCapacitiesPost201;
    Request: ApiUserCapacitiesPostMutationRequest;
    Errors: ApiUserCapacitiesPost400 | ApiUserCapacitiesPost403 | ApiUserCapacitiesPost422;
};