/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiWorkspacesIdDeletePathParams = {
    /**
     * @description Workspace identifier
     * @type string
    */
    id: string;
};

/**
 * @description Workspace resource deleted
*/
export type ApiWorkspacesIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiWorkspacesIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWorkspacesIdDelete404 = ErrorJsonld;

export type ApiWorkspacesIdDeleteMutationResponse = ApiWorkspacesIdDelete204;

export type ApiWorkspacesIdDeleteMutation = {
    Response: ApiWorkspacesIdDelete204;
    PathParams: ApiWorkspacesIdDeletePathParams;
    Errors: ApiWorkspacesIdDelete403 | ApiWorkspacesIdDelete404;
};