/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WorkspaceJsonld } from "./workspace/Jsonld.ts";

export type ApiWorkspacesIdGetPathParams = {
    /**
     * @description Workspace identifier
     * @type string
    */
    id: string;
};

/**
 * @description Workspace resource
*/
export type ApiWorkspacesIdGet200 = WorkspaceJsonld;

/**
 * @description Forbidden
*/
export type ApiWorkspacesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWorkspacesIdGet404 = ErrorJsonld;

export type ApiWorkspacesIdGetQueryResponse = ApiWorkspacesIdGet200;

export type ApiWorkspacesIdGetQuery = {
    Response: ApiWorkspacesIdGet200;
    PathParams: ApiWorkspacesIdGetPathParams;
    Errors: ApiWorkspacesIdGet403 | ApiWorkspacesIdGet404;
};