/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WebhookDeliveryJsonld } from "./webhookDelivery/Jsonld.ts";

export type ApiWebhookDeliveriesIdGetPathParams = {
    /**
     * @description WebhookDelivery identifier
     * @type string
    */
    id: string;
};

/**
 * @description WebhookDelivery resource
*/
export type ApiWebhookDeliveriesIdGet200 = WebhookDeliveryJsonld;

/**
 * @description Forbidden
*/
export type ApiWebhookDeliveriesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWebhookDeliveriesIdGet404 = ErrorJsonld;

export type ApiWebhookDeliveriesIdGetQueryResponse = ApiWebhookDeliveriesIdGet200;

export type ApiWebhookDeliveriesIdGetQuery = {
    Response: ApiWebhookDeliveriesIdGet200;
    PathParams: ApiWebhookDeliveriesIdGetPathParams;
    Errors: ApiWebhookDeliveriesIdGet403 | ApiWebhookDeliveriesIdGet404;
};