/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { WorkspaceMember } from "./WorkspaceMember.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WorkspaceMemberJsonld } from "./workspaceMember/Jsonld.ts";

/**
 * @description WorkspaceMember resource created
*/
export type ApiWorkspaceMembersPost201 = WorkspaceMemberJsonld;

/**
 * @description Invalid input
*/
export type ApiWorkspaceMembersPost400 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiWorkspaceMembersPost422 = ConstraintViolationJsonld;

/**
 * @description The new WorkspaceMember resource
*/
export type ApiWorkspaceMembersPostMutationRequest = Omit<NonNullable<WorkspaceMember>, "id" | "createdAt" | "updatedAt">;

export type ApiWorkspaceMembersPostMutationResponse = ApiWorkspaceMembersPost201;

export type ApiWorkspaceMembersPostMutation = {
    Response: ApiWorkspaceMembersPost201;
    Request: ApiWorkspaceMembersPostMutationRequest;
    Errors: ApiWorkspaceMembersPost400 | ApiWorkspaceMembersPost422;
};