/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WorkspaceInvitationJsonld } from "./workspaceInvitation/Jsonld.ts";

export type ApiWorkspaceInvitationsGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    status?: string;
    /**
     * @type array | undefined
    */
    "status[]"?: string[];
};

/**
 * @description WorkspaceInvitation collection
*/
export type ApiWorkspaceInvitationsGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: WorkspaceInvitationJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiWorkspaceInvitationsGetCollection403 = ErrorJsonld;

export type ApiWorkspaceInvitationsGetCollectionQueryResponse = ApiWorkspaceInvitationsGetCollection200;

export type ApiWorkspaceInvitationsGetCollectionQuery = {
    Response: ApiWorkspaceInvitationsGetCollection200;
    QueryParams: ApiWorkspaceInvitationsGetCollectionQueryParams;
    Errors: ApiWorkspaceInvitationsGetCollection403;
};