/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WatchJsonld } from "./watch/Jsonld.ts";

export type ApiWatchesIdGetPathParams = {
    /**
     * @description Watch identifier
     * @type string
    */
    id: string;
};

/**
 * @description Watch resource
*/
export type ApiWatchesIdGet200 = WatchJsonld;

/**
 * @description Forbidden
*/
export type ApiWatchesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWatchesIdGet404 = ErrorJsonld;

export type ApiWatchesIdGetQueryResponse = ApiWatchesIdGet200;

export type ApiWatchesIdGetQuery = {
    Response: ApiWatchesIdGet200;
    PathParams: ApiWatchesIdGetPathParams;
    Errors: ApiWatchesIdGet403 | ApiWatchesIdGet404;
};