/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { WorkspaceMemberJsonld } from "./workspaceMember/Jsonld.ts";

export type ApiWorkspaceMembersGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    user?: string;
    /**
     * @type array | undefined
    */
    "user[]"?: string[];
    /**
     * @type string | undefined
    */
    role?: string;
    /**
     * @type array | undefined
    */
    "role[]"?: string[];
};

/**
 * @description WorkspaceMember collection
*/
export type ApiWorkspaceMembersGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: WorkspaceMemberJsonld[];
});

export type ApiWorkspaceMembersGetCollectionQueryResponse = ApiWorkspaceMembersGetCollection200;

export type ApiWorkspaceMembersGetCollectionQuery = {
    Response: ApiWorkspaceMembersGetCollection200;
    QueryParams: ApiWorkspaceMembersGetCollectionQueryParams;
    Errors: any;
};