/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WorkspaceAbsenceJsonld } from "./workspaceAbsence/Jsonld.ts";

export type ApiWorkspaceAbsencesIdGetPathParams = {
    /**
     * @description WorkspaceAbsence identifier
     * @type string
    */
    id: string;
};

/**
 * @description WorkspaceAbsence resource
*/
export type ApiWorkspaceAbsencesIdGet200 = WorkspaceAbsenceJsonld;

/**
 * @description Forbidden
*/
export type ApiWorkspaceAbsencesIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWorkspaceAbsencesIdGet404 = ErrorJsonld;

export type ApiWorkspaceAbsencesIdGetQueryResponse = ApiWorkspaceAbsencesIdGet200;

export type ApiWorkspaceAbsencesIdGetQuery = {
    Response: ApiWorkspaceAbsencesIdGet200;
    PathParams: ApiWorkspaceAbsencesIdGetPathParams;
    Errors: ApiWorkspaceAbsencesIdGet403 | ApiWorkspaceAbsencesIdGet404;
};