/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WorkflowJsonMergePatch } from "./workflow/JsonMergePatch.ts";
import type { WorkflowJsonld } from "./workflow/Jsonld.ts";

export type ApiWorkflowsIdPatchPathParams = {
    /**
     * @description Workflow identifier
     * @type string
    */
    id: string;
};

/**
 * @description Workflow resource updated
*/
export type ApiWorkflowsIdPatch200 = WorkflowJsonld;

/**
 * @description Invalid input
*/
export type ApiWorkflowsIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiWorkflowsIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWorkflowsIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiWorkflowsIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Workflow resource
*/
export type ApiWorkflowsIdPatchMutationRequest = Omit<NonNullable<WorkflowJsonMergePatch>, "automations" | "id" | "createdAt" | "updatedAt" | "deletedAt" | "version" | "enabled" | "archived" | "deleted">;

export type ApiWorkflowsIdPatchMutationResponse = ApiWorkflowsIdPatch200;

export type ApiWorkflowsIdPatchMutation = {
    Response: ApiWorkflowsIdPatch200;
    Request: ApiWorkflowsIdPatchMutationRequest;
    PathParams: ApiWorkflowsIdPatchPathParams;
    Errors: ApiWorkflowsIdPatch400 | ApiWorkflowsIdPatch403 | ApiWorkflowsIdPatch404 | ApiWorkflowsIdPatch422;
};