/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Webhook } from "./Webhook.ts";
import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WebhookJsonld } from "./webhook/Jsonld.ts";

/**
 * @description Webhook resource created
*/
export type ApiWebhooksPost201 = WebhookJsonld;

/**
 * @description Invalid input
*/
export type ApiWebhooksPost400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiWebhooksPost403 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiWebhooksPost422 = ConstraintViolationJsonld;

/**
 * @description The new Webhook resource
*/
export type ApiWebhooksPostMutationRequest = Omit<NonNullable<Webhook>, "id" | "createdAt" | "updatedAt" | "version" | "active">;

export type ApiWebhooksPostMutationResponse = ApiWebhooksPost201;

export type ApiWebhooksPostMutation = {
    Response: ApiWebhooksPost201;
    Request: ApiWebhooksPostMutationRequest;
    Errors: ApiWebhooksPost400 | ApiWebhooksPost403 | ApiWebhooksPost422;
};