/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WebhookJsonld } from "./webhook/Jsonld.ts";

export type ApiWebhooksIdGetPathParams = {
    /**
     * @description Webhook identifier
     * @type string
    */
    id: string;
};

/**
 * @description Webhook resource
*/
export type ApiWebhooksIdGet200 = WebhookJsonld;

/**
 * @description Forbidden
*/
export type ApiWebhooksIdGet403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWebhooksIdGet404 = ErrorJsonld;

export type ApiWebhooksIdGetQueryResponse = ApiWebhooksIdGet200;

export type ApiWebhooksIdGetQuery = {
    Response: ApiWebhooksIdGet200;
    PathParams: ApiWebhooksIdGetPathParams;
    Errors: ApiWebhooksIdGet403 | ApiWebhooksIdGet404;
};