/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WorkspaceJsonld } from "./workspace/Jsonld.ts";

export type ApiWorkspacesGetCollectionQueryParamsOrdernameEnum = "asc" | "desc";

export type ApiWorkspacesGetCollectionQueryParamsOrdercreatedAtEnum = "asc" | "desc";

export type ApiWorkspacesGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    slug?: string;
    /**
     * @type array | undefined
    */
    "slug[]"?: string[];
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[name]"?: ApiWorkspacesGetCollectionQueryParamsOrdernameEnum;
    /**
     * @default "asc"
     * @type string | undefined
    */
    "order[createdAt]"?: ApiWorkspacesGetCollectionQueryParamsOrdercreatedAtEnum;
};

/**
 * @description Workspace collection
*/
export type ApiWorkspacesGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: WorkspaceJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiWorkspacesGetCollection403 = ErrorJsonld;

export type ApiWorkspacesGetCollectionQueryResponse = ApiWorkspacesGetCollection200;

export type ApiWorkspacesGetCollectionQuery = {
    Response: ApiWorkspacesGetCollection200;
    QueryParams: ApiWorkspacesGetCollectionQueryParams;
    Errors: ApiWorkspacesGetCollection403;
};