/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConstraintViolationJsonld } from "./constraintViolation/Jsonld.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WebhookJsonMergePatch } from "./webhook/JsonMergePatch.ts";
import type { WebhookJsonld } from "./webhook/Jsonld.ts";

export type ApiWebhooksIdPatchPathParams = {
    /**
     * @description Webhook identifier
     * @type string
    */
    id: string;
};

/**
 * @description Webhook resource updated
*/
export type ApiWebhooksIdPatch200 = WebhookJsonld;

/**
 * @description Invalid input
*/
export type ApiWebhooksIdPatch400 = ErrorJsonld;

/**
 * @description Forbidden
*/
export type ApiWebhooksIdPatch403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWebhooksIdPatch404 = ErrorJsonld;

/**
 * @description An error occurred
*/
export type ApiWebhooksIdPatch422 = ConstraintViolationJsonld;

/**
 * @description The updated Webhook resource
*/
export type ApiWebhooksIdPatchMutationRequest = Omit<NonNullable<WebhookJsonMergePatch>, "id" | "createdAt" | "updatedAt" | "version" | "active">;

export type ApiWebhooksIdPatchMutationResponse = ApiWebhooksIdPatch200;

export type ApiWebhooksIdPatchMutation = {
    Response: ApiWebhooksIdPatch200;
    Request: ApiWebhooksIdPatchMutationRequest;
    PathParams: ApiWebhooksIdPatchPathParams;
    Errors: ApiWebhooksIdPatch400 | ApiWebhooksIdPatch403 | ApiWebhooksIdPatch404 | ApiWebhooksIdPatch422;
};