/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraCollectionBaseSchema } from "./HydraCollectionBaseSchema.ts";
import type { ErrorJsonld } from "./error/Jsonld.ts";
import type { WebhookJsonld } from "./webhook/Jsonld.ts";

export type ApiWebhooksGetCollectionQueryParams = {
    /**
     * @description The collection page number
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items per page
     * @minLength 0
     * @maxLength 200
     * @default 30
     * @type integer | undefined
    */
    itemsPerPage?: number;
    /**
     * @type string | undefined
    */
    workspace?: string;
    /**
     * @type array | undefined
    */
    "workspace[]"?: string[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
};

/**
 * @description Webhook collection
*/
export type ApiWebhooksGetCollection200 = (HydraCollectionBaseSchema & {
    /**
     * @type array
    */
    member: WebhookJsonld[];
});

/**
 * @description Forbidden
*/
export type ApiWebhooksGetCollection403 = ErrorJsonld;

export type ApiWebhooksGetCollectionQueryResponse = ApiWebhooksGetCollection200;

export type ApiWebhooksGetCollectionQuery = {
    Response: ApiWebhooksGetCollection200;
    QueryParams: ApiWebhooksGetCollectionQueryParams;
    Errors: ApiWebhooksGetCollection403;
};