/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorJsonld } from "./error/Jsonld.ts";

export type ApiWebhooksIdDeletePathParams = {
    /**
     * @description Webhook identifier
     * @type string
    */
    id: string;
};

/**
 * @description Webhook resource deleted
*/
export type ApiWebhooksIdDelete204 = unknown;

/**
 * @description Forbidden
*/
export type ApiWebhooksIdDelete403 = ErrorJsonld;

/**
 * @description Not found
*/
export type ApiWebhooksIdDelete404 = ErrorJsonld;

export type ApiWebhooksIdDeleteMutationResponse = ApiWebhooksIdDelete204;

export type ApiWebhooksIdDeleteMutation = {
    Response: ApiWebhooksIdDelete204;
    PathParams: ApiWebhooksIdDeletePathParams;
    Errors: ApiWebhooksIdDelete403 | ApiWebhooksIdDelete404;
};