/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description User token created
*/
export type LoginCheckPost200 = {
    /**
     * @type string
    */
    readonly token: string;
};

/**
 * @description The login data
*/
export type LoginCheckPostMutationRequest = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    password: string;
};

export type LoginCheckPostMutationResponse = LoginCheckPost200;

export type LoginCheckPostMutation = {
    Response: LoginCheckPost200;
    Request: LoginCheckPostMutationRequest;
    Errors: any;
};