/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProjectStatus = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default "#6366f1"
     * @type string | undefined
    */
    color?: string;
    /**
     * @default 0
     * @type integer | undefined
    */
    position?: number;
    /**
     * @default false
     * @type boolean | undefined
    */
    isCompleted?: boolean;
    /**
     * @default false
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type string,null
    */
    externalSource?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly completed?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly archived?: boolean;
    /**
     * @type string,null
    */
    readonly externalRef?: string | null;
};