/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProjectMemberRoleEnum = "manager" | "contributor" | "viewer";

export type ProjectMember = {
    /**
     * @type string | undefined, iri-reference
    */
    project?: string;
    /**
     * @type string | undefined, iri-reference
    */
    user?: string;
    /**
     * @default "contributor"
     * @type string | undefined
    */
    role?: ProjectMemberRoleEnum;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
};