/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TaskAssigneePrincipalTypeEnum = "user" | "team";

/**
 * @description Polymorphic Task → (User|Team) assignment.\n\nReplaces the old `task_assignees(task_id, user_id)` ManyToMany join.\nEach row is one assignment of a Principal (a User OR a Team) to a\nTask. The Task\'s \"effective assignees\" — what shows up in the avatar\nstack and notifications — is the union of:\n  - direct user assignments (principalType=user)\n  - the members of every assigned team (principalType=team, expanded\n    via team_members)\n\nWorkspace is denormalised from the parent task at persist-time so\nfilters and voters don\'t need a join.\n\nThe principal_type + principal_id pattern intentionally avoids\nDoctrine STI — see AssigneePrincipalType.
*/
export type TaskAssignee = {
    /**
     * @type string | undefined, iri-reference
    */
    task?: string;
    /**
     * @type string | undefined
    */
    principalType?: TaskAssigneePrincipalTypeEnum;
    /**
     * @type string | undefined, uuid
    */
    principalId?: string;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @description Convenience getter for the API output — returns the IRI of the principal.
     * @type string | undefined
    */
    readonly principalIri?: string;
};