/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type WebhookDeliveryStatusEnum = "pending" | "success" | "failure";

/**
 * @description Single attempt to deliver one DomainEvent to one Webhook. One log row per\n(webhook, event, attempt) — retries get their own row so the timeline is\ncomplete.\n\nRead-only via the API (operators inspect the log; retries happen on the\nMessenger transport\'s own schedule, not via REST).
*/
export type WebhookDelivery = {
    /**
     * @type string | undefined, iri-reference
    */
    webhook?: string;
    /**
     * @description Snapshot of the source DomainEvent.aggregateId — reference only, no FK to domain_events.
     * @type string,null, uuid
    */
    eventId?: string | null;
    /**
     * @type string | undefined
    */
    eventName?: string;
    /**
     * @default "pending"
     * @type string | undefined
    */
    status?: WebhookDeliveryStatusEnum;
    /**
     * @type integer,null
    */
    httpStatus?: number | null;
    /**
     * @type string,null
    */
    responseBody?: string | null;
    /**
     * @type string,null
    */
    errorMessage?: string | null;
    /**
     * @default 1
     * @type integer | undefined
    */
    attempt?: number;
    /**
     * @type integer,null
    */
    durationMs?: number | null;
    /**
     * @type string,null, date-time
    */
    attemptedAt?: string | null;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
};