/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RolePermissionOverrideHtmlRoleEnum = "owner" | "admin" | "member" | "guest";

export type RolePermissionOverrideHtmlCapabilityEnum = "workspace.manage_settings" | "workspace.manage_members" | "workspace.manage_billing" | "project.create" | "project.update" | "project.archive" | "project.delete" | "project.manage_members" | "task.create" | "task.update" | "task.assign" | "task.delete_own" | "task.delete_others" | "time_entry.create" | "time_entry.update_own" | "time_entry.update_others" | "time_entry.delete_own" | "time_entry.delete_others" | "file.upload" | "file.delete_others" | "comment.create" | "comment.delete_others" | "document.create" | "document.delete_others" | "automation.manage" | "webhook.manage" | "reports.view";

/**
 * @description Workspace-scoped override of the DefaultPermissions matrix.\n\nEach row says: in workspace X, role R has capability C with value\n`isGranted` (which can be true OR false — overrides can both grant AND\nrevoke). The {@see PermissionResolver} consults overrides first and only\nfalls back to {@see \\App\\Security\\DefaultPermissions} when no row matches.\n\nThe unique constraint guarantees one override per (workspace, role,\ncapability) tuple — re-asserting the same triple updates the existing row\nrather than stacking conflicting policies.\n\nOwner is intentionally excluded as a target role here (validation): no\noverride should be able to lock the owner out of their own workspace.
*/
export type RolePermissionOverrideHtml = {
    /**
     * @type string | undefined
    */
    role?: RolePermissionOverrideHtmlRoleEnum;
    /**
     * @type string | undefined
    */
    capability?: RolePermissionOverrideHtmlCapabilityEnum;
    /**
     * @default true
     * @type boolean | undefined
    */
    isGranted?: boolean;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly granted?: boolean;
};