/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CustomFieldOptionHtml = {
    /**
     * @type string | undefined, iri-reference
    */
    definition?: string;
    /**
     * @type string | undefined
    */
    value?: string;
    /**
     * @type string,null
    */
    color?: string | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    position?: number;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
};