/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Subscription that mirrors selected DomainEvents to an external HTTP endpoint.\n\nEach delivery is signed with HMAC-SHA256 over the request body, using `secret`\nas the key; consumers verify by recomputing the digest and comparing it to the\n`X-Worktide-Signature: sha256=…` header.\n\nEvent subscription matches by name:\n  - `[\"*\"]`                  — every event\n  - `[\"task.*\"]`             — every event whose name starts with \"task.\"\n  - `[\"task.created\"]`       — exact name only\n\nThe `secret` is write-only via the API (returned obfuscated on reads) so it\nnever leaks back to clients after creation. `failureCount` and\n`lastTriggeredAt` are server-managed; clients cannot patch them.\n\nAfter {@see self::FAILURE_THRESHOLD} consecutive non-2xx deliveries the\nwebhook auto-deactivates — the operator must inspect the deliveries log and\nre-enable it with a fresh PATCH.
 */
export const webhookHtmlSchema = z.object({
    "name": z.optional(z.string().default("")),
"url": z.optional(z.string()),
"eventTypes": z.optional(z.array(z.string()).describe("Event-name patterns this webhook subscribes to.")),
"isActive": z.optional(z.boolean().default(true)),
"failureCount": z.optional(z.int().default(0)),
"lastTriggeredAt": z.iso.datetime().nullish(),
"lastSucceededAt": z.iso.datetime().nullish(),
"lastFailedAt": z.iso.datetime().nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"active": z.optional(z.boolean())
    }).describe("Subscription that mirrors selected DomainEvents to an external HTTP endpoint.\n\nEach delivery is signed with HMAC-SHA256 over the request body, using `secret`\nas the key; consumers verify by recomputing the digest and comparing it to the\n`X-Worktide-Signature: sha256=…` header.\n\nEvent subscription matches by name:\n  - `[\"*\"]`                  — every event\n  - `[\"task.*\"]`             — every event whose name starts with \"task.\"\n  - `[\"task.created\"]`       — exact name only\n\nThe `secret` is write-only via the API (returned obfuscated on reads) so it\nnever leaks back to clients after creation. `failureCount` and\n`lastTriggeredAt` are server-managed; clients cannot patch them.\n\nAfter {@see self::FAILURE_THRESHOLD} consecutive non-2xx deliveries the\nwebhook auto-deactivates — the operator must inspect the deliveries log and\nre-enable it with a fresh PATCH.")