/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const taskHtmlSchema = z.object({
    "project": z.string().describe("Tasks without a project (\"private tasks\") are personal todos that belong\nto a workspace but don't show up in any project board. They follow the\nsame auth rules — owner-only visibility — via the Voter, and let users\ntrack miscellaneous work alongside structured project tasks.").nullish(),
"identifier": z.optional(z.string()),
"title": z.optional(z.string()),
"description": z.string().nullish(),
"status": z.optional(z.string()),
"tracker": z.string().describe("Issue-type classification (Bug / Feature / Story / Support / …).").nullish(),
"priority": z.optional(z.enum(["low", "normal", "high", "urgent"]).default("normal")),
"assignedPrincipals": z.optional(z.array(z.string()).describe("Polymorphic assignment principals — a mix of Users and Teams.")),
"createdBy": z.string().nullish(),
"dueOn": z.iso.datetime().nullish(),
"startOn": z.iso.datetime().describe("Planned start (Soll). Used by Gantt and the AI auto-scheduler in\nPhase D — separate from `startedOn` (Ist, set when work begins).").nullish(),
"startedOn": z.iso.datetime().nullish(),
"estimatedMinutes": z.int().nullish(),
"correlationId": z.uuid().describe("Idempotency anchor for inbound channels (CSV-Import, Mail-Inbound,\nWebhook-Replay, AI-Breakdown). Indexed but not unique — multiple\nchannels can collide deliberately on the same external reference.").nullish(),
"createdVia": z.optional(z.enum(["created", "import", "email", "automation", "api", "recurring", "template"]).default("created").describe("How this task entered Worktide. Default is direct creation through\nthe UI; importers, mail handlers, and automations stamp their own\nvalue so the activity feed and reports can attribute volume.")),
"parent": z.string().nullish(),
"position": z.optional(z.int().default(0)),
"isPrio": z.optional(z.boolean().default(false)),
"isHiddenForConnectUsers": z.optional(z.boolean().default(false).describe("Internal task that must not be visible to external (cross-workspace)\nproject members. Same semantics as Comment.isHiddenForConnectUsers.")),
"closedOn": z.iso.datetime().nullish(),
"closedBy": z.string().nullish(),
"tags": z.optional(z.array(z.string())),
"listEntries": z.optional(z.array(z.string())),
"checklistItems": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"checklistItemsCount": z.optional(z.int().describe("Number of checklist items on this task (for awork-style task summaries).")),
"checklistItemsDoneCount": z.optional(z.int().describe("Number of checked-off checklist items.")),
"assignees": z.optional(z.array(z.string()).describe("Backwards-compatible flat list of *directly* assigned user IRIs.")),
"assignedTeams": z.optional(z.array(z.string()).describe("Team IRIs directly assigned to this task. The SPA may render\nthese as a separate \"team chip\" group or expand via a parallel\n/v1/teams fetch.")),
"prio": z.optional(z.boolean()),
"hiddenForConnectUsers": z.optional(z.boolean()),
"deleted": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    })