/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TaskHtmlPriorityEnum = "low" | "normal" | "high" | "urgent";

export type TaskHtml = {
    /**
     * @description Tasks without a project (\"private tasks\") are personal todos that belong\nto a workspace but don\'t show up in any project board. They follow the\nsame auth rules — owner-only visibility — via the Voter, and let users\ntrack miscellaneous work alongside structured project tasks.
     * @type string,null, iri-reference
    */
    project?: string | null;
    /**
     * @type string | undefined
    */
    identifier?: string;
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string,null
    */
    description?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    status?: string;
    /**
     * @default "normal"
     * @type string | undefined
    */
    priority?: TaskHtmlPriorityEnum;
    /**
     * @type array | undefined
    */
    assignees?: string[];
    /**
     * @type string,null, iri-reference
    */
    createdBy?: string | null;
    /**
     * @type string,null, date-time
    */
    dueOn?: string | null;
    /**
     * @type string,null, date-time
    */
    startedOn?: string | null;
    /**
     * @type integer,null
    */
    estimatedMinutes?: number | null;
    /**
     * @type string,null, iri-reference
    */
    parent?: string | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    position?: number;
    /**
     * @default false
     * @type boolean | undefined
    */
    isPrio?: boolean;
    /**
     * @description Internal task that must not be visible to external (cross-workspace)\nproject members. Same semantics as Comment.isHiddenForConnectUsers.
     * @default false
     * @type boolean | undefined
    */
    isHiddenForConnectUsers?: boolean;
    /**
     * @type string,null, date-time
    */
    closedOn?: string | null;
    /**
     * @type string,null, iri-reference
    */
    closedBy?: string | null;
    /**
     * @type array | undefined
    */
    tags?: string[];
    /**
     * @type array | undefined
    */
    readonly listEntries?: string[];
    /**
     * @type array | undefined
    */
    readonly checklistItems?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type string,null
    */
    externalSource?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @description Number of checklist items on this task (for awork-style task summaries).
     * @type integer | undefined
    */
    readonly checklistItemsCount?: number;
    /**
     * @description Number of checked-off checklist items.
     * @type integer | undefined
    */
    readonly checklistItemsDoneCount?: number;
    /**
     * @description Convenience for the common single-assignee case.
     * @type string,null, iri-reference
    */
    readonly primaryAssignee?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly prio?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly hiddenForConnectUsers?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
    /**
     * @type string,null
    */
    readonly externalRef?: string | null;
};