/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type WorkspaceMemberJsonMergePatchRoleEnum = "owner" | "admin" | "member" | "guest";

export type WorkspaceMemberJsonMergePatch = {
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @type string | undefined, iri-reference
    */
    user?: string;
    /**
     * @default "member"
     * @type string | undefined
    */
    role?: WorkspaceMemberJsonMergePatchRoleEnum;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
};