/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { absenceRegionJsonMergePatchSchema } from "./absenceRegion/jsonMergePatchSchema.ts";
import { absenceRegionJsonldSchema } from "./absenceRegion/jsonldSchema.ts";
import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAbsenceRegionsIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("AbsenceRegion identifier")
    })

/**
 * @description AbsenceRegion resource updated
 */
export const apiAbsenceRegionsIdPatch200Schema = z.lazy(() => absenceRegionJsonldSchema).describe("Regional public-holiday calendar (e.g. \"Bayern\", \"France\"). Users assigned\nto a region auto-inherit absences from imported public holidays.\n\nSchema only — public-holiday ETL is a future task. countryCode is ISO 3166-1\nalpha-2, location is a free-form sub-region name.")

/**
 * @description Invalid input
 */
export const apiAbsenceRegionsIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiAbsenceRegionsIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAbsenceRegionsIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiAbsenceRegionsIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated AbsenceRegion resource
 */
export const apiAbsenceRegionsIdPatchMutationRequestSchema = z.lazy(() => absenceRegionJsonMergePatchSchema).describe("Regional public-holiday calendar (e.g. \"Bayern\", \"France\"). Users assigned\nto a region auto-inherit absences from imported public holidays.\n\nSchema only — public-holiday ETL is a future task. countryCode is ISO 3166-1\nalpha-2, location is a free-form sub-region name.").unwrap().omit({ 'users': true,'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiAbsenceRegionsIdPatchMutationResponseSchema = z.lazy(() => apiAbsenceRegionsIdPatch200Schema)