/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { autopilotJsonldSchema } from "./autopilot/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAutopilotsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Autopilot identifier")
    })

/**
 * @description Autopilot resource
 */
export const apiAutopilotsIdGet200Schema = z.lazy(() => autopilotJsonldSchema).describe("Per-Project alert rules — \"warn the project lead when budget > 80%\n * consumed\", \"ping when a task is overdue by more than 3 days\".\n\nOne Autopilot per project (UNIQUE on project_id). Rules are stored as\nJSON so adding new alert kinds doesn't require schema migrations; the\nAutopilotEvaluator service knows how to interpret each kind.\n\nAvailable alert kinds (B8 MVP):\n  - \"budget_threshold\"     { percent: 80 }\n  - \"overdue_tasks\"        { gracePeriodDays: 0 }\n  - \"due_soon\"             { withinDays: 3 }\n\nEach rule that triggers writes a DomainEvent named\n\"autopilot.{kind}.triggered\" carrying the projectId + payload, plus\nstamps lastTriggeredAt on the Autopilot. Consumers (notifications,\nwebhooks once B10 lands) subscribe to these events.")

/**
 * @description Forbidden
 */
export const apiAutopilotsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAutopilotsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAutopilotsIdGetQueryResponseSchema = z.lazy(() => apiAutopilotsIdGet200Schema)