/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { absenceJsonMergePatchSchema } from "./absence/jsonMergePatchSchema.ts";
import { absenceJsonldSchema } from "./absence/jsonldSchema.ts";
import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAbsencesIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("Absence identifier")
    })

/**
 * @description Absence resource updated
 */
export const apiAbsencesIdPatch200Schema = z.lazy(() => absenceJsonldSchema).describe("Personal absence — vacation, sick leave, etc. Linked to a user; counts\nagainst their UserCapacity when computing availability.\n\nBeyond awork: we have a `type` enum (vacation / sick / personal /\nholiday / other) for filtering and reporting. awork doesn't model this,\nso its UI relies on `description` heuristics.\n\nHalf-day flags follow awork's semantics: if both start and end are the\nsame date, only one half-day flag matters.")

/**
 * @description Invalid input
 */
export const apiAbsencesIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiAbsencesIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAbsencesIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiAbsencesIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated Absence resource
 */
export const apiAbsencesIdPatchMutationRequestSchema = z.lazy(() => absenceJsonMergePatchSchema).describe("Personal absence — vacation, sick leave, etc. Linked to a user; counts\nagainst their UserCapacity when computing availability.\n\nBeyond awork: we have a `type` enum (vacation / sick / personal /\nholiday / other) for filtering and reporting. awork doesn't model this,\nso its UI relies on `description` heuristics.\n\nHalf-day flags follow awork's semantics: if both start and end are the\nsame date, only one half-day flag matters.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'halfDayOnStart': true,'halfDayOnEnd': true,'readOnly': true,'deleted': true,'externalRef': true })

export const apiAbsencesIdPatchMutationResponseSchema = z.lazy(() => apiAbsencesIdPatch200Schema)