/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { automationJsonldSchema } from "./automation/jsonldSchema.ts";
import { automationSchema } from "./automationSchema.ts";
import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

/**
 * @description Automation resource created
 */
export const apiAutomationsPost201Schema = z.lazy(() => automationJsonldSchema).describe("\"When trigger X fires, run actions Y\" — the building block of a Workflow.\n\ntriggerConfig is a JSON object whose shape depends on triggerType:\n  task.status_changed   → { toStatusId?: uuid, fromStatusId?: uuid }\n  task.assignee_changed → { newAssigneeId?: uuid }\n  task.created          → (none, fires for every new task in the workspace)\n  etc.\n\nAutomationDispatcher (the doctrine listener) reads triggerConfig to filter\nwhich raw domain events should actually trigger this automation.")

/**
 * @description Invalid input
 */
export const apiAutomationsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiAutomationsPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiAutomationsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Automation resource
 */
export const apiAutomationsPostMutationRequestSchema = z.lazy(() => automationSchema).describe("\"When trigger X fires, run actions Y\" — the building block of a Workflow.\n\ntriggerConfig is a JSON object whose shape depends on triggerType:\n  task.status_changed   → { toStatusId?: uuid, fromStatusId?: uuid }\n  task.assignee_changed → { newAssigneeId?: uuid }\n  task.created          → (none, fires for every new task in the workspace)\n  etc.\n\nAutomationDispatcher (the doctrine listener) reads triggerConfig to filter\nwhich raw domain events should actually trigger this automation.").unwrap().omit({ 'actions': true,'id': true,'createdAt': true,'updatedAt': true,'version': true,'enabled': true })

export const apiAutomationsPostMutationResponseSchema = z.lazy(() => apiAutomationsPost201Schema)