/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { automationJsonldSchema } from "./automation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAutomationsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Automation identifier")
    })

/**
 * @description Automation resource
 */
export const apiAutomationsIdGet200Schema = z.lazy(() => automationJsonldSchema).describe("\"When trigger X fires, run actions Y\" — the building block of a Workflow.\n\ntriggerConfig is a JSON object whose shape depends on triggerType:\n  task.status_changed   → { toStatusId?: uuid, fromStatusId?: uuid }\n  task.assignee_changed → { newAssigneeId?: uuid }\n  task.created          → (none, fires for every new task in the workspace)\n  etc.\n\nAutomationDispatcher (the doctrine listener) reads triggerConfig to filter\nwhich raw domain events should actually trigger this automation.")

/**
 * @description Forbidden
 */
export const apiAutomationsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAutomationsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAutomationsIdGetQueryResponseSchema = z.lazy(() => apiAutomationsIdGet200Schema)