/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { absenceRegionJsonldSchema } from "./absenceRegion/jsonldSchema.ts";
import { absenceRegionSchema } from "./absenceRegionSchema.ts";
import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

/**
 * @description AbsenceRegion resource created
 */
export const apiAbsenceRegionsPost201Schema = z.lazy(() => absenceRegionJsonldSchema).describe("Regional public-holiday calendar (e.g. \"Bayern\", \"France\"). Users assigned\nto a region auto-inherit absences from imported public holidays.\n\nSchema only — public-holiday ETL is a future task. countryCode is ISO 3166-1\nalpha-2, location is a free-form sub-region name.")

/**
 * @description Invalid input
 */
export const apiAbsenceRegionsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiAbsenceRegionsPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiAbsenceRegionsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new AbsenceRegion resource
 */
export const apiAbsenceRegionsPostMutationRequestSchema = z.lazy(() => absenceRegionSchema).describe("Regional public-holiday calendar (e.g. \"Bayern\", \"France\"). Users assigned\nto a region auto-inherit absences from imported public holidays.\n\nSchema only — public-holiday ETL is a future task. countryCode is ISO 3166-1\nalpha-2, location is a free-form sub-region name.").unwrap().omit({ 'users': true,'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiAbsenceRegionsPostMutationResponseSchema = z.lazy(() => apiAbsenceRegionsPost201Schema)