/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAutopilotsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Autopilot identifier")
    })

/**
 * @description Autopilot resource deleted
 */
export const apiAutopilotsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiAutopilotsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAutopilotsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAutopilotsIdDeleteMutationResponseSchema = z.lazy(() => apiAutopilotsIdDelete204Schema)