/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { automationActionJsonldSchema } from "./automationAction/jsonldSchema.ts";
import { automationActionSchema } from "./automationActionSchema.ts";
import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

/**
 * @description AutomationAction resource created
 */
export const apiAutomationActionsPost201Schema = z.lazy(() => automationActionJsonldSchema).describe("One step the Automation runs when triggered. Multiple Actions per\nAutomation run in `position` order; if one fails the remainder still\nexecute (best-effort). config shape is type-specific:\n\n  task.set_status      { statusId: uuid }\n  task.set_priority    { priority: low|normal|high|urgent }\n  task.add_tag         { tagId: uuid }\n  task.assign_user     { userId: uuid }\n  task.post_comment    { content: string }\n  task.close           — no config\n\nAction targets the Task that triggered the parent Automation (we don't\ncross-target yet; in awork actions can fan out — that's a future block).")

/**
 * @description Invalid input
 */
export const apiAutomationActionsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiAutomationActionsPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiAutomationActionsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new AutomationAction resource
 */
export const apiAutomationActionsPostMutationRequestSchema = z.lazy(() => automationActionSchema).describe("One step the Automation runs when triggered. Multiple Actions per\nAutomation run in `position` order; if one fails the remainder still\nexecute (best-effort). config shape is type-specific:\n\n  task.set_status      { statusId: uuid }\n  task.set_priority    { priority: low|normal|high|urgent }\n  task.add_tag         { tagId: uuid }\n  task.assign_user     { userId: uuid }\n  task.post_comment    { content: string }\n  task.close           — no config\n\nAction targets the Task that triggered the parent Automation (we don't\ncross-target yet; in awork actions can fan out — that's a future block).").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiAutomationActionsPostMutationResponseSchema = z.lazy(() => apiAutomationActionsPost201Schema)