/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAutomationActionsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("AutomationAction identifier")
    })

/**
 * @description AutomationAction resource deleted
 */
export const apiAutomationActionsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiAutomationActionsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAutomationActionsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAutomationActionsIdDeleteMutationResponseSchema = z.lazy(() => apiAutomationActionsIdDelete204Schema)