/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { activeTimerJsonldSchema } from "./activeTimer/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiActiveTimersGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page")
    })

/**
 * @description ActiveTimer collection
 */
export const apiActiveTimersGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(activeTimerJsonldSchema.describe("Currently-running stopwatch for one user. At most one row per user (UNIQUE\non user_id) — starting a new timer auto-stops the previous one and turns it\ninto a finalized TimeEntry.\n\nThis is a deliberately separate entity from TimeEntry so:\n  - TimeEntries stay immutable historical records,\n  - the running stopwatch doesn't pollute reports with a zero-or-partial\n    duration row,\n  - the polling endpoint to render \"Sven is tracking X\" only hits one row.\n\nRead-only via the API; clients drive transitions through the dedicated\n/v1/timers/start and /v1/timers/stop endpoints."))
              }
    })).describe("ActiveTimer.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiActiveTimersGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiActiveTimersGetCollectionQueryResponseSchema = z.lazy(() => apiActiveTimersGetCollection200Schema)