/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAbsencesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Absence identifier")
    })

/**
 * @description Absence resource deleted
 */
export const apiAbsencesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiAbsencesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAbsencesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAbsencesIdDeleteMutationResponseSchema = z.lazy(() => apiAbsencesIdDelete204Schema)