/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { automationActionJsonldSchema } from "./automationAction/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiAutomationActionsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"automation": z.optional(z.string()),
"automation[]": z.optional(z.array(z.string())),
"type": z.optional(z.string()),
"type[]": z.optional(z.array(z.string())),
"order[position]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description AutomationAction collection
 */
export const apiAutomationActionsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(automationActionJsonldSchema.describe("One step the Automation runs when triggered. Multiple Actions per\nAutomation run in `position` order; if one fails the remainder still\nexecute (best-effort). config shape is type-specific:\n\n  task.set_status      { statusId: uuid }\n  task.set_priority    { priority: low|normal|high|urgent }\n  task.add_tag         { tagId: uuid }\n  task.assign_user     { userId: uuid }\n  task.post_comment    { content: string }\n  task.close           — no config\n\nAction targets the Task that triggered the parent Automation (we don't\ncross-target yet; in awork actions can fan out — that's a future block)."))
              }
    })).describe("AutomationAction.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiAutomationActionsGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAutomationActionsGetCollectionQueryResponseSchema = z.lazy(() => apiAutomationActionsGetCollection200Schema)