/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { automationActionJsonldSchema } from "./automationAction/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiAutomationActionsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("AutomationAction identifier")
    })

/**
 * @description AutomationAction resource
 */
export const apiAutomationActionsIdGet200Schema = z.lazy(() => automationActionJsonldSchema).describe("One step the Automation runs when triggered. Multiple Actions per\nAutomation run in `position` order; if one fails the remainder still\nexecute (best-effort). config shape is type-specific:\n\n  task.set_status      { statusId: uuid }\n  task.set_priority    { priority: low|normal|high|urgent }\n  task.add_tag         { tagId: uuid }\n  task.assign_user     { userId: uuid }\n  task.post_comment    { content: string }\n  task.close           — no config\n\nAction targets the Task that triggered the parent Automation (we don't\ncross-target yet; in awork actions can fan out — that's a future block).")

/**
 * @description Forbidden
 */
export const apiAutomationActionsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiAutomationActionsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiAutomationActionsIdGetQueryResponseSchema = z.lazy(() => apiAutomationActionsIdGet200Schema)