/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiContactsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Contact identifier")
    })

/**
 * @description Contact resource deleted
 */
export const apiContactsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiContactsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiContactsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiContactsIdDeleteMutationResponseSchema = z.lazy(() => apiContactsIdDelete204Schema)