/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { customFieldDefinitionJsonldSchema } from "./customFieldDefinition/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiCustomFieldDefinitionsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"target": z.optional(z.string()),
"target[]": z.optional(z.array(z.string())),
"type": z.optional(z.string()),
"type[]": z.optional(z.array(z.string())),
"key": z.optional(z.string()),
"key[]": z.optional(z.array(z.string())),
"label": z.optional(z.string()),
"isRequired": z.optional(z.boolean()),
"isArchived": z.optional(z.boolean()),
"order[position]": z.enum(["asc", "desc"]).default("asc"),
"order[label]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description CustomFieldDefinition collection
 */
export const apiCustomFieldDefinitionsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(customFieldDefinitionJsonldSchema.describe("Workspace-scoped definition of a user-defined field that can be attached to\nProject / Task / TimeEntry (extensible via CustomFieldTarget enum).\n\n`target` controls which entity types may carry a value of this field.\n`key` is the stable machine identifier used in API payloads and integrations."))
              }
    })).describe("CustomFieldDefinition.jsonld collection.")

export const apiCustomFieldDefinitionsGetCollectionQueryResponseSchema = z.lazy(() => apiCustomFieldDefinitionsGetCollection200Schema)