/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { customerSystemJsonldSchema } from "./customerSystem/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiCustomerSystemsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("CustomerSystem identifier")
    })

/**
 * @description CustomerSystem resource
 */
export const apiCustomerSystemsIdGet200Schema = z.lazy(() => customerSystemJsonldSchema).describe("A concrete system instance the agency runs for a customer — one TYPO3\nmain site, one WordPress blog, one Shopware store. Customers may have\nany number of systems and each system may carry its own\nServiceSubscriptions for hosting / maintenance / SLA.\n\nThe agency cares about three buckets of data here:\n  1. Operational: live + staging URLs, hosting provider, environment\n     label, admin entry-point URL.\n  2. Maintenance: SystemType drives what UI controls and what dashboards\n     apply (a TYPO3-specific health-check page makes no sense on a\n     WordPress instance).\n  3. Notes: a free-form text field for credentials, quirks, contacts.\n     INTENTIONALLY plaintext for now — secret encryption needs a proper\n     KMS story (see roadmap CRM-3). Until then, treat this field as\n     privileged like any other PII / credentials column.\n\nCustomer ↔ Workspace consistency: `workspace` is denormalized from the\ncustomer so voters and filters don't always have to join.")

/**
 * @description Forbidden
 */
export const apiCustomerSystemsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiCustomerSystemsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiCustomerSystemsIdGetQueryResponseSchema = z.lazy(() => apiCustomerSystemsIdGet200Schema)