/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { customFieldDefinitionJsonldSchema } from "./customFieldDefinition/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiCustomFieldDefinitionsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("CustomFieldDefinition identifier")
    })

/**
 * @description CustomFieldDefinition resource
 */
export const apiCustomFieldDefinitionsIdGet200Schema = z.lazy(() => customFieldDefinitionJsonldSchema).describe("Workspace-scoped definition of a user-defined field that can be attached to\nProject / Task / TimeEntry (extensible via CustomFieldTarget enum).\n\n`target` controls which entity types may carry a value of this field.\n`key` is the stable machine identifier used in API payloads and integrations.")

/**
 * @description Not found
 */
export const apiCustomFieldDefinitionsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiCustomFieldDefinitionsIdGetQueryResponseSchema = z.lazy(() => apiCustomFieldDefinitionsIdGet200Schema)