/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { customerJsonldSchema } from "./customer/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiCustomersGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"legalName": z.optional(z.string()),
"email": z.optional(z.string()),
"status": z.optional(z.string()),
"status[]": z.optional(z.array(z.string())),
"industry": z.optional(z.string()),
"tags.id": z.optional(z.string()),
"tags.id[]": z.optional(z.array(z.string())),
"isCompany": z.optional(z.boolean()),
"exists[deletedAt]": z.optional(z.boolean()),
"order[name]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc"),
"order[updatedAt]": z.enum(["asc", "desc"]).default("asc"),
"order[status]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description Customer collection
 */
export const apiCustomersGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(customerJsonldSchema.describe("A workspace-scoped customer record — the agency's view of one client.\n\nThis is *deliberately* not modeled like awork's `Company` entity, which\nexisted only as an FK on Project (no first-class customer DB). In Worktide\neach Workspace owns a full CRM of Customers; Projects optionally link to a\nCustomer, ServiceSubscriptions hang off CustomerSystems (Phase 3 block 2),\nand the TYPO3 client portal will read this same table.\n\n`isCompany` flips the schema between \"company with VAT and legalName\" and\n\"private person with first/last name\". The flat `addressLine1/2/zip/city/\ncountry` fields are good enough for the MVP — a future block can move\naddresses into a polymorphic Address entity if we need multi-address\n(billing / shipping / visit).\n\nLifecycle: Prospect → Active → Inactive | Churned → Archived. The status\nfield is informational — no automated transitions yet; an operator\npatches it as the relationship evolves."))
              }
    })).describe("Customer.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiCustomersGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiCustomersGetCollectionQueryResponseSchema = z.lazy(() => apiCustomersGetCollection200Schema)