/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiCommentsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Comment identifier")
    })

/**
 * @description Comment resource deleted
 */
export const apiCommentsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiCommentsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiCommentsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiCommentsIdDeleteMutationResponseSchema = z.lazy(() => apiCommentsIdDelete204Schema)