/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiChecklistItemsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("ChecklistItem identifier")
    })

/**
 * @description ChecklistItem resource deleted
 */
export const apiChecklistItemsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiChecklistItemsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiChecklistItemsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiChecklistItemsIdDeleteMutationResponseSchema = z.lazy(() => apiChecklistItemsIdDelete204Schema)