/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { customFieldDefinitionJsonldSchema } from "./customFieldDefinition/jsonldSchema.ts";
import { customFieldDefinitionSchema } from "./customFieldDefinitionSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

/**
 * @description CustomFieldDefinition resource created
 */
export const apiCustomFieldDefinitionsPost201Schema = z.lazy(() => customFieldDefinitionJsonldSchema).describe("Workspace-scoped definition of a user-defined field that can be attached to\nProject / Task / TimeEntry (extensible via CustomFieldTarget enum).\n\n`target` controls which entity types may carry a value of this field.\n`key` is the stable machine identifier used in API payloads and integrations.")

/**
 * @description Invalid input
 */
export const apiCustomFieldDefinitionsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiCustomFieldDefinitionsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new CustomFieldDefinition resource
 */
export const apiCustomFieldDefinitionsPostMutationRequestSchema = z.lazy(() => customFieldDefinitionSchema).describe("Workspace-scoped definition of a user-defined field that can be attached to\nProject / Task / TimeEntry (extensible via CustomFieldTarget enum).\n\n`target` controls which entity types may carry a value of this field.\n`key` is the stable machine identifier used in API payloads and integrations.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true,'required': true,'archived': true })

export const apiCustomFieldDefinitionsPostMutationResponseSchema = z.lazy(() => apiCustomFieldDefinitionsPost201Schema)