/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { customerJsonMergePatchSchema } from "./customer/jsonMergePatchSchema.ts";
import { customerJsonldSchema } from "./customer/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiCustomersIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("Customer identifier")
    })

/**
 * @description Customer resource updated
 */
export const apiCustomersIdPatch200Schema = z.lazy(() => customerJsonldSchema).describe("A workspace-scoped customer record — the agency's view of one client.\n\nThis is *deliberately* not modeled like awork's `Company` entity, which\nexisted only as an FK on Project (no first-class customer DB). In Worktide\neach Workspace owns a full CRM of Customers; Projects optionally link to a\nCustomer, ServiceSubscriptions hang off CustomerSystems (Phase 3 block 2),\nand the TYPO3 client portal will read this same table.\n\n`isCompany` flips the schema between \"company with VAT and legalName\" and\n\"private person with first/last name\". The flat `addressLine1/2/zip/city/\ncountry` fields are good enough for the MVP — a future block can move\naddresses into a polymorphic Address entity if we need multi-address\n(billing / shipping / visit).\n\nLifecycle: Prospect → Active → Inactive | Churned → Archived. The status\nfield is informational — no automated transitions yet; an operator\npatches it as the relationship evolves.")

/**
 * @description Invalid input
 */
export const apiCustomersIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiCustomersIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiCustomersIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiCustomersIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated Customer resource
 */
export const apiCustomersIdPatchMutationRequestSchema = z.lazy(() => customerJsonMergePatchSchema).describe("A workspace-scoped customer record — the agency's view of one client.\n\nThis is *deliberately* not modeled like awork's `Company` entity, which\nexisted only as an FK on Project (no first-class customer DB). In Worktide\neach Workspace owns a full CRM of Customers; Projects optionally link to a\nCustomer, ServiceSubscriptions hang off CustomerSystems (Phase 3 block 2),\nand the TYPO3 client portal will read this same table.\n\n`isCompany` flips the schema between \"company with VAT and legalName\" and\n\"private person with first/last name\". The flat `addressLine1/2/zip/city/\ncountry` fields are good enough for the MVP — a future block can move\naddresses into a polymorphic Address entity if we need multi-address\n(billing / shipping / visit).\n\nLifecycle: Prospect → Active → Inactive | Churned → Archived. The status\nfield is informational — no automated transitions yet; an operator\npatches it as the relationship evolves.").unwrap().omit({ 'contacts': true,'projects': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'company': true,'deleted': true,'externalRef': true })

export const apiCustomersIdPatchMutationResponseSchema = z.lazy(() => apiCustomersIdPatch200Schema)