/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiConversationsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Conversation identifier")
    })

/**
 * @description Conversation resource deleted
 */
export const apiConversationsIdDelete204Schema = z.unknown()

/**
 * @description Not found
 */
export const apiConversationsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiConversationsIdDeleteMutationResponseSchema = z.lazy(() => apiConversationsIdDelete204Schema)