/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { channelJsonldSchema } from "./channel/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiChannelsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Channel identifier")
    })

/**
 * @description Channel resource
 */
export const apiChannelsIdGet200Schema = z.lazy(() => channelJsonldSchema).describe("Source-agnostic communication endpoint for a workspace.\n\nA Channel is a configuration row that binds an in-code adapter\n(`adapterCode` — e.g. `email_imap`, `email_graph`, `slack_bot`,\n`zabbix_webhook`) to a workspace, holds its auth + endpoint config,\nand declares whether it carries inbound, outbound, or both.\n\nMails are the canonical both-capable channel (IMAP-Pull + SMTP-Send\non the same Mailbox). A Zabbix webhook is inbound-only. A\ntransactional Mailgun setup is outbound-only.\n\nTier-1 implementation only ships the three email adapters\n(email_imap / email_graph / email_gmail). Slack/Zabbix/Twilio/etc.\ndock onto this entity in later phases without a schema migration —\nadding a new value to the `adapterCode` whitelist is enough.\n\n`authConfig` is stored as JSON and is meant to be **libsodium-\nencrypted at rest** by an Doctrine event-listener (TBD in C.2). The\nraw column never holds passwords/tokens in cleartext.\n\n`inboundConfig` / `outboundConfig` are adapter-specific shapes\n(IMAP host/port/folder, Graph user-id, Gmail labelIds, …). The\nadapter declares its expected schema; this entity stores it\nopaque.")

/**
 * @description Not found
 */
export const apiChannelsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiChannelsIdGetQueryResponseSchema = z.lazy(() => apiChannelsIdGet200Schema)