/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { commentJsonldSchema } from "./comment/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiCommentsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"target": z.optional(z.string()),
"target[]": z.optional(z.array(z.string())),
"targetId": z.optional(z.string()),
"targetId[]": z.optional(z.array(z.string())),
"author": z.optional(z.string()),
"author[]": z.optional(z.array(z.string())),
"parent": z.optional(z.string()),
"parent[]": z.optional(z.array(z.string())),
"content": z.optional(z.string()),
"isResolved": z.optional(z.boolean()),
"isHiddenForConnectUsers": z.optional(z.boolean()),
"exists[pinnedAt]": z.optional(z.boolean()),
"exists[parent]": z.optional(z.boolean()),
"exists[editedAt]": z.optional(z.boolean()),
"createdAt[before]": z.optional(z.string()),
"createdAt[strictly_before]": z.optional(z.string()),
"createdAt[after]": z.optional(z.string()),
"createdAt[strictly_after]": z.optional(z.string()),
"updatedAt[before]": z.optional(z.string()),
"updatedAt[strictly_before]": z.optional(z.string()),
"updatedAt[after]": z.optional(z.string()),
"updatedAt[strictly_after]": z.optional(z.string()),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc"),
"order[pinnedAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description Comment collection
 */
export const apiCommentsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(commentJsonldSchema.describe("Polymorphic comment attached to a Project / Task / Document (extensible).\n\nMirrors awork's pinning + threading semantics:\n - `parent` enables one-level reply threads\n - `pinnedAt` + `pinnedBy` flag a comment as \"important\" (sticks to the top)\n - `editedAt` differentiates the original post from edits (clients badge it)\n - `mentions` is a JSON array of user UUIDs referenced via @-syntax; the\n   notification subsystem (later) will read this column.\n\nPrivacy: comments inherit visibility from their parent — voter delegates."))
              }
    })).describe("Comment.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiCommentsGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiCommentsGetCollectionQueryResponseSchema = z.lazy(() => apiCommentsGetCollection200Schema)