/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { customerSystemJsonldSchema } from "./customerSystem/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiCustomerSystemsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"customer": z.optional(z.string()),
"customer[]": z.optional(z.array(z.string())),
"type": z.optional(z.string()),
"type[]": z.optional(z.array(z.string())),
"environment": z.optional(z.string()),
"environment[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"hostingProvider": z.optional(z.string()),
"isActive": z.optional(z.boolean()),
"order[name]": z.enum(["asc", "desc"]).default("asc"),
"order[type]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description CustomerSystem collection
 */
export const apiCustomerSystemsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(customerSystemJsonldSchema.describe("A concrete system instance the agency runs for a customer — one TYPO3\nmain site, one WordPress blog, one Shopware store. Customers may have\nany number of systems and each system may carry its own\nServiceSubscriptions for hosting / maintenance / SLA.\n\nThe agency cares about three buckets of data here:\n  1. Operational: live + staging URLs, hosting provider, environment\n     label, admin entry-point URL.\n  2. Maintenance: SystemType drives what UI controls and what dashboards\n     apply (a TYPO3-specific health-check page makes no sense on a\n     WordPress instance).\n  3. Notes: a free-form text field for credentials, quirks, contacts.\n     INTENTIONALLY plaintext for now — secret encryption needs a proper\n     KMS story (see roadmap CRM-3). Until then, treat this field as\n     privileged like any other PII / credentials column.\n\nCustomer ↔ Workspace consistency: `workspace` is denormalized from the\ncustomer so voters and filters don't always have to join."))
              }
    })).describe("CustomerSystem.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiCustomerSystemsGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiCustomerSystemsGetCollectionQueryResponseSchema = z.lazy(() => apiCustomerSystemsGetCollection200Schema)