/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { domainEventJsonldSchema } from "./domainEvent/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiDomainEventsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("DomainEvent identifier")
    })

/**
 * @description DomainEvent resource
 */
export const apiDomainEventsIdGet200Schema = z.lazy(() => domainEventJsonldSchema).describe("Immutable event log. UUIDv7 PK gives a natural monotonic cursor —\nsubscribers paginate by \"id greater than last seen\".")

/**
 * @description Not found
 */
export const apiDomainEventsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiDomainEventsIdGetQueryResponseSchema = z.lazy(() => apiDomainEventsIdGet200Schema)