/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { domainEventJsonldSchema } from "./domainEvent/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiDomainEventsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"name": z.optional(z.string()),
"aggregateType": z.optional(z.string()),
"aggregateType[]": z.optional(z.array(z.string())),
"aggregateId": z.optional(z.string()),
"aggregateId[]": z.optional(z.array(z.string())),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"actor": z.optional(z.string()),
"actor[]": z.optional(z.array(z.string())),
"occurredAt[before]": z.optional(z.string()),
"occurredAt[strictly_before]": z.optional(z.string()),
"occurredAt[after]": z.optional(z.string()),
"occurredAt[strictly_after]": z.optional(z.string()),
"order[occurredAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description DomainEvent collection
 */
export const apiDomainEventsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(domainEventJsonldSchema.describe("Immutable event log. UUIDv7 PK gives a natural monotonic cursor —\nsubscribers paginate by \"id greater than last seen\"."))
              }
    })).describe("DomainEvent.jsonld collection.")

export const apiDomainEventsGetCollectionQueryResponseSchema = z.lazy(() => apiDomainEventsGetCollection200Schema)