/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiDocumentSpacesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("DocumentSpace identifier")
    })

/**
 * @description DocumentSpace resource deleted
 */
export const apiDocumentSpacesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiDocumentSpacesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiDocumentSpacesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiDocumentSpacesIdDeleteMutationResponseSchema = z.lazy(() => apiDocumentSpacesIdDelete204Schema)