/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { documentSpaceJsonldSchema } from "./documentSpace/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiDocumentSpacesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("DocumentSpace identifier")
    })

/**
 * @description DocumentSpace resource
 */
export const apiDocumentSpacesIdGet200Schema = z.lazy(() => documentSpaceJsonldSchema).describe("Container for Documents — equivalent to a Notion/Confluence \"space\" or a\ntop-level sidebar group. Documents can also exist without a space (private\nnotes); when both exist, space ordering wins over project ordering.\n\nPer-space access (contributors / team access) is deferred — for the MVP a\nspace is workspace-wide-readable; the writer-restriction is on the\nDocument itself via DocumentContributor.")

/**
 * @description Forbidden
 */
export const apiDocumentSpacesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiDocumentSpacesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiDocumentSpacesIdGetQueryResponseSchema = z.lazy(() => apiDocumentSpacesIdGet200Schema)