/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { documentRevisionJsonldSchema } from "./documentRevision/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiDocumentRevisionsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("DocumentRevision identifier")
    })

/**
 * @description DocumentRevision resource
 */
export const apiDocumentRevisionsIdGet200Schema = z.lazy(() => documentRevisionJsonldSchema).describe("Append-only snapshot of a Document at one save-point. Lets the wiki\nUI walk back through history and restore older bodies.\n\nCreated by DocumentRevisionListener whenever a Document's name or\nbody changes (preUpdate). The pre-existing values are snapshotted —\nthe listener writes the LAST KNOWN state, not the new one, so the\nrevision list reads like a real history (\"Stand vom Datum X\").\n\nRevisions are read-only — no Patch/Post via the API. Restoring goes\nthrough a custom action on Document, not by mutating the revision.")

/**
 * @description Forbidden
 */
export const apiDocumentRevisionsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiDocumentRevisionsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiDocumentRevisionsIdGetQueryResponseSchema = z.lazy(() => apiDocumentRevisionsIdGet200Schema)