/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { documentSpaceJsonldSchema } from "./documentSpace/jsonldSchema.ts";
import { documentSpaceSchema } from "./documentSpaceSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

/**
 * @description DocumentSpace resource created
 */
export const apiDocumentSpacesPost201Schema = z.lazy(() => documentSpaceJsonldSchema).describe("Container for Documents — equivalent to a Notion/Confluence \"space\" or a\ntop-level sidebar group. Documents can also exist without a space (private\nnotes); when both exist, space ordering wins over project ordering.\n\nPer-space access (contributors / team access) is deferred — for the MVP a\nspace is workspace-wide-readable; the writer-restriction is on the\nDocument itself via DocumentContributor.")

/**
 * @description Invalid input
 */
export const apiDocumentSpacesPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiDocumentSpacesPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiDocumentSpacesPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new DocumentSpace resource
 */
export const apiDocumentSpacesPostMutationRequestSchema = z.lazy(() => documentSpaceSchema).describe("Container for Documents — equivalent to a Notion/Confluence \"space\" or a\ntop-level sidebar group. Documents can also exist without a space (private\nnotes); when both exist, space ordering wins over project ordering.\n\nPer-space access (contributors / team access) is deferred — for the MVP a\nspace is workspace-wide-readable; the writer-restriction is on the\nDocument itself via DocumentContributor.").unwrap().omit({ 'documents': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'archived': true,'deleted': true })

export const apiDocumentSpacesPostMutationResponseSchema = z.lazy(() => apiDocumentSpacesPost201Schema)