/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiDocumentsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Document identifier")
    })

/**
 * @description Document resource deleted
 */
export const apiDocumentsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiDocumentsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiDocumentsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiDocumentsIdDeleteMutationResponseSchema = z.lazy(() => apiDocumentsIdDelete204Schema)