/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { entitySyncJsonldSchema } from "./entitySync/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiEntitySyncsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"channel": z.optional(z.string()),
"channel[]": z.optional(z.array(z.string())),
"entityType": z.optional(z.string()),
"entityType[]": z.optional(z.array(z.string())),
"entityId": z.optional(z.string()),
"entityId[]": z.optional(z.array(z.string())),
"externalId": z.optional(z.string()),
"externalId[]": z.optional(z.array(z.string())),
"syncMode": z.optional(z.string()),
"syncMode[]": z.optional(z.array(z.string()))
    })

/**
 * @description EntitySync collection
 */
export const apiEntitySyncsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(entitySyncJsonldSchema.describe("One mapping row between a Worktide entity and its mirror in an\nexternal system. Replaces and generalises the per-entity\n{@see Trait\\ExternalReferenceTrait} for cases that need:\n\n  - M:N. A single Worktide Task can be mirrored in Jira AND\n    Redmine AND a CalDAV calendar simultaneously — three\n    EntitySync rows, one per channel.\n  - Bidirectional sync state. The trait only carried a flat ID;\n    this entity carries `externalUpdatedAt` + `ourVersion` + `etag`\n    so adapters can detect dual-changes and apply\n    {@see ConflictPolicy}.\n  - Pause without un-mapping. `syncMode = Disabled` keeps the\n    mapping intact while halting reads/writes — useful during\n    debugging or partial migrations.\n\nThe (entityType, entityId) pair carries the **identity** of the\nWorktide-side record; entityType is a free-form string slug\n(`task`, `project`, `customer`, `time_entry`, `calendar_event`)\nso we don't have to invent a discriminator hierarchy for every\nfuture entity that becomes syncable.\n\nUNIQUE(channel, externalId) makes a single external record map\nto at most one local entity per channel; the inverse is allowed\n(one local entity in N channels), which is exactly the M:N we\nwant."))
              }
    })).describe("EntitySync.jsonld collection.")

export const apiEntitySyncsGetCollectionQueryResponseSchema = z.lazy(() => apiEntitySyncsGetCollection200Schema)