/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { fileJsonldSchema } from "./file/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const apiFilesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"target": z.optional(z.string()),
"target[]": z.optional(z.array(z.string())),
"targetId": z.optional(z.string()),
"targetId[]": z.optional(z.array(z.string())),
"mimeType": z.optional(z.string()),
"name": z.optional(z.string()),
"uploadedBy": z.optional(z.string()),
"uploadedBy[]": z.optional(z.array(z.string())),
"isExternal": z.optional(z.boolean()),
"isHiddenForConnectUsers": z.optional(z.boolean()),
"order[name]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description File collection
 */
export const apiFilesGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(fileJsonldSchema.describe("Polymorphic file attachment. The \"file\" itself is metadata only — actual\nbytes live on Flysystem-managed storage and are addressed through\nFileVersion entries (one File can have N revisions; the latest is the\n\"current\" version, kept on this row for fast lookups).\n\nUploads happen through FileUploadController (multipart) and become version 1\nof a new File row. Subsequent versions add new FileVersion rows without\nmutating the File metadata.\n\nCross-tenant safety: workspace-scoped + voter delegates to the target entity."))
              }
    })).describe("File.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiFilesGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiFilesGetCollectionQueryResponseSchema = z.lazy(() => apiFilesGetCollection200Schema)