/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiFilesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("File identifier")
    })

/**
 * @description File resource deleted
 */
export const apiFilesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiFilesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiFilesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiFilesIdDeleteMutationResponseSchema = z.lazy(() => apiFilesIdDelete204Schema)