/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Project identifier")
    })

/**
 * @description Project resource deleted
 */
export const apiProjectsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiProjectsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiProjectsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectsIdDeleteMutationResponseSchema = z.lazy(() => apiProjectsIdDelete204Schema)