/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectMemberJsonldSchema } from "./projectMember/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectMembersIdGetPathParamsSchema = z.object({
    "id": z.string().describe("ProjectMember identifier")
    })

/**
 * @description ProjectMember resource
 */
export const apiProjectMembersIdGet200Schema = z.lazy(() => projectMemberJsonldSchema)

/**
 * @description Not found
 */
export const apiProjectMembersIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectMembersIdGetQueryResponseSchema = z.lazy(() => apiProjectMembersIdGet200Schema)