/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectStatusesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("ProjectStatus identifier")
    })

/**
 * @description ProjectStatus resource deleted
 */
export const apiProjectStatusesIdDelete204Schema = z.unknown()

/**
 * @description Not found
 */
export const apiProjectStatusesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectStatusesIdDeleteMutationResponseSchema = z.lazy(() => apiProjectStatusesIdDelete204Schema)