/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiPersonalAccessTokensIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("PersonalAccessToken identifier")
    })

/**
 * @description PersonalAccessToken resource deleted
 */
export const apiPersonalAccessTokensIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiPersonalAccessTokensIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiPersonalAccessTokensIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiPersonalAccessTokensIdDeleteMutationResponseSchema = z.lazy(() => apiPersonalAccessTokensIdDelete204Schema)