/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectMilestoneJsonldSchema } from "./projectMilestone/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectMilestonesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("ProjectMilestone identifier")
    })

/**
 * @description ProjectMilestone resource
 */
export const apiProjectMilestonesIdGet200Schema = z.lazy(() => projectMilestoneJsonldSchema).describe("A named goal/checkpoint inside a Project — typically tied to a due date,\nwith an optional set of tasks whose completion marks it as reached.\n\nGoing beyond awork (which only has id/name/color/dueDate):\n - `isReached` + `reachedOn` + `reachedBy` so the activity feed knows when\n - `isArchived` to hide stale milestones without losing history\n - M:N to Task — \"what needs to be done for this milestone\"\n - `description` + `position` for richer UI")

/**
 * @description Forbidden
 */
export const apiProjectMilestonesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiProjectMilestonesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectMilestonesIdGetQueryResponseSchema = z.lazy(() => apiProjectMilestonesIdGet200Schema)