/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectVersionJsonldSchema } from "./projectVersion/jsonldSchema.ts";
import { projectVersionSchema } from "./projectVersionSchema.ts";
import { z } from "zod/v4";

/**
 * @description ProjectVersion resource created
 */
export const apiProjectVersionsPost201Schema = z.lazy(() => projectVersionJsonldSchema).describe("A Release / Version of a Project — the \"ship target\" axis on top of\nProject + Tracker + Status. Tasks can be tagged with `fixedVersion`\nto mark \"this work goes into Release 1.2.0\".\n\nNamed `ProjectVersion` (not `Version`) to avoid clashing with the\nVersionedTrait + Symfony's `Symfony\\Component\\Console\\Application::VERSION`\n+ general naming clarity (we already have `version: int` optimistic\nlocking on most entities).\n\nSharing field is reserved for the future Redmine-style cross-project\nrelease model — for now Worktide ships only `none` (this project) and\n`system` (every project in the workspace). The other three enum\nvalues exist so the column doesn't need a migration when sub-projects\nland in a later phase.\n\neffectiveDate is the planned ship date — burndown / release reports\nuse it as the X-axis anchor. When `status=closed`, the SPA treats\neffectiveDate as the actual release date.\n\nwikiPageTitle is a plain string (not an FK) because the Document a\nrelease-page lives at can be in any space; storing only the title +\nthe workspace lets the SPA look it up by name without forcing a\nlink-table that gets stale when pages are renamed.")

/**
 * @description Invalid input
 */
export const apiProjectVersionsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiProjectVersionsPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiProjectVersionsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new ProjectVersion resource
 */
export const apiProjectVersionsPostMutationRequestSchema = z.lazy(() => projectVersionSchema).describe("A Release / Version of a Project — the \"ship target\" axis on top of\nProject + Tracker + Status. Tasks can be tagged with `fixedVersion`\nto mark \"this work goes into Release 1.2.0\".\n\nNamed `ProjectVersion` (not `Version`) to avoid clashing with the\nVersionedTrait + Symfony's `Symfony\\Component\\Console\\Application::VERSION`\n+ general naming clarity (we already have `version: int` optimistic\nlocking on most entities).\n\nSharing field is reserved for the future Redmine-style cross-project\nrelease model — for now Worktide ships only `none` (this project) and\n`system` (every project in the workspace). The other three enum\nvalues exist so the column doesn't need a migration when sub-projects\nland in a later phase.\n\neffectiveDate is the planned ship date — burndown / release reports\nuse it as the X-axis anchor. When `status=closed`, the SPA treats\neffectiveDate as the actual release date.\n\nwikiPageTitle is a plain string (not an FK) because the Document a\nrelease-page lives at can be in any space; storing only the title +\nthe workspace lets the SPA look it up by name without forcing a\nlink-table that gets stale when pages are renamed.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'deleted': true })

export const apiProjectVersionsPostMutationResponseSchema = z.lazy(() => apiProjectVersionsPost201Schema)