/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectVersionsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("ProjectVersion identifier")
    })

/**
 * @description ProjectVersion resource deleted
 */
export const apiProjectVersionsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiProjectVersionsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiProjectVersionsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectVersionsIdDeleteMutationResponseSchema = z.lazy(() => apiProjectVersionsIdDelete204Schema)