/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectJsonldSchema } from "./project/jsonldSchema.ts";
import { projectSchema } from "./projectSchema.ts";
import { z } from "zod/v4";

/**
 * @description Project resource created
 */
export const apiProjectsPost201Schema = z.lazy(() => projectJsonldSchema)

/**
 * @description Invalid input
 */
export const apiProjectsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiProjectsPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiProjectsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Project resource
 */
export const apiProjectsPostMutationRequestSchema = z.lazy(() => projectSchema).unwrap().omit({ 'members': true,'tasks': true,'taskLists': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'archived': true,'private': true,'billableByDefault': true,'image': true,'retainer': true,'multiAssignmentAllowed': true,'deleted': true,'externalRef': true })

export const apiProjectsPostMutationResponseSchema = z.lazy(() => apiProjectsPost201Schema)