/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectTemplateJsonldSchema } from "./projectTemplate/jsonldSchema.ts";
import { projectTemplateSchema } from "./projectTemplateSchema.ts";
import { z } from "zod/v4";

/**
 * @description ProjectTemplate resource created
 */
export const apiProjectTemplatesPost201Schema = z.lazy(() => projectTemplateJsonldSchema).describe("Reusable blueprint for a Project. Captures the project's \"defaults\"\n(name, description, color, projectType, billing flags) plus a reference\nto a TaskBundle whose templates become the initial Tasks when this\nproject template is instantiated.\n\n`instantiate` (controller action) creates a new Project + copies bundle\ntemplates into real Tasks, dueDates relative to the new project's start.")

/**
 * @description Invalid input
 */
export const apiProjectTemplatesPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiProjectTemplatesPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiProjectTemplatesPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new ProjectTemplate resource
 */
export const apiProjectTemplatesPostMutationRequestSchema = z.lazy(() => projectTemplateSchema).describe("Reusable blueprint for a Project. Captures the project's \"defaults\"\n(name, description, color, projectType, billing flags) plus a reference\nto a TaskBundle whose templates become the initial Tasks when this\nproject template is instantiated.\n\n`instantiate` (controller action) creates a new Project + copies bundle\ntemplates into real Tasks, dueDates relative to the new project's start.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'published': true,'archived': true,'deleted': true })

export const apiProjectTemplatesPostMutationResponseSchema = z.lazy(() => apiProjectTemplatesPost201Schema)