/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { projectMemberJsonldSchema } from "./projectMember/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectMembersGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"project": z.optional(z.string()),
"project[]": z.optional(z.array(z.string())),
"user": z.optional(z.string()),
"user[]": z.optional(z.array(z.string())),
"role": z.optional(z.string()),
"role[]": z.optional(z.array(z.string()))
    })

/**
 * @description ProjectMember collection
 */
export const apiProjectMembersGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(projectMemberJsonldSchema)
              }
    })).describe("ProjectMember.jsonld collection.")

export const apiProjectMembersGetCollectionQueryResponseSchema = z.lazy(() => apiProjectMembersGetCollection200Schema)