/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectMilestonesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("ProjectMilestone identifier")
    })

/**
 * @description ProjectMilestone resource deleted
 */
export const apiProjectMilestonesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiProjectMilestonesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiProjectMilestonesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectMilestonesIdDeleteMutationResponseSchema = z.lazy(() => apiProjectMilestonesIdDelete204Schema)