/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectMemberJsonMergePatchSchema } from "./projectMember/jsonMergePatchSchema.ts";
import { projectMemberJsonldSchema } from "./projectMember/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectMembersIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("ProjectMember identifier")
    })

/**
 * @description ProjectMember resource updated
 */
export const apiProjectMembersIdPatch200Schema = z.lazy(() => projectMemberJsonldSchema)

/**
 * @description Invalid input
 */
export const apiProjectMembersIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiProjectMembersIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiProjectMembersIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated ProjectMember resource
 */
export const apiProjectMembersIdPatchMutationRequestSchema = z.lazy(() => projectMemberJsonMergePatchSchema).unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true })

export const apiProjectMembersIdPatchMutationResponseSchema = z.lazy(() => apiProjectMembersIdPatch200Schema)