/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { projectMilestoneJsonldSchema } from "./projectMilestone/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectMilestonesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"project": z.optional(z.string()),
"project[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"isReached": z.optional(z.boolean()),
"isArchived": z.optional(z.boolean()),
"dueOn[before]": z.optional(z.string()),
"dueOn[strictly_before]": z.optional(z.string()),
"dueOn[after]": z.optional(z.string()),
"dueOn[strictly_after]": z.optional(z.string()),
"reachedOn[before]": z.optional(z.string()),
"reachedOn[strictly_before]": z.optional(z.string()),
"reachedOn[after]": z.optional(z.string()),
"reachedOn[strictly_after]": z.optional(z.string()),
"order[dueOn]": z.enum(["asc", "desc"]).default("asc"),
"order[position]": z.enum(["asc", "desc"]).default("asc"),
"order[name]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description ProjectMilestone collection
 */
export const apiProjectMilestonesGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(projectMilestoneJsonldSchema.describe("A named goal/checkpoint inside a Project — typically tied to a due date,\nwith an optional set of tasks whose completion marks it as reached.\n\nGoing beyond awork (which only has id/name/color/dueDate):\n - `isReached` + `reachedOn` + `reachedBy` so the activity feed knows when\n - `isArchived` to hide stale milestones without losing history\n - M:N to Task — \"what needs to be done for this milestone\"\n - `description` + `position` for richer UI"))
              }
    })).describe("ProjectMilestone.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiProjectMilestonesGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiProjectMilestonesGetCollectionQueryResponseSchema = z.lazy(() => apiProjectMilestonesGetCollection200Schema)