/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { projectTemplateJsonMergePatchSchema } from "./projectTemplate/jsonMergePatchSchema.ts";
import { projectTemplateJsonldSchema } from "./projectTemplate/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiProjectTemplatesIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("ProjectTemplate identifier")
    })

/**
 * @description ProjectTemplate resource updated
 */
export const apiProjectTemplatesIdPatch200Schema = z.lazy(() => projectTemplateJsonldSchema).describe("Reusable blueprint for a Project. Captures the project's \"defaults\"\n(name, description, color, projectType, billing flags) plus a reference\nto a TaskBundle whose templates become the initial Tasks when this\nproject template is instantiated.\n\n`instantiate` (controller action) creates a new Project + copies bundle\ntemplates into real Tasks, dueDates relative to the new project's start.")

/**
 * @description Invalid input
 */
export const apiProjectTemplatesIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiProjectTemplatesIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiProjectTemplatesIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiProjectTemplatesIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated ProjectTemplate resource
 */
export const apiProjectTemplatesIdPatchMutationRequestSchema = z.lazy(() => projectTemplateJsonMergePatchSchema).describe("Reusable blueprint for a Project. Captures the project's \"defaults\"\n(name, description, color, projectType, billing flags) plus a reference\nto a TaskBundle whose templates become the initial Tasks when this\nproject template is instantiated.\n\n`instantiate` (controller action) creates a new Project + copies bundle\ntemplates into real Tasks, dueDates relative to the new project's start.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'published': true,'archived': true,'deleted': true })

export const apiProjectTemplatesIdPatchMutationResponseSchema = z.lazy(() => apiProjectTemplatesIdPatch200Schema)