/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiRolePermissionOverridesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("RolePermissionOverride identifier")
    })

/**
 * @description RolePermissionOverride resource deleted
 */
export const apiRolePermissionOverridesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiRolePermissionOverridesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiRolePermissionOverridesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiRolePermissionOverridesIdDeleteMutationResponseSchema = z.lazy(() => apiRolePermissionOverridesIdDelete204Schema)