/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { rolePermissionOverrideJsonldSchema } from "./rolePermissionOverride/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiRolePermissionOverridesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"role": z.optional(z.string()),
"role[]": z.optional(z.array(z.string())),
"capability": z.optional(z.string()),
"capability[]": z.optional(z.array(z.string())),
"isGranted": z.optional(z.boolean())
    })

/**
 * @description RolePermissionOverride collection
 */
export const apiRolePermissionOverridesGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(rolePermissionOverrideJsonldSchema.describe("Workspace-scoped override of the DefaultPermissions matrix.\n\nEach row says: in workspace X, role R has capability C with value\n`isGranted` (which can be true OR false — overrides can both grant AND\nrevoke). The {@see PermissionResolver} consults overrides first and only\nfalls back to {@see \\App\\Security\\DefaultPermissions} when no row matches.\n\nThe unique constraint guarantees one override per (workspace, role,\ncapability) tuple — re-asserting the same triple updates the existing row\nrather than stacking conflicting policies.\n\nOwner is intentionally excluded as a target role here (validation): no\noverride should be able to lock the owner out of their own workspace."))
              }
    })).describe("RolePermissionOverride.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiRolePermissionOverridesGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiRolePermissionOverridesGetCollectionQueryResponseSchema = z.lazy(() => apiRolePermissionOverridesGetCollection200Schema)