/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { rolePermissionOverrideJsonldSchema } from "./rolePermissionOverride/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiRolePermissionOverridesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("RolePermissionOverride identifier")
    })

/**
 * @description RolePermissionOverride resource
 */
export const apiRolePermissionOverridesIdGet200Schema = z.lazy(() => rolePermissionOverrideJsonldSchema).describe("Workspace-scoped override of the DefaultPermissions matrix.\n\nEach row says: in workspace X, role R has capability C with value\n`isGranted` (which can be true OR false — overrides can both grant AND\nrevoke). The {@see PermissionResolver} consults overrides first and only\nfalls back to {@see \\App\\Security\\DefaultPermissions} when no row matches.\n\nThe unique constraint guarantees one override per (workspace, role,\ncapability) tuple — re-asserting the same triple updates the existing row\nrather than stacking conflicting policies.\n\nOwner is intentionally excluded as a target role here (validation): no\noverride should be able to lock the owner out of their own workspace.")

/**
 * @description Forbidden
 */
export const apiRolePermissionOverridesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiRolePermissionOverridesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiRolePermissionOverridesIdGetQueryResponseSchema = z.lazy(() => apiRolePermissionOverridesIdGet200Schema)