/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { serviceSubscriptionJsonldSchema } from "./serviceSubscription/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiServiceSubscriptionsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("ServiceSubscription identifier")
    })

/**
 * @description ServiceSubscription resource
 */
export const apiServiceSubscriptionsIdGet200Schema = z.lazy(() => serviceSubscriptionJsonldSchema).describe("A billable service the agency provides to one Customer. Optionally pinned\nto a specific CustomerSystem when the service is system-bound\n(hosting for the Foo TYPO3 instance) vs. customer-wide (general\nmaintenance retainer covering all of Foo's sites).\n\nMoney is stored as integer cents in the {@see self::$priceCents} column;\nno float column, no Decimal cast — multiplication and rounding stays\nexact. {@see self::$currency} is an ISO 4217 alpha-3 code in lowercase.\n\nLifecycle:\n  Trial → Active → (Paused) → Cancelled\n\n`nextBillingOn` is auto-recomputed by the prePersist/preUpdate listener\nfrom (startedOn, billingCycle, status). When the subscription is\nCancelled or Once-billed, nextBillingOn becomes null.")

/**
 * @description Forbidden
 */
export const apiServiceSubscriptionsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiServiceSubscriptionsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiServiceSubscriptionsIdGetQueryResponseSchema = z.lazy(() => apiServiceSubscriptionsIdGet200Schema)