/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { serviceSubscriptionJsonldSchema } from "./serviceSubscription/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiServiceSubscriptionsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"customer": z.optional(z.string()),
"customer[]": z.optional(z.array(z.string())),
"system": z.optional(z.string()),
"system[]": z.optional(z.array(z.string())),
"status": z.optional(z.string()),
"status[]": z.optional(z.array(z.string())),
"billingCycle": z.optional(z.string()),
"billingCycle[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"autoRenew": z.optional(z.boolean()),
"order[name]": z.enum(["asc", "desc"]).default("asc"),
"order[startedOn]": z.enum(["asc", "desc"]).default("asc"),
"order[nextBillingOn]": z.enum(["asc", "desc"]).default("asc"),
"order[priceCents]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description ServiceSubscription collection
 */
export const apiServiceSubscriptionsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(serviceSubscriptionJsonldSchema.describe("A billable service the agency provides to one Customer. Optionally pinned\nto a specific CustomerSystem when the service is system-bound\n(hosting for the Foo TYPO3 instance) vs. customer-wide (general\nmaintenance retainer covering all of Foo's sites).\n\nMoney is stored as integer cents in the {@see self::$priceCents} column;\nno float column, no Decimal cast — multiplication and rounding stays\nexact. {@see self::$currency} is an ISO 4217 alpha-3 code in lowercase.\n\nLifecycle:\n  Trial → Active → (Paused) → Cancelled\n\n`nextBillingOn` is auto-recomputed by the prePersist/preUpdate listener\nfrom (startedOn, billingCycle, status). When the subscription is\nCancelled or Once-billed, nextBillingOn becomes null."))
              }
    })).describe("ServiceSubscription.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiServiceSubscriptionsGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiServiceSubscriptionsGetCollectionQueryResponseSchema = z.lazy(() => apiServiceSubscriptionsGetCollection200Schema)