/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { serviceSubscriptionJsonMergePatchSchema } from "./serviceSubscription/jsonMergePatchSchema.ts";
import { serviceSubscriptionJsonldSchema } from "./serviceSubscription/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiServiceSubscriptionsIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("ServiceSubscription identifier")
    })

/**
 * @description ServiceSubscription resource updated
 */
export const apiServiceSubscriptionsIdPatch200Schema = z.lazy(() => serviceSubscriptionJsonldSchema).describe("A billable service the agency provides to one Customer. Optionally pinned\nto a specific CustomerSystem when the service is system-bound\n(hosting for the Foo TYPO3 instance) vs. customer-wide (general\nmaintenance retainer covering all of Foo's sites).\n\nMoney is stored as integer cents in the {@see self::$priceCents} column;\nno float column, no Decimal cast — multiplication and rounding stays\nexact. {@see self::$currency} is an ISO 4217 alpha-3 code in lowercase.\n\nLifecycle:\n  Trial → Active → (Paused) → Cancelled\n\n`nextBillingOn` is auto-recomputed by the prePersist/preUpdate listener\nfrom (startedOn, billingCycle, status). When the subscription is\nCancelled or Once-billed, nextBillingOn becomes null.")

/**
 * @description Invalid input
 */
export const apiServiceSubscriptionsIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiServiceSubscriptionsIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiServiceSubscriptionsIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiServiceSubscriptionsIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated ServiceSubscription resource
 */
export const apiServiceSubscriptionsIdPatchMutationRequestSchema = z.lazy(() => serviceSubscriptionJsonMergePatchSchema).describe("A billable service the agency provides to one Customer. Optionally pinned\nto a specific CustomerSystem when the service is system-bound\n(hosting for the Foo TYPO3 instance) vs. customer-wide (general\nmaintenance retainer covering all of Foo's sites).\n\nMoney is stored as integer cents in the {@see self::$priceCents} column;\nno float column, no Decimal cast — multiplication and rounding stays\nexact. {@see self::$currency} is an ISO 4217 alpha-3 code in lowercase.\n\nLifecycle:\n  Trial → Active → (Paused) → Cancelled\n\n`nextBillingOn` is auto-recomputed by the prePersist/preUpdate listener\nfrom (startedOn, billingCycle, status). When the subscription is\nCancelled or Once-billed, nextBillingOn becomes null.").unwrap().omit({ 'nextBillingOn': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'deleted': true,'externalRef': true })

export const apiServiceSubscriptionsIdPatchMutationResponseSchema = z.lazy(() => apiServiceSubscriptionsIdPatch200Schema)