/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTasksIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Task identifier")
    })

/**
 * @description Task resource deleted
 */
export const apiTasksIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiTasksIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTasksIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTasksIdDeleteMutationResponseSchema = z.lazy(() => apiTasksIdDelete204Schema)