/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskDependencyJsonldSchema } from "./taskDependency/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskDependenciesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("TaskDependency identifier")
    })

/**
 * @description TaskDependency resource
 */
export const apiTaskDependenciesIdGet200Schema = z.lazy(() => taskDependencyJsonldSchema).describe("Directional precedence relation between two tasks within the same project.\n\nBeyond awork: we keep `type` (the four classic PM dependency variants) and\n`lagMinutes` so Gantt-style scheduling has the data it needs without a\nschema change later. Cycle detection runs in the controller before persist.")

/**
 * @description Forbidden
 */
export const apiTaskDependenciesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskDependenciesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskDependenciesIdGetQueryResponseSchema = z.lazy(() => apiTaskDependenciesIdGet200Schema)