/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskListEntriesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("TaskListEntry identifier")
    })

/**
 * @description TaskListEntry resource deleted
 */
export const apiTaskListEntriesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiTaskListEntriesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskListEntriesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskListEntriesIdDeleteMutationResponseSchema = z.lazy(() => apiTaskListEntriesIdDelete204Schema)