/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskViewsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("TaskView identifier")
    })

/**
 * @description TaskView resource deleted
 */
export const apiTaskViewsIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiTaskViewsIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskViewsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskViewsIdDeleteMutationResponseSchema = z.lazy(() => apiTaskViewsIdDelete204Schema)