/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { typeOfWorkJsonldSchema } from "./typeOfWork/jsonldSchema.ts";
import { typeOfWorkSchema } from "./typeOfWorkSchema.ts";
import { z } from "zod/v4";

/**
 * @description TypeOfWork resource created
 */
export const apiTypesOfWorkPost201Schema = z.lazy(() => typeOfWorkJsonldSchema).describe("Classification of time entries — \"Development\", \"Project Management\",\n\"Client Meeting\", \"Travel\", etc.\n\nBeyond awork: we add isBillableByDefault here so creating a TimeEntry of\ntype \"Travel\" can default isBillable=false without the user setting it\neach time. Reports can also break down billable vs non-billable hours\nby type-of-work.")

/**
 * @description Invalid input
 */
export const apiTypesOfWorkPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTypesOfWorkPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTypesOfWorkPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new TypeOfWork resource
 */
export const apiTypesOfWorkPostMutationRequestSchema = z.lazy(() => typeOfWorkSchema).describe("Classification of time entries — \"Development\", \"Project Management\",\n\"Client Meeting\", \"Travel\", etc.\n\nBeyond awork: we add isBillableByDefault here so creating a TimeEntry of\ntype \"Travel\" can default isBillable=false without the user setting it\neach time. Reports can also break down billable vs non-billable hours\nby type-of-work.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true,'billableByDefault': true,'archived': true,'externalRef': true })

export const apiTypesOfWorkPostMutationResponseSchema = z.lazy(() => apiTypesOfWorkPost201Schema)