/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { timeTrackingSettingsJsonMergePatchSchema } from "./timeTrackingSettings/jsonMergePatchSchema.ts";
import { timeTrackingSettingsJsonldSchema } from "./timeTrackingSettings/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTimeTrackingSettingsIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("TimeTrackingSettings identifier")
    })

/**
 * @description TimeTrackingSettings resource updated
 */
export const apiTimeTrackingSettingsIdPatch200Schema = z.lazy(() => timeTrackingSettingsJsonldSchema).describe("Workspace-scoped time-tracking configuration. One row per workspace\n(UNIQUE workspace_id) — clients PATCH the singleton to tune behaviour:\n\n  - roundingMinutes:  when a TimeEntry is saved, its duration is rounded\n                      UP to the nearest N minutes (0 = no rounding).\n                      Common settings: 5, 15, 30.\n  - minimumMinutes:   floor for any newly-tracked entry (0 = no floor).\n                      Useful for \"always book at least 15 minutes\" rules.\n  - lockAfterDays:    once a TimeEntry is older than N days, it's marked\n                      isLocked and the author can no longer change it\n                      (closed accounting periods). null disables the\n                      auto-lock.\n  - allowFutureEntries: defaults to false — refuses startsAt > now.\n\nThe rounding policy is applied by {@see TimeTrackingPolicy::apply()} at\npersist time; the lock policy by a scheduled command that walks aged rows.")

/**
 * @description Invalid input
 */
export const apiTimeTrackingSettingsIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTimeTrackingSettingsIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTimeTrackingSettingsIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTimeTrackingSettingsIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated TimeTrackingSettings resource
 */
export const apiTimeTrackingSettingsIdPatchMutationRequestSchema = z.lazy(() => timeTrackingSettingsJsonMergePatchSchema).describe("Workspace-scoped time-tracking configuration. One row per workspace\n(UNIQUE workspace_id) — clients PATCH the singleton to tune behaviour:\n\n  - roundingMinutes:  when a TimeEntry is saved, its duration is rounded\n                      UP to the nearest N minutes (0 = no rounding).\n                      Common settings: 5, 15, 30.\n  - minimumMinutes:   floor for any newly-tracked entry (0 = no floor).\n                      Useful for \"always book at least 15 minutes\" rules.\n  - lockAfterDays:    once a TimeEntry is older than N days, it's marked\n                      isLocked and the author can no longer change it\n                      (closed accounting periods). null disables the\n                      auto-lock.\n  - allowFutureEntries: defaults to false — refuses startsAt > now.\n\nThe rounding policy is applied by {@see TimeTrackingPolicy::apply()} at\npersist time; the lock policy by a scheduled command that walks aged rows.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiTimeTrackingSettingsIdPatchMutationResponseSchema = z.lazy(() => apiTimeTrackingSettingsIdPatch200Schema)