/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskDependencyJsonldSchema } from "./taskDependency/jsonldSchema.ts";
import { taskDependencySchema } from "./taskDependencySchema.ts";
import { z } from "zod/v4";

/**
 * @description TaskDependency resource created
 */
export const apiTaskDependenciesPost201Schema = z.lazy(() => taskDependencyJsonldSchema).describe("Directional precedence relation between two tasks within the same project.\n\nBeyond awork: we keep `type` (the four classic PM dependency variants) and\n`lagMinutes` so Gantt-style scheduling has the data it needs without a\nschema change later. Cycle detection runs in the controller before persist.")

/**
 * @description Invalid input
 */
export const apiTaskDependenciesPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTaskDependenciesPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTaskDependenciesPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new TaskDependency resource
 */
export const apiTaskDependenciesPostMutationRequestSchema = z.lazy(() => taskDependencySchema).describe("Directional precedence relation between two tasks within the same project.\n\nBeyond awork: we keep `type` (the four classic PM dependency variants) and\n`lagMinutes` so Gantt-style scheduling has the data it needs without a\nschema change later. Cycle detection runs in the controller before persist.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiTaskDependenciesPostMutationResponseSchema = z.lazy(() => apiTaskDependenciesPost201Schema)