/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { taskJsonldSchema } from "./task/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTasksGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"identifier": z.optional(z.string()),
"identifier[]": z.optional(z.array(z.string())),
"title": z.optional(z.string()),
"description": z.optional(z.string()),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"project": z.optional(z.string()),
"project[]": z.optional(z.array(z.string())),
"status": z.optional(z.string()),
"status[]": z.optional(z.array(z.string())),
"priority": z.optional(z.string()),
"priority[]": z.optional(z.array(z.string())),
"assignees": z.optional(z.string()),
"assignees[]": z.optional(z.array(z.string())),
"createdBy": z.optional(z.string()),
"createdBy[]": z.optional(z.array(z.string())),
"parent": z.optional(z.string()),
"parent[]": z.optional(z.array(z.string())),
"tags": z.optional(z.string()),
"tags[]": z.optional(z.array(z.string())),
"dueOn[before]": z.optional(z.string()),
"dueOn[strictly_before]": z.optional(z.string()),
"dueOn[after]": z.optional(z.string()),
"dueOn[strictly_after]": z.optional(z.string()),
"startedOn[before]": z.optional(z.string()),
"startedOn[strictly_before]": z.optional(z.string()),
"startedOn[after]": z.optional(z.string()),
"startedOn[strictly_after]": z.optional(z.string()),
"closedOn[before]": z.optional(z.string()),
"closedOn[strictly_before]": z.optional(z.string()),
"closedOn[after]": z.optional(z.string()),
"closedOn[strictly_after]": z.optional(z.string()),
"createdAt[before]": z.optional(z.string()),
"createdAt[strictly_before]": z.optional(z.string()),
"createdAt[after]": z.optional(z.string()),
"createdAt[strictly_after]": z.optional(z.string()),
"updatedAt[before]": z.optional(z.string()),
"updatedAt[strictly_before]": z.optional(z.string()),
"updatedAt[after]": z.optional(z.string()),
"updatedAt[strictly_after]": z.optional(z.string()),
"exists[deletedAt]": z.optional(z.boolean()),
"exists[dueOn]": z.optional(z.boolean()),
"exists[parent]": z.optional(z.boolean()),
"exists[closedOn]": z.optional(z.boolean()),
"isPrio": z.optional(z.boolean()),
"isHiddenForConnectUsers": z.optional(z.boolean()),
"order[identifier]": z.enum(["asc", "desc"]).default("asc"),
"order[title]": z.enum(["asc", "desc"]).default("asc"),
"order[priority]": z.enum(["asc", "desc"]).default("asc"),
"order[position]": z.enum(["asc", "desc"]).default("asc"),
"order[dueOn]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc"),
"order[updatedAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description Task collection
 */
export const apiTasksGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(taskJsonldSchema)
              }
    })).describe("Task.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiTasksGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTasksGetCollectionQueryResponseSchema = z.lazy(() => apiTasksGetCollection200Schema)