/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { trackerJsonldSchema } from "./tracker/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTrackersIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Tracker identifier")
    })

/**
 * @description Tracker resource
 */
export const apiTrackersIdGet200Schema = z.lazy(() => trackerJsonldSchema).describe("Issue tracker classification — Bug, Feature, Story, Support, Epic, …\n\nA Tracker is the \"issue type\" axis on top of TaskStatus (the lifecycle\naxis) and TaskPriority (the urgency axis). It tells the SPA which\nicon + color to show, lets reports group by issue type, and (in\nPhase B Schicht-2) drives the workflow-per-tracker engine.\n\nWorkspace-scoped + name-unique. Trackers are seeded per workspace\nduring onboarding (a fixture provides the four classic ones) and can\nbe edited / extended later from /workspace-settings/trackers.\n\n`isDefault=true` marks the tracker assigned to brand-new tasks when\nthe caller doesn't specify one. Exactly one default per workspace —\nenforced by a Symfony validator (not a DB unique constraint, so a\nbrief \"two defaults in transit\" state during a re-assignment doesn't\ndeadlock the UI).\n\n`defaultStatus` lets a Bug start in a different status than a Story\nif a workspace wants that. Nullable — if unset, the workspace's\nisDefault TaskStatus wins.\n\nHard-delete is allowed but blocked at the DB level (`onDelete: RESTRICT`\non Task.tracker) when any task still references it; the SPA should\noffer \"reassign all tasks of this tracker to X\" first.")

/**
 * @description Not found
 */
export const apiTrackersIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTrackersIdGetQueryResponseSchema = z.lazy(() => apiTrackersIdGet200Schema)