/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskTemplateJsonldSchema } from "./taskTemplate/jsonldSchema.ts";
import { taskTemplateSchema } from "./taskTemplateSchema.ts";
import { z } from "zod/v4";

/**
 * @description TaskTemplate resource created
 */
export const apiTaskTemplatesPost201Schema = z.lazy(() => taskTemplateJsonldSchema).describe("Template for a Task — lives inside a TaskBundle. When the bundle is\napplied to a project (or pulled in via instantiate-from-ProjectTemplate),\neach TaskTemplate becomes a real Task with these defaults filled in and\neverything else (assignee, dueDate, status) reset to project defaults.\n\n`dueDayOffset` is days from the project start; the instantiator computes\n`dueOn = project.startsOn + dueDayOffset` (or `null` if startsOn is null).\n`parent` enables one-level subtask templates inside the same bundle.")

/**
 * @description Invalid input
 */
export const apiTaskTemplatesPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTaskTemplatesPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTaskTemplatesPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new TaskTemplate resource
 */
export const apiTaskTemplatesPostMutationRequestSchema = z.lazy(() => taskTemplateSchema).describe("Template for a Task — lives inside a TaskBundle. When the bundle is\napplied to a project (or pulled in via instantiate-from-ProjectTemplate),\neach TaskTemplate becomes a real Task with these defaults filled in and\neverything else (assignee, dueDate, status) reset to project defaults.\n\n`dueDayOffset` is days from the project start; the instantiator computes\n`dueOn = project.startsOn + dueDayOffset` (or `null` if startsOn is null).\n`parent` enables one-level subtask templates inside the same bundle.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiTaskTemplatesPostMutationResponseSchema = z.lazy(() => apiTaskTemplatesPost201Schema)