/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskViewJsonldSchema } from "./taskView/jsonldSchema.ts";
import { taskViewSchema } from "./taskViewSchema.ts";
import { z } from "zod/v4";

/**
 * @description TaskView resource created
 */
export const apiTaskViewsPost201Schema = z.lazy(() => taskViewJsonldSchema).describe("Persisted task-list filter the user keeps coming back to (\"Open bugs\",\n\"My tasks due this week\", \"Sprint backlog\"). Captures the query as JSON\nso the UI can re-apply it without rebuilding the filter chip-by-chip.\n\nisShared flips it from private to workspace-wide. We skip awork's\nsubscribe/unsubscribe sub-resource — a shared view is simply visible\nto every workspace member; clients keep \"their views\" by filtering\nthe list with ?owner=<me>.")

/**
 * @description Invalid input
 */
export const apiTaskViewsPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTaskViewsPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTaskViewsPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new TaskView resource
 */
export const apiTaskViewsPostMutationRequestSchema = z.lazy(() => taskViewSchema).describe("Persisted task-list filter the user keeps coming back to (\"Open bugs\",\n\"My tasks due this week\", \"Sprint backlog\"). Captures the query as JSON\nso the UI can re-apply it without rebuilding the filter chip-by-chip.\n\nisShared flips it from private to workspace-wide. We skip awork's\nsubscribe/unsubscribe sub-resource — a shared view is simply visible\nto every workspace member; clients keep \"their views\" by filtering\nthe list with ?owner=<me>.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true,'shared': true })

export const apiTaskViewsPostMutationResponseSchema = z.lazy(() => apiTaskViewsPost201Schema)