/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskJsonldSchema } from "./task/jsonldSchema.ts";
import { taskSchema } from "./taskSchema.ts";
import { z } from "zod/v4";

/**
 * @description Task resource created
 */
export const apiTasksPost201Schema = z.lazy(() => taskJsonldSchema)

/**
 * @description Invalid input
 */
export const apiTasksPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTasksPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTasksPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new Task resource
 */
export const apiTasksPostMutationRequestSchema = z.lazy(() => taskSchema).unwrap().omit({ 'listEntries': true,'checklistItems': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'checklistItemsCount': true,'checklistItemsDoneCount': true,'primaryAssignee': true,'prio': true,'hiddenForConnectUsers': true,'deleted': true,'externalRef': true })

export const apiTasksPostMutationResponseSchema = z.lazy(() => apiTasksPost201Schema)