/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskDependenciesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("TaskDependency identifier")
    })

/**
 * @description TaskDependency resource deleted
 */
export const apiTaskDependenciesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiTaskDependenciesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskDependenciesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskDependenciesIdDeleteMutationResponseSchema = z.lazy(() => apiTaskDependenciesIdDelete204Schema)