/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskListEntryJsonldSchema } from "./taskListEntry/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskListEntriesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("TaskListEntry identifier")
    })

/**
 * @description TaskListEntry resource
 */
export const apiTaskListEntriesIdGet200Schema = z.lazy(() => taskListEntryJsonldSchema).describe("Membership of a Task in a TaskList, with per-list ordering.\n\nModelled as an explicit join entity (rather than a plain ManyToMany\njunction) so each placement carries its own ordering — moving a task\nbetween lists doesn't lose its position in the others.\n\nUnique constraint on (list, task) prevents the same task being added\nto the same list twice.")

/**
 * @description Forbidden
 */
export const apiTaskListEntriesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskListEntriesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskListEntriesIdGetQueryResponseSchema = z.lazy(() => apiTaskListEntriesIdGet200Schema)