/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTrackersIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Tracker identifier")
    })

/**
 * @description Tracker resource deleted
 */
export const apiTrackersIdDelete204Schema = z.unknown()

/**
 * @description Not found
 */
export const apiTrackersIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTrackersIdDeleteMutationResponseSchema = z.lazy(() => apiTrackersIdDelete204Schema)