/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { taskListEntryJsonldSchema } from "./taskListEntry/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskListEntriesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"list": z.optional(z.string()),
"list[]": z.optional(z.array(z.string())),
"task": z.optional(z.string()),
"task[]": z.optional(z.array(z.string())),
"order[position]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description TaskListEntry collection
 */
export const apiTaskListEntriesGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(taskListEntryJsonldSchema.describe("Membership of a Task in a TaskList, with per-list ordering.\n\nModelled as an explicit join entity (rather than a plain ManyToMany\njunction) so each placement carries its own ordering — moving a task\nbetween lists doesn't lose its position in the others.\n\nUnique constraint on (list, task) prevents the same task being added\nto the same list twice."))
              }
    })).describe("TaskListEntry.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiTaskListEntriesGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskListEntriesGetCollectionQueryResponseSchema = z.lazy(() => apiTaskListEntriesGetCollection200Schema)