/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskBundleJsonldSchema } from "./taskBundle/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskBundlesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("TaskBundle identifier")
    })

/**
 * @description TaskBundle resource
 */
export const apiTaskBundlesIdGet200Schema = z.lazy(() => taskBundleJsonldSchema).describe("Reusable group of TaskTemplates. Bundles are the unit that gets \"applied\"\nto a project (via apply-bundle) and the building block ProjectTemplate\nuses to define what tasks come with a new project.\n\nMirrors awork's TaskBundle category — they call this \"the 29-op heavy\" but\n80% of those ops are CRUD on the nested TaskTemplate; our flat /v1/task_templates\ncollection covers it with workspace-aware filters.")

/**
 * @description Forbidden
 */
export const apiTaskBundlesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskBundlesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskBundlesIdGetQueryResponseSchema = z.lazy(() => apiTaskBundlesIdGet200Schema)