/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskBundlesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("TaskBundle identifier")
    })

/**
 * @description TaskBundle resource deleted
 */
export const apiTaskBundlesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiTaskBundlesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTaskBundlesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskBundlesIdDeleteMutationResponseSchema = z.lazy(() => apiTaskBundlesIdDelete204Schema)