/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { typeOfWorkJsonldSchema } from "./typeOfWork/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTypesOfWorkIdGetPathParamsSchema = z.object({
    "id": z.string().describe("TypeOfWork identifier")
    })

/**
 * @description TypeOfWork resource
 */
export const apiTypesOfWorkIdGet200Schema = z.lazy(() => typeOfWorkJsonldSchema).describe("Classification of time entries — \"Development\", \"Project Management\",\n\"Client Meeting\", \"Travel\", etc.\n\nBeyond awork: we add isBillableByDefault here so creating a TimeEntry of\ntype \"Travel\" can default isBillable=false without the user setting it\neach time. Reports can also break down billable vs non-billable hours\nby type-of-work.")

/**
 * @description Forbidden
 */
export const apiTypesOfWorkIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTypesOfWorkIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTypesOfWorkIdGetQueryResponseSchema = z.lazy(() => apiTypesOfWorkIdGet200Schema)