/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { taskListJsonldSchema } from "./taskList/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskListsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"project": z.optional(z.string()),
"project[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"isArchived": z.optional(z.boolean()),
"isHiddenForConnectUsers": z.optional(z.boolean()),
"order[position]": z.enum(["asc", "desc"]).default("asc"),
"order[name]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description TaskList collection
 */
export const apiTaskListsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(taskListJsonldSchema.describe("Kanban-style \"lane\" / \"column\" inside a Project. Mirrors awork's TaskList:\na Task can sit in MULTIPLE TaskLists (e.g. one Kanban view per quarter +\none priority view) — membership + per-list ordering live in TaskListEntry.\n\nVoter delegates to the parent Project: anyone with VIEW on the Project\nsees the list; EDIT to mutate."))
              }
    })).describe("TaskList.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiTaskListsGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskListsGetCollectionQueryResponseSchema = z.lazy(() => apiTaskListsGetCollection200Schema)