/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { taskTemplateJsonldSchema } from "./taskTemplate/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTaskTemplatesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"bundle": z.optional(z.string()),
"bundle[]": z.optional(z.array(z.string())),
"title": z.optional(z.string()),
"priority": z.optional(z.string()),
"priority[]": z.optional(z.array(z.string())),
"order[position]": z.enum(["asc", "desc"]).default("asc"),
"order[title]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description TaskTemplate collection
 */
export const apiTaskTemplatesGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(taskTemplateJsonldSchema.describe("Template for a Task — lives inside a TaskBundle. When the bundle is\napplied to a project (or pulled in via instantiate-from-ProjectTemplate),\neach TaskTemplate becomes a real Task with these defaults filled in and\neverything else (assignee, dueDate, status) reset to project defaults.\n\n`dueDayOffset` is days from the project start; the instantiator computes\n`dueOn = project.startsOn + dueDayOffset` (or `null` if startsOn is null).\n`parent` enables one-level subtask templates inside the same bundle."))
              }
    })).describe("TaskTemplate.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiTaskTemplatesGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiTaskTemplatesGetCollectionQueryResponseSchema = z.lazy(() => apiTaskTemplatesGetCollection200Schema)