/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { taskBundleJsonldSchema } from "./taskBundle/jsonldSchema.ts";
import { taskBundleSchema } from "./taskBundleSchema.ts";
import { z } from "zod/v4";

/**
 * @description TaskBundle resource created
 */
export const apiTaskBundlesPost201Schema = z.lazy(() => taskBundleJsonldSchema).describe("Reusable group of TaskTemplates. Bundles are the unit that gets \"applied\"\nto a project (via apply-bundle) and the building block ProjectTemplate\nuses to define what tasks come with a new project.\n\nMirrors awork's TaskBundle category — they call this \"the 29-op heavy\" but\n80% of those ops are CRUD on the nested TaskTemplate; our flat /v1/task_templates\ncollection covers it with workspace-aware filters.")

/**
 * @description Invalid input
 */
export const apiTaskBundlesPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTaskBundlesPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTaskBundlesPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new TaskBundle resource
 */
export const apiTaskBundlesPostMutationRequestSchema = z.lazy(() => taskBundleSchema).describe("Reusable group of TaskTemplates. Bundles are the unit that gets \"applied\"\nto a project (via apply-bundle) and the building block ProjectTemplate\nuses to define what tasks come with a new project.\n\nMirrors awork's TaskBundle category — they call this \"the 29-op heavy\" but\n80% of those ops are CRUD on the nested TaskTemplate; our flat /v1/task_templates\ncollection covers it with workspace-aware filters.").unwrap().omit({ 'taskTemplates': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'archived': true,'deleted': true })

export const apiTaskBundlesPostMutationResponseSchema = z.lazy(() => apiTaskBundlesPost201Schema)