/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { timeEntryJsonMergePatchSchema } from "./timeEntry/jsonMergePatchSchema.ts";
import { timeEntryJsonldSchema } from "./timeEntry/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiTimeEntriesIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("TimeEntry identifier")
    })

/**
 * @description TimeEntry resource updated
 */
export const apiTimeEntriesIdPatch200Schema = z.lazy(() => timeEntryJsonldSchema)

/**
 * @description Invalid input
 */
export const apiTimeEntriesIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiTimeEntriesIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiTimeEntriesIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiTimeEntriesIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated TimeEntry resource
 */
export const apiTimeEntriesIdPatchMutationRequestSchema = z.lazy(() => timeEntryJsonMergePatchSchema).unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true,'billed': true,'billable': true,'locked': true,'external': true,'running': true,'externalRef': true })

export const apiTimeEntriesIdPatchMutationResponseSchema = z.lazy(() => apiTimeEntriesIdPatch200Schema)