/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { userContactInfoJsonldSchema } from "./userContactInfo/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiUserContactInfosGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"user": z.optional(z.string()),
"user[]": z.optional(z.array(z.string())),
"type": z.optional(z.string()),
"type[]": z.optional(z.array(z.string())),
"subType": z.optional(z.string()),
"subType[]": z.optional(z.array(z.string())),
"value": z.optional(z.string())
    })

/**
 * @description UserContactInfo collection
 */
export const apiUserContactInfosGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(userContactInfoJsonldSchema.describe("Additional contact channels for a User — phone, alternative email,\npostal address. Multiple rows per user; type+subType + label distinguish\n\"work mobile\" from \"private mobile\" from \"billing address\".\n\nMatches awork's UserContactInfo array nested inside the User response."))
              }
    })).describe("UserContactInfo.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiUserContactInfosGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiUserContactInfosGetCollectionQueryResponseSchema = z.lazy(() => apiUserContactInfosGetCollection200Schema)