/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiUsersIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("User identifier")
    })

/**
 * @description User resource deleted
 */
export const apiUsersIdDelete204Schema = z.unknown()

/**
 * @description Not found
 */
export const apiUsersIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiUsersIdDeleteMutationResponseSchema = z.lazy(() => apiUsersIdDelete204Schema)