/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { userCapacityJsonldSchema } from "./userCapacity/jsonldSchema.ts";
import { userCapacitySchema } from "./userCapacitySchema.ts";
import { z } from "zod/v4";

/**
 * @description UserCapacity resource created
 */
export const apiUserCapacitiesPost201Schema = z.lazy(() => userCapacityJsonldSchema).describe("Per-user weekly working capacity in MINUTES per weekday. Replaces awork's\n`UserWeeklyCapacity` object — flattened into the row so reporting queries\ndon't need to join an embedded.\n\nOne row per user, enforced by the unique constraint on user_id. Default\n= 0 minutes everywhere; UI should pre-fill 480 (8h) on weekdays for new\nusers.")

/**
 * @description Invalid input
 */
export const apiUserCapacitiesPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiUserCapacitiesPost403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiUserCapacitiesPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new UserCapacity resource
 */
export const apiUserCapacitiesPostMutationRequestSchema = z.lazy(() => userCapacitySchema).describe("Per-user weekly working capacity in MINUTES per weekday. Replaces awork's\n`UserWeeklyCapacity` object — flattened into the row so reporting queries\ndon't need to join an embedded.\n\nOne row per user, enforced by the unique constraint on user_id. Default\n= 0 minutes everywhere; UI should pre-fill 480 (8h) on weekdays for new\nusers.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true,'weeklyMinutes': true })

export const apiUserCapacitiesPostMutationResponseSchema = z.lazy(() => apiUserCapacitiesPost201Schema)