/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { userJsonMergePatchSchema } from "./user/jsonMergePatchSchema.ts";
import { userJsonldSchema } from "./user/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiUsersIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("User identifier")
    })

/**
 * @description User resource updated
 */
export const apiUsersIdPatch200Schema = z.lazy(() => userJsonldSchema)

/**
 * @description Invalid input
 */
export const apiUsersIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiUsersIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiUsersIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated User resource
 */
export const apiUsersIdPatchMutationRequestSchema = z.lazy(() => userJsonMergePatchSchema).unwrap().omit({ 'workspaceMemberships': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'userIdentifier': true,'fullName': true,'deleted': true,'externalRef': true })

export const apiUsersIdPatchMutationResponseSchema = z.lazy(() => apiUsersIdPatch200Schema)