/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { userJsonldSchema } from "./user/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiUsersGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"email": z.optional(z.string()),
"firstName": z.optional(z.string()),
"lastName": z.optional(z.string()),
"order[email]": z.enum(["asc", "desc"]).default("asc"),
"order[lastName]": z.enum(["asc", "desc"]).default("asc"),
"order[firstName]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc"),
"order[lastLoginAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description User collection
 */
export const apiUsersGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(userJsonldSchema)
              }
    })).describe("User.jsonld collection.")

export const apiUsersGetCollectionQueryResponseSchema = z.lazy(() => apiUsersGetCollection200Schema)