/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { userContactInfoJsonMergePatchSchema } from "./userContactInfo/jsonMergePatchSchema.ts";
import { userContactInfoJsonldSchema } from "./userContactInfo/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiUserContactInfosIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("UserContactInfo identifier")
    })

/**
 * @description UserContactInfo resource updated
 */
export const apiUserContactInfosIdPatch200Schema = z.lazy(() => userContactInfoJsonldSchema).describe("Additional contact channels for a User — phone, alternative email,\npostal address. Multiple rows per user; type+subType + label distinguish\n\"work mobile\" from \"private mobile\" from \"billing address\".\n\nMatches awork's UserContactInfo array nested inside the User response.")

/**
 * @description Invalid input
 */
export const apiUserContactInfosIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiUserContactInfosIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiUserContactInfosIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiUserContactInfosIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated UserContactInfo resource
 */
export const apiUserContactInfosIdPatchMutationRequestSchema = z.lazy(() => userContactInfoJsonMergePatchSchema).describe("Additional contact channels for a User — phone, alternative email,\npostal address. Multiple rows per user; type+subType + label distinguish\n\"work mobile\" from \"private mobile\" from \"billing address\".\n\nMatches awork's UserContactInfo array nested inside the User response.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiUserContactInfosIdPatchMutationResponseSchema = z.lazy(() => apiUserContactInfosIdPatch200Schema)