/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { userJsonldSchema } from "./user/jsonldSchema.ts";
import { userSchema } from "./userSchema.ts";
import { z } from "zod/v4";

/**
 * @description User resource created
 */
export const apiUsersPost201Schema = z.lazy(() => userJsonldSchema)

/**
 * @description Invalid input
 */
export const apiUsersPost400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiUsersPost422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The new User resource
 */
export const apiUsersPostMutationRequestSchema = z.lazy(() => userSchema).unwrap().omit({ 'workspaceMemberships': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'userIdentifier': true,'fullName': true,'deleted': true,'externalRef': true })

export const apiUsersPostMutationResponseSchema = z.lazy(() => apiUsersPost201Schema)