/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { workspaceInvitationJsonldSchema } from "./workspaceInvitation/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspaceInvitationsIdGetPathParamsSchema = z.object({
    "id": z.string().describe("WorkspaceInvitation identifier")
    })

/**
 * @description WorkspaceInvitation resource
 */
export const apiWorkspaceInvitationsIdGet200Schema = z.lazy(() => workspaceInvitationJsonldSchema).describe("Workspace invitation: an owner/admin types an email + role, this entity\nstores a unique opaque accept-token, and the invitee turns into a\nWorkspaceMember once they hit POST /v1/workspace_invitations/{token}/accept.\n\nFlow:\n  POST /v1/workspace_invitations    →  status=pending, token returned ONCE\n  POST .../{token}/accept           →  creates User if needed, links membership\n                                       with the chosen role, status=accepted\n  DELETE /v1/workspace_invitations/{id}  →  revokes a pending invite\n\nThe token plaintext is shown only in the creation response so the operator\ncan ship a magic link to the invitee. After that, the DB column is the\nopaque value we compare against incoming accepts (no hashing here — the\nthreat model is leaked email content, not a leaked DB dump; the token's\nvalue is its unguessability, and acceptance permanently consumes it).\n\nRole validation prevents creating Owner invitations — workspace owners are\nset by the workspace-creation flow, not handed out on email.")

/**
 * @description Forbidden
 */
export const apiWorkspaceInvitationsIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWorkspaceInvitationsIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkspaceInvitationsIdGetQueryResponseSchema = z.lazy(() => apiWorkspaceInvitationsIdGet200Schema)