/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { workspaceMemberJsonldSchema } from "./workspaceMember/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspaceMembersIdGetPathParamsSchema = z.object({
    "id": z.string().describe("WorkspaceMember identifier")
    })

/**
 * @description WorkspaceMember resource
 */
export const apiWorkspaceMembersIdGet200Schema = z.lazy(() => workspaceMemberJsonldSchema)

/**
 * @description Not found
 */
export const apiWorkspaceMembersIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkspaceMembersIdGetQueryResponseSchema = z.lazy(() => apiWorkspaceMembersIdGet200Schema)