/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkflowTransitionsIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("WorkflowTransition identifier")
    })

/**
 * @description WorkflowTransition resource deleted
 */
export const apiWorkflowTransitionsIdDelete204Schema = z.unknown()

/**
 * @description Not found
 */
export const apiWorkflowTransitionsIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkflowTransitionsIdDeleteMutationResponseSchema = z.lazy(() => apiWorkflowTransitionsIdDelete204Schema)