/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { workflowJsonMergePatchSchema } from "./workflow/jsonMergePatchSchema.ts";
import { workflowJsonldSchema } from "./workflow/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkflowsIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("Workflow identifier")
    })

/**
 * @description Workflow resource updated
 */
export const apiWorkflowsIdPatch200Schema = z.lazy(() => workflowJsonldSchema).describe("Workflow = named process template, linked to N projects. Holds N\nAutomations (when-then rules) that fire on domain events emitted by\nany project bound to this workflow.\n\nLinked from Project.workflow (nullable). awork also allows linking from\nProjectTemplate so instantiated projects inherit it — that comes later.")

/**
 * @description Invalid input
 */
export const apiWorkflowsIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiWorkflowsIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWorkflowsIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiWorkflowsIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated Workflow resource
 */
export const apiWorkflowsIdPatchMutationRequestSchema = z.lazy(() => workflowJsonMergePatchSchema).describe("Workflow = named process template, linked to N projects. Holds N\nAutomations (when-then rules) that fire on domain events emitted by\nany project bound to this workflow.\n\nLinked from Project.workflow (nullable). awork also allows linking from\nProjectTemplate so instantiated projects inherit it — that comes later.").unwrap().omit({ 'automations': true,'id': true,'createdAt': true,'updatedAt': true,'deletedAt': true,'version': true,'enabled': true,'archived': true,'deleted': true })

export const apiWorkflowsIdPatchMutationResponseSchema = z.lazy(() => apiWorkflowsIdPatch200Schema)