/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspaceMembersIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("WorkspaceMember identifier")
    })

/**
 * @description WorkspaceMember resource deleted
 */
export const apiWorkspaceMembersIdDelete204Schema = z.unknown()

/**
 * @description Not found
 */
export const apiWorkspaceMembersIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkspaceMembersIdDeleteMutationResponseSchema = z.lazy(() => apiWorkspaceMembersIdDelete204Schema)