/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { watchJsonldSchema } from "./watch/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWatchesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("Watch identifier")
    })

/**
 * @description Watch resource
 */
export const apiWatchesIdGet200Schema = z.lazy(() => watchJsonldSchema).describe("A user subscribed to notifications on a polymorphic target.\n\nModelled identical to {@see Comment}: `target` enum + `targetId` UUID,\none row per (workspace, target, targetId, user) tuple — enforced by a\nunique index so subscribe is idempotent (POST twice is fine, never\nproduces duplicates).\n\nInspired by Redmine's `watchers` table (polymorphic `watchable_type` +\n`watchable_id`, see ~/ddev/bluemine/symfony/src/Entity/Watcher.php).\n\nNotifications themselves are out of scope here — this entity only\nkeeps the subscription list. A future MessageHandler will iterate the\nwatchers when a tracked DomainEvent fires.\n\nGET-collection is permissive (any ROLE_USER can list to render the\n\"Watching\" badge on a card); mutations go through the WatchActions\ncontroller's toggle endpoint so the route IS the authorisation\n(always operates on the current user's own subscriptions).")

/**
 * @description Forbidden
 */
export const apiWatchesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWatchesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWatchesIdGetQueryResponseSchema = z.lazy(() => apiWatchesIdGet200Schema)