/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { workspaceAbsenceJsonldSchema } from "./workspaceAbsence/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspaceAbsencesIdGetPathParamsSchema = z.object({
    "id": z.string().describe("WorkspaceAbsence identifier")
    })

/**
 * @description WorkspaceAbsence resource
 */
export const apiWorkspaceAbsencesIdGet200Schema = z.lazy(() => workspaceAbsenceJsonldSchema).describe("Workspace-wide non-working day — company holiday, retreat, training day.\nApplies to every member; the absences UI overlays these on top of personal\nAbsences when rendering availability.")

/**
 * @description Forbidden
 */
export const apiWorkspaceAbsencesIdGet403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWorkspaceAbsencesIdGet404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkspaceAbsencesIdGetQueryResponseSchema = z.lazy(() => apiWorkspaceAbsencesIdGet200Schema)