/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { workflowJsonldSchema } from "./workflow/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkflowsGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"isEnabled": z.optional(z.boolean()),
"isArchived": z.optional(z.boolean()),
"order[name]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description Workflow collection
 */
export const apiWorkflowsGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(workflowJsonldSchema.describe("Workflow = named process template, linked to N projects. Holds N\nAutomations (when-then rules) that fire on domain events emitted by\nany project bound to this workflow.\n\nLinked from Project.workflow (nullable). awork also allows linking from\nProjectTemplate so instantiated projects inherit it — that comes later."))
              }
    })).describe("Workflow.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiWorkflowsGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkflowsGetCollectionQueryResponseSchema = z.lazy(() => apiWorkflowsGetCollection200Schema)