/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspacesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Workspace identifier")
    })

/**
 * @description Workspace resource deleted
 */
export const apiWorkspacesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiWorkspacesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWorkspacesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkspacesIdDeleteMutationResponseSchema = z.lazy(() => apiWorkspacesIdDelete204Schema)