/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { webhookDeliveryJsonldSchema } from "./webhookDelivery/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWebhookDeliveriesGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"webhook": z.optional(z.string()),
"webhook[]": z.optional(z.array(z.string())),
"status": z.optional(z.string()),
"status[]": z.optional(z.array(z.string())),
"eventName": z.optional(z.string()),
"order[attemptedAt]": z.enum(["asc", "desc"]).default("asc"),
"order[createdAt]": z.enum(["asc", "desc"]).default("asc")
    })

/**
 * @description WebhookDelivery collection
 */
export const apiWebhookDeliveriesGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(webhookDeliveryJsonldSchema.describe("Single attempt to deliver one DomainEvent to one Webhook. One log row per\n(webhook, event, attempt) — retries get their own row so the timeline is\ncomplete.\n\nRead-only via the API (operators inspect the log; retries happen on the\nMessenger transport's own schedule, not via REST)."))
              }
    })).describe("WebhookDelivery.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiWebhookDeliveriesGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWebhookDeliveriesGetCollectionQueryResponseSchema = z.lazy(() => apiWebhookDeliveriesGetCollection200Schema)