/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { hydraCollectionBaseSchemaSchema } from "./hydraCollectionBaseSchemaSchema.ts";
import { webhookJsonldSchema } from "./webhook/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWebhooksGetCollectionQueryParamsSchema = z.object({
    "page": z.coerce.number().int().default(1).describe("The collection page number"),
"itemsPerPage": z.coerce.number().int().min(0).max(200).default(30).describe("The number of items per page"),
"workspace": z.optional(z.string()),
"workspace[]": z.optional(z.array(z.string())),
"name": z.optional(z.string()),
"isActive": z.optional(z.boolean())
    })

/**
 * @description Webhook collection
 */
export const apiWebhooksGetCollection200Schema = z.lazy(() => hydraCollectionBaseSchemaSchema).and(z.object({
    get "member"(){
                return z.array(webhookJsonldSchema.describe("Subscription that mirrors selected DomainEvents to an external HTTP endpoint.\n\nEach delivery is signed with HMAC-SHA256 over the request body, using `secret`\nas the key; consumers verify by recomputing the digest and comparing it to the\n`X-Worktide-Signature: sha256=…` header.\n\nEvent subscription matches by name:\n  - `[\"*\"]`                  — every event\n  - `[\"task.*\"]`             — every event whose name starts with \"task.\"\n  - `[\"task.created\"]`       — exact name only\n\nThe `secret` is write-only via the API (returned obfuscated on reads) so it\nnever leaks back to clients after creation. `failureCount` and\n`lastTriggeredAt` are server-managed; clients cannot patch them.\n\nAfter {@see self::FAILURE_THRESHOLD} consecutive non-2xx deliveries the\nwebhook auto-deactivates — the operator must inspect the deliveries log and\nre-enable it with a fresh PATCH."))
              }
    })).describe("Webhook.jsonld collection.")

/**
 * @description Forbidden
 */
export const apiWebhooksGetCollection403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWebhooksGetCollectionQueryResponseSchema = z.lazy(() => apiWebhooksGetCollection200Schema)