/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWebhooksIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("Webhook identifier")
    })

/**
 * @description Webhook resource deleted
 */
export const apiWebhooksIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiWebhooksIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWebhooksIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWebhooksIdDeleteMutationResponseSchema = z.lazy(() => apiWebhooksIdDelete204Schema)