/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspaceAbsencesIdDeletePathParamsSchema = z.object({
    "id": z.string().describe("WorkspaceAbsence identifier")
    })

/**
 * @description WorkspaceAbsence resource deleted
 */
export const apiWorkspaceAbsencesIdDelete204Schema = z.unknown()

/**
 * @description Forbidden
 */
export const apiWorkspaceAbsencesIdDelete403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWorkspaceAbsencesIdDelete404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

export const apiWorkspaceAbsencesIdDeleteMutationResponseSchema = z.lazy(() => apiWorkspaceAbsencesIdDelete204Schema)