/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { constraintViolationJsonldSchema } from "./constraintViolation/jsonldSchema.ts";
import { errorJsonldSchema } from "./error/jsonldSchema.ts";
import { workspaceAbsenceJsonMergePatchSchema } from "./workspaceAbsence/jsonMergePatchSchema.ts";
import { workspaceAbsenceJsonldSchema } from "./workspaceAbsence/jsonldSchema.ts";
import { z } from "zod/v4";

export const apiWorkspaceAbsencesIdPatchPathParamsSchema = z.object({
    "id": z.string().describe("WorkspaceAbsence identifier")
    })

/**
 * @description WorkspaceAbsence resource updated
 */
export const apiWorkspaceAbsencesIdPatch200Schema = z.lazy(() => workspaceAbsenceJsonldSchema).describe("Workspace-wide non-working day — company holiday, retreat, training day.\nApplies to every member; the absences UI overlays these on top of personal\nAbsences when rendering availability.")

/**
 * @description Invalid input
 */
export const apiWorkspaceAbsencesIdPatch400Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Forbidden
 */
export const apiWorkspaceAbsencesIdPatch403Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description Not found
 */
export const apiWorkspaceAbsencesIdPatch404Schema = z.lazy(() => errorJsonldSchema).describe("A representation of common errors.")

/**
 * @description An error occurred
 */
export const apiWorkspaceAbsencesIdPatch422Schema = z.lazy(() => constraintViolationJsonldSchema).describe("Unprocessable entity")

/**
 * @description The updated WorkspaceAbsence resource
 */
export const apiWorkspaceAbsencesIdPatchMutationRequestSchema = z.lazy(() => workspaceAbsenceJsonMergePatchSchema).describe("Workspace-wide non-working day — company holiday, retreat, training day.\nApplies to every member; the absences UI overlays these on top of personal\nAbsences when rendering availability.").unwrap().omit({ 'id': true,'createdAt': true,'updatedAt': true,'version': true })

export const apiWorkspaceAbsencesIdPatchMutationResponseSchema = z.lazy(() => apiWorkspaceAbsencesIdPatch200Schema)