/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Unprocessable entity
 */
export const constraintViolationSchema = z.object({
    "status": z.optional(z.int().default(422)),
"violations": z.optional(z.array(z.object({
    "propertyPath": z.string().describe("The property path of the violation"),
"message": z.string().describe("The message associated with the violation"),
"code": z.optional(z.string().describe("The code of the violation")),
"hint": z.optional(z.string().describe("An extra hint to understand the violation")),
"payload": z.optional(z.object({
    
    }).catchall(z.unknown()).describe("The serialized payload of the violation"))
    }))),
"detail": z.optional(z.string()),
"type": z.optional(z.string()),
"title": z.string().nullish(),
"instance": z.string().nullish()
    }).describe("Unprocessable entity")