/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description A concrete system instance the agency runs for a customer — one TYPO3\nmain site, one WordPress blog, one Shopware store. Customers may have\nany number of systems and each system may carry its own\nServiceSubscriptions for hosting / maintenance / SLA.\n\nThe agency cares about three buckets of data here:\n  1. Operational: live + staging URLs, hosting provider, environment\n     label, admin entry-point URL.\n  2. Maintenance: SystemType drives what UI controls and what dashboards\n     apply (a TYPO3-specific health-check page makes no sense on a\n     WordPress instance).\n  3. Notes: a free-form text field for credentials, quirks, contacts.\n     INTENTIONALLY plaintext for now — secret encryption needs a proper\n     KMS story (see roadmap CRM-3). Until then, treat this field as\n     privileged like any other PII / credentials column.\n\nCustomer ↔ Workspace consistency: `workspace` is denormalized from the\ncustomer so voters and filters don\'t always have to join.
 */
export const customerSystemSchema = z.object({
    "customer": z.optional(z.string()),
"name": z.string(),
"type": z.optional(z.enum(["typo3", "wordpress", "drupal", "magento", "shopware", "joomla", "symfony", "laravel", "static", "other"]).default("other")),
"systemVersion": z.string().describe("Optional version tag of the hosted system itself — major release is\nusually enough (\"13\", \"v6.6\"). Named `systemVersion` not `version` to\navoid colliding with VersionedTrait's optimistic-locking column.").nullish(),
"url": z.url().nullish(),
"stagingUrl": z.url().nullish(),
"adminLoginUrl": z.url().nullish(),
"hostingProvider": z.string().nullish(),
"environment": z.optional(z.enum(["production", "staging", "development"]).default("production")),
"credentialsNotes": z.string().nullish(),
"notes": z.string().nullish(),
"isActive": z.optional(z.boolean().default(true)),
"subscriptions": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"active": z.optional(z.boolean()),
"deleted": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    }).describe("A concrete system instance the agency runs for a customer — one TYPO3\nmain site, one WordPress blog, one Shopware store. Customers may have\nany number of systems and each system may carry its own\nServiceSubscriptions for hosting / maintenance / SLA.\n\nThe agency cares about three buckets of data here:\n  1. Operational: live + staging URLs, hosting provider, environment\n     label, admin entry-point URL.\n  2. Maintenance: SystemType drives what UI controls and what dashboards\n     apply (a TYPO3-specific health-check page makes no sense on a\n     WordPress instance).\n  3. Notes: a free-form text field for credentials, quirks, contacts.\n     INTENTIONALLY plaintext for now — secret encryption needs a proper\n     KMS story (see roadmap CRM-3). Until then, treat this field as\n     privileged like any other PII / credentials column.\n\nCustomer ↔ Workspace consistency: `workspace` is denormalized from the\ncustomer so voters and filters don't always have to join.")