/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Container for Documents — equivalent to a Notion/Confluence \"space\" or a\ntop-level sidebar group. Documents can also exist without a space (private\nnotes); when both exist, space ordering wins over project ordering.\n\nPer-space access (contributors / team access) is deferred — for the MVP a\nspace is workspace-wide-readable; the writer-restriction is on the\nDocument itself via DocumentContributor.
 */
export const documentSpaceSchema = z.object({
    "name": z.optional(z.string()),
"description": z.string().nullish(),
"color": z.string().nullish(),
"icon": z.string().nullish(),
"emoji": z.string().describe("Emoji shortcode (or actual emoji) the UI uses as space icon.").nullish(),
"position": z.optional(z.number().default(0)),
"isArchived": z.optional(z.boolean().default(false)),
"documents": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"archived": z.optional(z.boolean()),
"deleted": z.optional(z.boolean())
    }).describe("Container for Documents — equivalent to a Notion/Confluence \"space\" or a\ntop-level sidebar group. Documents can also exist without a space (private\nnotes); when both exist, space ordering wins over project ordering.\n\nPer-space access (contributors / team access) is deferred — for the MVP a\nspace is workspace-wide-readable; the writer-restriction is on the\nDocument itself via DocumentContributor.")