/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Outbox table that records every Worktide-side change to an\nentity that\'s mirrored in at least one external system.\n\nSame pattern as {@see OutboundMessage} for mail: write the\nintent transactionally with the entity change, let a separate\nworker dispatch to the adapters. Decouples the API request\nlatency from the external-system reachability — a slow Jira\nnever blocks a Worktide save.\n\nThe row is fanned out to ALL EntitySync mappings for the\n(entityType, entityId) at processing time, not at write time.\nThat way a mapping added between change and dispatch still\nreceives the update.\n\n`changedFields` + `previousValues` are sparse: only the fields\nthat actually changed in this Doctrine flush. Adapters use this\nto construct minimal PATCH requests and for conflict detection\n(if previousValue !== externalCurrentValue → conflict).\n\nRe-entry guard: the {@see \\App\\Channels\\SyncReentryGuard} flag\nis set while inbound sync writes are being applied; the\nlistener that creates these rows skips writes during that\nwindow so an inbound update doesn\'t bounce right back to the\nsource.
 */
export const entityChangeOutboxSchema = z.object({
    "entityType": z.optional(z.string()),
"entityId": z.optional(z.uuid()),
"changedFields": z.optional(z.object({
    
    }).catchall(z.string().nullable())),
"previousValues": z.optional(z.object({
    
    }).catchall(z.string().nullable())),
"isDelete": z.optional(z.boolean().default(false)),
"status": z.optional(z.enum(["pending", "sending", "sent", "partial", "failed", "conflict", "dead"]).default("pending")),
"attemptCount": z.optional(z.int().default(0)),
"nextAttemptAt": z.optional(z.iso.datetime().describe("Earliest time the worker is allowed to claim this row again.")),
"lastError": z.string().nullish(),
"processedAt": z.iso.datetime().nullish(),
"perMappingState": z.optional(z.object({
    
    }).catchall(z.string().nullable()).describe("Per-mapping outcome — JSON map `entitySyncId → {result, etag,\nexternalUpdatedAt, error}` so the worker can do partial\nretries (only the failed mappings) without re-pushing to the\nadapters that already succeeded.")),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"delete": z.optional(z.boolean())
    }).describe("Outbox table that records every Worktide-side change to an\nentity that's mirrored in at least one external system.\n\nSame pattern as {@see OutboundMessage} for mail: write the\nintent transactionally with the entity change, let a separate\nworker dispatch to the adapters. Decouples the API request\nlatency from the external-system reachability — a slow Jira\nnever blocks a Worktide save.\n\nThe row is fanned out to ALL EntitySync mappings for the\n(entityType, entityId) at processing time, not at write time.\nThat way a mapping added between change and dispatch still\nreceives the update.\n\n`changedFields` + `previousValues` are sparse: only the fields\nthat actually changed in this Doctrine flush. Adapters use this\nto construct minimal PATCH requests and for conflict detection\n(if previousValue !== externalCurrentValue → conflict).\n\nRe-entry guard: the {@see \\App\\Channels\\SyncReentryGuard} flag\nis set while inbound sync writes are being applied; the\nlistener that creates these rows skips writes during that\nwindow so an inbound update doesn't bounce right back to the\nsource.")