/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const fileVersionSchema = z.object({
    "file": z.optional(z.string()),
"versionNumber": z.optional(z.int().default(1)),
"originalFilename": z.optional(z.string().describe("Filename as it was uploaded (UTF-8).")),
"size": z.optional(z.union([z.int(), z.string()]).default("0").describe("Bytes.")),
"mimeType": z.optional(z.string().default("application/octet-stream")),
"checksum": z.optional(z.string().describe("SHA-256 hex of the bytes — integrity + dedup.")),
"storagePath": z.optional(z.string().describe("Flysystem path relative to the configured storage root.")),
"uploadedBy": z.string().nullish(),
"note": z.string().nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime())
    })