/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraCollectionBaseSchemaNoPaginationSchema } from "./hydraCollectionBaseSchemaNoPaginationSchema.ts";
import { z } from "zod/v4";

export const hydraCollectionBaseSchemaSchema = z.lazy(() => hydraCollectionBaseSchemaNoPaginationSchema).and(z.object({
    "view": z.optional(z.object({
    "@id": z.optional(z.string()),
"@type": z.optional(z.string()),
"first": z.string().nullish(),
"last": z.string().nullish(),
"previous": z.string().nullish(),
"next": z.string().nullish()
    }))
    }))