/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description One thing that came in from the outside world. Source-agnostic\nrepresentation that every {@see Channel} adapter writes.\n\nFor mail, one event = one received message. For a webhook, one\nevent = one POST. For an RSS adapter, one event = one new feed\nitem.\n\n`externalId` is whatever the source uses to identify the item\n(Message-ID for mail, Zabbix event-id, webhook delivery-id). The\nUNIQUE(channel, externalId) index makes ingestion idempotent —\npulling the same mailbox twice doesn\'t create duplicates.\n\n`conversationId` is populated for threading-capable adapters via\nthe `ConversationThreader` strategy. For non-threading sources\nit stays NULL and the event is a standalone item.\n\n`body` is normalised plain text or markdown — adapters that\nreceive richer formats (HTML mail, Slack mrkdwn) should also\nstash the original payload in `sourceMetadata.raw` for later\nre-rendering.\n\nSoft-deletion isn\'t applied here on purpose — `state=Dismissed`\nis the soft-delete; the row stays for AI-training and audit.\n\nOperations are read-only (Get/GetCollection) plus PATCH-state.\nCreation goes through the adapter pipeline, not the API.
 */
export const inboundEventSchema = z.object({
    "channel": z.optional(z.string()),
"externalId": z.optional(z.string()),
"senderRaw": z.string().describe("Free-text label for the originator — for mail, the From-header\nvalue verbatim; for slack, the user-display-name. Useful when\nContact resolution didn't yield a match.").nullish(),
"senderContact": z.string().nullish(),
"subject": z.string().describe("Optional first-line summary (mail Subject, slack message\nsnippet). Helps the inbox-list render without loading the\nfull body.").nullish(),
"body": z.string().nullish(),
"attachments": z.optional(z.array(z.object({
    
    }).catchall(z.string().nullable())).describe("Attachments as a list of references — {filename, mimeType,\nsizeBytes, fileIri (when persisted to File entity), externalUrl\n(when held by the source)}. Concrete shape is adapter-defined.")),
"sourceMetadata": z.optional(z.object({
    
    }).catchall(z.string().nullable())),
"traceUrl": z.string().describe("Deep-link back to the message inside the source system if it\nhas a stable URL (Slack permalink, MS Graph webLink). Lets the\nSPA say \"open in Slack\" instead of just rendering our snapshot.").nullish(),
"conversation": z.string().nullish(),
"state": z.optional(z.enum(["pending", "processed", "dismissed"]).default("pending")),
"receivedAt": z.optional(z.iso.datetime()),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish()
    }).describe("One thing that came in from the outside world. Source-agnostic\nrepresentation that every {@see Channel} adapter writes.\n\nFor mail, one event = one received message. For a webhook, one\nevent = one POST. For an RSS adapter, one event = one new feed\nitem.\n\n`externalId` is whatever the source uses to identify the item\n(Message-ID for mail, Zabbix event-id, webhook delivery-id). The\nUNIQUE(channel, externalId) index makes ingestion idempotent —\npulling the same mailbox twice doesn't create duplicates.\n\n`conversationId` is populated for threading-capable adapters via\nthe `ConversationThreader` strategy. For non-threading sources\nit stays NULL and the event is a standalone item.\n\n`body` is normalised plain text or markdown — adapters that\nreceive richer formats (HTML mail, Slack mrkdwn) should also\nstash the original payload in `sourceMetadata.raw` for later\nre-rendering.\n\nSoft-deletion isn't applied here on purpose — `state=Dismissed`\nis the soft-delete; the row stays for AI-training and audit.\n\nOperations are read-only (Get/GetCollection) plus PATCH-state.\nCreation goes through the adapter pipeline, not the API.")