/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Classification of time entries — \"Development\", \"Project Management\",\n\"Client Meeting\", \"Travel\", etc.\n\nBeyond awork: we add isBillableByDefault here so creating a TimeEntry of\ntype \"Travel\" can default isBillable=false without the user setting it\neach time. Reports can also break down billable vs non-billable hours\nby type-of-work.
 */
export const typeOfWorkSchema = z.object({
    "name": z.optional(z.string()),
"description": z.string().nullish(),
"icon": z.string().nullish(),
"color": z.string().nullish(),
"isBillableByDefault": z.optional(z.boolean().default(true)),
"isArchived": z.optional(z.boolean().default(false)),
"position": z.optional(z.int().default(0)),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"externalSource": z.string().nullish(),
"externalId": z.string().nullish(),
"billableByDefault": z.optional(z.boolean()),
"archived": z.optional(z.boolean()),
"externalRef": z.string().nullish()
    }).describe("Classification of time entries — \"Development\", \"Project Management\",\n\"Client Meeting\", \"Travel\", etc.\n\nBeyond awork: we add isBillableByDefault here so creating a TimeEntry of\ntype \"Travel\" can default isBillable=false without the user setting it\neach time. Reports can also break down billable vs non-billable hours\nby type-of-work.")