/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Single attempt to deliver one DomainEvent to one Webhook. One log row per\n(webhook, event, attempt) — retries get their own row so the timeline is\ncomplete.\n\nRead-only via the API (operators inspect the log; retries happen on the\nMessenger transport\'s own schedule, not via REST).
 */
export const webhookDeliverySchema = z.object({
    "webhook": z.optional(z.string()),
"eventId": z.uuid().describe("Snapshot of the source DomainEvent.aggregateId — reference only, no FK to domain_events.").nullish(),
"eventName": z.optional(z.string()),
"status": z.optional(z.enum(["pending", "success", "failure"]).default("pending")),
"httpStatus": z.int().nullish(),
"responseBody": z.string().nullish(),
"errorMessage": z.string().nullish(),
"attempt": z.optional(z.int().default(1)),
"durationMs": z.int().nullish(),
"attemptedAt": z.iso.datetime().nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime())
    }).describe("Single attempt to deliver one DomainEvent to one Webhook. One log row per\n(webhook, event, attempt) — retries get their own row so the timeline is\ncomplete.\n\nRead-only via the API (operators inspect the log; retries happen on the\nMessenger transport's own schedule, not via REST).")