/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Workflow = named process template, linked to N projects. Holds N\nAutomations (when-then rules) that fire on domain events emitted by\nany project bound to this workflow.\n\nLinked from Project.workflow (nullable). awork also allows linking from\nProjectTemplate so instantiated projects inherit it — that comes later.
 */
export const workflowSchema = z.object({
    "name": z.optional(z.string()),
"description": z.string().nullish(),
"color": z.optional(z.string().default("#6366f1")),
"isEnabled": z.optional(z.boolean().default(true)),
"isArchived": z.optional(z.boolean().default(false)),
"automations": z.optional(z.array(z.string())),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"enabled": z.optional(z.boolean()),
"archived": z.optional(z.boolean()),
"deleted": z.optional(z.boolean())
    }).describe("Workflow = named process template, linked to N projects. Holds N\nAutomations (when-then rules) that fire on domain events emitted by\nany project bound to this workflow.\n\nLinked from Project.workflow (nullable). awork also allows linking from\nProjectTemplate so instantiated projects inherit it — that comes later.")