/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description A Release / Version of a Project — the \"ship target\" axis on top of\nProject + Tracker + Status. Tasks can be tagged with `fixedVersion`\nto mark \"this work goes into Release 1.2.0\".\n\nNamed `ProjectVersion` (not `Version`) to avoid clashing with the\nVersionedTrait + Symfony\'s `Symfony\\Component\\Console\\Application::VERSION`\n+ general naming clarity (we already have `version: int` optimistic\nlocking on most entities).\n\nSharing field is reserved for the future Redmine-style cross-project\nrelease model — for now Worktide ships only `none` (this project) and\n`system` (every project in the workspace). The other three enum\nvalues exist so the column doesn\'t need a migration when sub-projects\nland in a later phase.\n\neffectiveDate is the planned ship date — burndown / release reports\nuse it as the X-axis anchor. When `status=closed`, the SPA treats\neffectiveDate as the actual release date.\n\nwikiPageTitle is a plain string (not an FK) because the Document a\nrelease-page lives at can be in any space; storing only the title +\nthe workspace lets the SPA look it up by name without forcing a\nlink-table that gets stale when pages are renamed.
 */
export const projectVersionHtmlSchema = z.object({
    "project": z.optional(z.string()),
"name": z.optional(z.string()),
"description": z.string().nullish(),
"effectiveDate": z.iso.datetime().nullish(),
"status": z.optional(z.enum(["open", "locked", "closed"]).default("open")),
"sharing": z.optional(z.enum(["none", "descendants", "hierarchy", "tree", "system"]).default("none")),
"wikiPageTitle": z.string().nullish(),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"deletedAt": z.iso.datetime().nullish(),
"workspace": z.optional(z.string()),
"version": z.optional(z.int().default(1)),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish(),
"deleted": z.optional(z.boolean())
    }).describe("A Release / Version of a Project — the \"ship target\" axis on top of\nProject + Tracker + Status. Tasks can be tagged with `fixedVersion`\nto mark \"this work goes into Release 1.2.0\".\n\nNamed `ProjectVersion` (not `Version`) to avoid clashing with the\nVersionedTrait + Symfony's `Symfony\\Component\\Console\\Application::VERSION`\n+ general naming clarity (we already have `version: int` optimistic\nlocking on most entities).\n\nSharing field is reserved for the future Redmine-style cross-project\nrelease model — for now Worktide ships only `none` (this project) and\n`system` (every project in the workspace). The other three enum\nvalues exist so the column doesn't need a migration when sub-projects\nland in a later phase.\n\neffectiveDate is the planned ship date — burndown / release reports\nuse it as the X-axis anchor. When `status=closed`, the SPA treats\neffectiveDate as the actual release date.\n\nwikiPageTitle is a plain string (not an FK) because the Document a\nrelease-page lives at can be in any space; storing only the title +\nthe workspace lets the SPA look it up by name without forcing a\nlink-table that gets stale when pages are renamed.")