/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type EntitySyncJsonMergePatchSyncModeEnum = "bidirectional" | "inbound" | "outbound" | "disabled";

export type EntitySyncJsonMergePatchConflictPolicyEnum = "worktide_wins" | "external_wins" | "last_write_wins" | "manual";

/**
 * @description One mapping row between a Worktide entity and its mirror in an\nexternal system. Replaces and generalises the per-entity\n{@see Trait\\ExternalReferenceTrait} for cases that need:\n\n  - M:N. A single Worktide Task can be mirrored in Jira AND\n    Redmine AND a CalDAV calendar simultaneously — three\n    EntitySync rows, one per channel.\n  - Bidirectional sync state. The trait only carried a flat ID;\n    this entity carries `externalUpdatedAt` + `ourVersion` + `etag`\n    so adapters can detect dual-changes and apply\n    {@see ConflictPolicy}.\n  - Pause without un-mapping. `syncMode = Disabled` keeps the\n    mapping intact while halting reads/writes — useful during\n    debugging or partial migrations.\n\nThe (entityType, entityId) pair carries the **identity** of the\nWorktide-side record; entityType is a free-form string slug\n(`task`, `project`, `customer`, `time_entry`, `calendar_event`)\nso we don\'t have to invent a discriminator hierarchy for every\nfuture entity that becomes syncable.\n\nUNIQUE(channel, externalId) makes a single external record map\nto at most one local entity per channel; the inverse is allowed\n(one local entity in N channels), which is exactly the M:N we\nwant.
*/
export type EntitySyncJsonMergePatch = {
    /**
     * @type string | undefined, iri-reference
    */
    channel?: string;
    /**
     * @description Worktide-side entity type slug — `task`, `comment`,\n`time_entry`, `calendar_event`, … Free-form so new\nsyncable entities don\'t need an enum migration. The\nadapter knows what it can sync; the resolver maps the slug\nback to the Doctrine class.
     * @type string | undefined
    */
    entityType?: string;
    /**
     * @description UUID of the Worktide-side entity. Foreign-key constraint\ncannot be expressed at the DB level because entityType is\npolymorphic — referential integrity is enforced by the\nadapter that creates/deletes mappings.
     * @type string | undefined, uuid
    */
    entityId?: string;
    /**
     * @description Identifier on the external side — Jira issue key\n(`PROJ-123`), Redmine issue id (`4567`), Google Calendar\nevent id (long opaque string), etc.
     * @type string | undefined
    */
    externalId?: string;
    /**
     * @description URL the user can click to open the record on the external\nsystem. Generated by the adapter at sync time so the SPA\ncan render \"Open in Jira\" without re-deriving the URL\nshape from the channel config.
     * @type string,null
    */
    externalUrl?: string | null;
    /**
     * @description `updated_at` value reported by the external system at the\nlast sync. Lets the adapter detect \"did the external change\nsince we last saw it?\" without re-pulling the full payload.
     * @type string,null, date-time
    */
    externalUpdatedAt?: string | null;
    /**
     * @description Snapshot of the Worktide-side `version` field at the last\nsync. Combined with `externalUpdatedAt` this is the basis\nfor the conflict-detection in {@see ConflictPolicy}.
     * @type integer,null
    */
    ourLastSyncedVersion?: number | null;
    /**
     * @description ETag or hash returned by the external system — useful for\nIf-None-Match conditional pulls (Jira, Microsoft Graph) so\nwe don\'t refetch unchanged records.
     * @type string,null
    */
    etag?: string | null;
    /**
     * @default "bidirectional"
     * @type string | undefined
    */
    syncMode?: EntitySyncJsonMergePatchSyncModeEnum;
    /**
     * @default "manual"
     * @type string | undefined
    */
    conflictPolicy?: EntitySyncJsonMergePatchConflictPolicyEnum;
    /**
     * @type string,null, date-time
    */
    lastSyncedAt?: string | null;
    /**
     * @type string,null, date-time
    */
    lastReconciledAt?: string | null;
    /**
     * @type string,null
    */
    lastSyncError?: string | null;
    /**
     * @description Adapter-specific blob. Holds field-mapping cache, vendor-\nspecific IDs that aren\'t the main externalId (Jira renderer\nvariants, Redmine project_id, etc.). Treat as opaque from\nthe application layer.
     * @type object | undefined
    */
    sourceMetadata?: {
        [key: string]: string | null;
    };
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
};