/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ConversationJsonMergePatchStatusEnum = "open" | "pending" | "closed" | "spam";

/**
 * @description Aggregate of {@see InboundEvent}s + {@see OutboundMessage}s that\nbelong to the same logical thread.\n\nOnly threading-capable channels populate this entity — Mail (via\nMessage-ID / References), Slack (thread_ts), WhatsApp (chat-id).\nChannels without thread semantics (Zabbix alerts, CVE feeds,\nmonitoring webhooks) leave their InboundEvents standalone with\n`conversationId = NULL`.\n\n`threadKey` is the channel-specific identifier the\n`ConversationThreader` strategy uses to match incoming events to\nan existing conversation. For mail it\'s the root References\nvalue; for slack it\'s the thread_ts of the root message.\n\n`customer`/`assignee` are resolved at first ingest time and may be\noverridden manually in the SPA later.
*/
export type ConversationJsonMergePatch = {
    /**
     * @type string | undefined, iri-reference
    */
    channel?: string;
    /**
     * @default ""
     * @type string | undefined
    */
    subject?: string;
    /**
     * @type string | undefined
    */
    threadKey?: string;
    /**
     * @default "open"
     * @type string | undefined
    */
    status?: ConversationJsonMergePatchStatusEnum;
    /**
     * @type string,null, iri-reference
    */
    customer?: string | null;
    /**
     * @type string,null, iri-reference
    */
    assignee?: string | null;
    /**
     * @description Free-text sender label captured at first-ingest — useful when\nthe Contact resolver hasn\'t matched a Customer yet. Falls back\nto the raw From-header value for mail.
     * @type string,null
    */
    senderRaw?: string | null;
    /**
     * @description Timestamp of the most recent inbound or outbound event in the\nthread. Drives the default inbox ordering. Updated by the\ningest pipeline + outbound worker.
     * @type string | undefined, date-time
    */
    lastEventAt?: string;
    /**
     * @description participant IRIs (Contact + User) for quick presence rendering
     * @type array | undefined
    */
    participantIris?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
};