/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Container for Documents — equivalent to a Notion/Confluence \"space\" or a\ntop-level sidebar group. Documents can also exist without a space (private\nnotes); when both exist, space ordering wins over project ordering.\n\nPer-space access (contributors / team access) is deferred — for the MVP a\nspace is workspace-wide-readable; the writer-restriction is on the\nDocument itself via DocumentContributor.
*/
export type DocumentSpaceHtml = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    description?: string | null;
    /**
     * @type string,null
    */
    color?: string | null;
    /**
     * @type string,null
    */
    icon?: string | null;
    /**
     * @description Emoji shortcode (or actual emoji) the UI uses as space icon.
     * @type string,null
    */
    emoji?: string | null;
    /**
     * @default 0
     * @type number | undefined
    */
    position?: number;
    /**
     * @default false
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @type array | undefined
    */
    readonly documents?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly archived?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
};