/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Value of a CustomFieldDefinition for a specific entity instance.\n\nPolymorphic by storing (target, target_id) rather than a per-type FK. Trade-off:\nno DB-level referential integrity to the target row — clean-up is done by\nSoftDelete listeners or maintenance jobs. We accept this for the flexibility of\nadding new targets without schema migrations.\n\nThe `value` column is JSON to support all CustomFieldType variants\n(string / number / bool / date / array-for-multiselect / uuid-for-user).
 */
export const customFieldValueJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "definition": z.optional(z.string()),
"target": z.optional(z.enum(["project", "task", "time_entry"])),
"targetId": z.optional(z.uuid()),
"value": z.optional(z.object({
    
    }).catchall(z.string().nullable()).default({})),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"workspace": z.optional(z.string()),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish()
    })).describe("Value of a CustomFieldDefinition for a specific entity instance.\n\nPolymorphic by storing (target, target_id) rather than a per-type FK. Trade-off:\nno DB-level referential integrity to the target row — clean-up is done by\nSoftDelete listeners or maintenance jobs. We accept this for the flexibility of\nadding new targets without schema migrations.\n\nThe `value` column is JSON to support all CustomFieldType variants\n(string / number / bool / date / array-for-multiselect / uuid-for-user).")