/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type OutboundMessageHtmlStatusEnum = "queued" | "sending" | "sent" | "failed" | "bounced";

/**
 * @description Something Worktide wants to send out through a {@see Channel}.\n\nLives independently of {@see InboundEvent} so the outbound\nlifecycle (queue → send → ack → bounce → open/click) has its\nown first-class state machine without mixing concerns. Reply-to-\nthread is expressed as `conversationId` + `inReplyToInboundEvent`,\nnot by mutating an inbound row.\n\nCreation paths:\n  1. User reply in the SPA conversation view\n  2. System notification (watcher fired, maintenance reminder)\n  3. AIRecommendation that the user approved\n\n`createdByUser` is required for messages to external recipients.\nThe OutboundQueue worker enforces this — auto-sending to a\ncustomer without a named operator is forbidden by policy (see\nAI-Vision: human-in-the-loop for external comms).\n\n`createdByRecommendation` (nullable) links back to the\nAIRecommendation row when the message originated from an AI\nsuggestion — useful for audit and for showing \"drafted by AI,\n * approved by Sven\" in the activity feed.\n\n`externalId` is the provider\'s tracking-id (SMTP queue-id,\nGraph internetMessageId, Mailgun message-id) — populated on send.
*/
export type OutboundMessageHtml = {
    /**
     * @type string | undefined, iri-reference
    */
    channel?: string;
    /**
     * @description Raw recipient address as the operator typed it / as the\nsource thread captured it. Kept verbatim for audit even after\n`recipientContact` resolves to a Contact record.
     * @type string | undefined
    */
    recipientRaw?: string;
    /**
     * @type string,null, iri-reference
    */
    recipientContact?: string | null;
    /**
     * @description Additional recipients — Cc/Bcc for mail, mentioned-users for\nslack, etc. JSON list of {address, contactIri?, kind: \'cc\'|\'bcc\'}.
     * @type array | undefined
    */
    additionalRecipients?: {
        [key: string]: string | null;
    }[];
    /**
     * @type string,null
    */
    subject?: string | null;
    /**
     * @default ""
     * @type string | undefined
    */
    body?: string;
    /**
     * @description list of {fileIri, filename, mimeType, sizeBytes}
     * @type array | undefined
    */
    attachments?: {
        [key: string]: string | null;
    }[];
    /**
     * @type string,null, iri-reference
    */
    conversation?: string | null;
    /**
     * @description The specific inbound event this message answers — drives the\nIn-Reply-To header for mail, the thread_ts for slack.
     * @type string,null, iri-reference
    */
    inReplyToInboundEvent?: string | null;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @description Free-form FK to an AIRecommendation row (entity arrives in\nPhase D). Stored as a UUID column so this entity can ship\nbefore the AI tier exists; the FK constraint lands in the\nPhase-D migration.
     * @type string,null, uuid
    */
    createdByRecommendationId?: string | null;
    /**
     * @default "queued"
     * @type string | undefined
    */
    status?: OutboundMessageHtmlStatusEnum;
    /**
     * @type string,null
    */
    statusReason?: string | null;
    /**
     * @default 0
     * @type integer | undefined
    */
    attemptCount?: number;
    /**
     * @type string,null, date-time
    */
    sentAt?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @type string,null, date-time
    */
    openedAt?: string | null;
    /**
     * @type string,null, date-time
    */
    clickedAt?: string | null;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
};