/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HydraItemBaseSchema } from "../HydraItemBaseSchema.ts";

/**
 * @description Subscription that mirrors selected DomainEvents to an external HTTP endpoint.\n\nEach delivery is signed with HMAC-SHA256 over the request body, using `secret`\nas the key; consumers verify by recomputing the digest and comparing it to the\n`X-Worktide-Signature: sha256=…` header.\n\nEvent subscription matches by name:\n  - `[\"*\"]`                  — every event\n  - `[\"task.*\"]`             — every event whose name starts with \"task.\"\n  - `[\"task.created\"]`       — exact name only\n\nThe `secret` is write-only via the API (returned obfuscated on reads) so it\nnever leaks back to clients after creation. `failureCount` and\n`lastTriggeredAt` are server-managed; clients cannot patch them.\n\nAfter {@see self::FAILURE_THRESHOLD} consecutive non-2xx deliveries the\nwebhook auto-deactivates — the operator must inspect the deliveries log and\nre-enable it with a fresh PATCH.
*/
export type WebhookJsonld = (HydraItemBaseSchema & {
    /**
     * @default ""
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    url?: string;
    /**
     * @description Event-name patterns this webhook subscribes to.
     * @type array | undefined
    */
    eventTypes?: string[];
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @default 0
     * @type integer | undefined
    */
    failureCount?: number;
    /**
     * @type string,null, date-time
    */
    lastTriggeredAt?: string | null;
    /**
     * @type string,null, date-time
    */
    lastSucceededAt?: string | null;
    /**
     * @type string,null, date-time
    */
    lastFailedAt?: string | null;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly active?: boolean;
});