/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileVersionHtml } from "../fileVersion/Html.ts";

export type FileHtmlTargetEnum = "project" | "task" | "workspace" | "user" | "comment" | "document";

/**
 * @description Polymorphic file attachment. The \"file\" itself is metadata only — actual\nbytes live on Flysystem-managed storage and are addressed through\nFileVersion entries (one File can have N revisions; the latest is the\n\"current\" version, kept on this row for fast lookups).\n\nUploads happen through FileUploadController (multipart) and become version 1\nof a new File row. Subsequent versions add new FileVersion rows without\nmutating the File metadata.\n\nCross-tenant safety: workspace-scoped + voter delegates to the target entity.
*/
export type FileHtml = {
    /**
     * @type string | undefined
    */
    target?: FileHtmlTargetEnum;
    /**
     * @type string | undefined, uuid
    */
    targetId?: string;
    /**
     * @description Display name (defaults to original filename, editable).
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string,null
    */
    description?: string | null;
    /**
     * @description MIME type of the current version (denormalised for fast filtering).
     * @type string,null
    */
    mimeType?: string | null;
    /**
     * @type string,null, iri-reference
    */
    uploadedBy?: string | null;
    /**
     * @description For files imported from external storage (Google Drive, OneDrive,\nDropbox, …). When set, no FileVersion bytes are stored — the file is\na pointer.
     * @type string,null
    */
    externalProvider?: string | null;
    /**
     * @type string,null
    */
    externalUrl?: string | null;
    /**
     * @default false
     * @type boolean | undefined
    */
    isExternal?: boolean;
    /**
     * @default false
     * @type boolean | undefined
    */
    isHiddenForConnectUsers?: boolean;
    currentVersion?: (FileVersionHtml | null);
    /**
     * @type array | undefined
    */
    readonly versions?: FileVersionHtml[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly external?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly hiddenForConnectUsers?: boolean;
    /**
     * @description Convenience: byte size of the current version (or null for external/empty).
     * @type integer,null
    */
    readonly size?: number | null;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
};