/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { hydraItemBaseSchemaSchema } from "../hydraItemBaseSchemaSchema.ts";
import { z } from "zod/v4";

export const projectMemberJsonldSchema = z.lazy(() => hydraItemBaseSchemaSchema).and(z.object({
    "project": z.optional(z.string()),
"user": z.optional(z.string()),
"role": z.optional(z.enum(["manager", "contributor", "viewer"]).default("contributor")),
"id": z.uuid().nullish(),
"createdAt": z.optional(z.iso.datetime()),
"updatedAt": z.optional(z.iso.datetime()),
"createdByUser": z.string().nullish(),
"updatedByUser": z.string().nullish()
    }))