/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type WorkspaceJsonMergePatch = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    slug?: string;
    /**
     * @default "de"
     * @type string | undefined
    */
    locale?: string;
    /**
     * @default "Europe/Berlin"
     * @type string | undefined
    */
    timezone?: string;
    /**
     * @description Free-form workspace settings as JSON. Currently holds:
     * @type object,null
    */
    settings?: {
        [key: string]: string | null;
    } | null;
    /**
     * @type array | undefined
    */
    readonly members?: string[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string,null, date-time
    */
    readonly deletedAt?: string | null;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type string,null
    */
    externalSource?: string | null;
    /**
     * @type string,null
    */
    externalId?: string | null;
    /**
     * @description Access-token TTL in seconds, or null if this workspace inherits the\nLexik default. Walks the JSON tree defensively because the JSON\nshape is free-form by design.
     * @type integer,null
    */
    readonly sessionAccessTtl?: number | null;
    /**
     * @type boolean | undefined
    */
    readonly deleted?: boolean;
    /**
     * @type string,null
    */
    readonly externalRef?: string | null;
};