/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CustomFieldOptionHtml } from "../customFieldOption/Html.ts";

export type CustomFieldDefinitionHtmlTargetEnum = "project" | "task" | "time_entry";

export type CustomFieldDefinitionHtmlTypeEnum = "text" | "long_text" | "number" | "date" | "date_time" | "boolean" | "select" | "multi_select" | "url" | "email" | "user";

/**
 * @description Workspace-scoped definition of a user-defined field that can be attached to\nProject / Task / TimeEntry (extensible via CustomFieldTarget enum).\n\n`target` controls which entity types may carry a value of this field.\n`key` is the stable machine identifier used in API payloads and integrations.
*/
export type CustomFieldDefinitionHtml = {
    /**
     * @type string | undefined
    */
    target?: CustomFieldDefinitionHtmlTargetEnum;
    /**
     * @type string | undefined
    */
    type?: CustomFieldDefinitionHtmlTypeEnum;
    /**
     * @type string | undefined
    */
    key?: string;
    /**
     * @type string | undefined
    */
    label?: string;
    /**
     * @type string,null
    */
    description?: string | null;
    /**
     * @description For Select / MultiSelect: list of allowed option labels.
     * @type array | undefined
    */
    options?: string[];
    /**
     * @default false
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @default false
     * @type boolean | undefined
    */
    isArchived?: boolean;
    /**
     * @default 0
     * @type integer | undefined
    */
    position?: number;
    /**
     * @type array | undefined
    */
    optionDefinitions?: CustomFieldOptionHtml[];
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
    /**
     * @type boolean | undefined
    */
    readonly required?: boolean;
    /**
     * @type boolean | undefined
    */
    readonly archived?: boolean;
};