/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Workspace-scoped time-tracking configuration. One row per workspace\n(UNIQUE workspace_id) — clients PATCH the singleton to tune behaviour:\n\n  - roundingMinutes:  when a TimeEntry is saved, its duration is rounded\n                      UP to the nearest N minutes (0 = no rounding).\n                      Common settings: 5, 15, 30.\n  - minimumMinutes:   floor for any newly-tracked entry (0 = no floor).\n                      Useful for \"always book at least 15 minutes\" rules.\n  - lockAfterDays:    once a TimeEntry is older than N days, it\'s marked\n                      isLocked and the author can no longer change it\n                      (closed accounting periods). null disables the\n                      auto-lock.\n  - allowFutureEntries: defaults to false — refuses startsAt > now.\n\nThe rounding policy is applied by {@see TimeTrackingPolicy::apply()} at\npersist time; the lock policy by a scheduled command that walks aged rows.
*/
export type TimeTrackingSettingsJsonMergePatch = {
    /**
     * @minLength 0
     * @maxLength 120
     * @default 0
     * @type integer | undefined
    */
    roundingMinutes?: number;
    /**
     * @minLength 0
     * @maxLength 480
     * @default 0
     * @type integer | undefined
    */
    minimumMinutes?: number;
    /**
     * @minLength 1
     * @maxLength 3650
     * @type integer,null
    */
    lockAfterDays?: number | null;
    /**
     * @default false
     * @type boolean | undefined
    */
    allowFutureEntries?: boolean;
    /**
     * @type string,null, uuid
    */
    readonly id?: string | null;
    /**
     * @type string | undefined, date-time
    */
    readonly createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updatedAt?: string;
    /**
     * @type string | undefined, iri-reference
    */
    workspace?: string;
    /**
     * @default 1
     * @type integer | undefined
    */
    readonly version?: number;
    /**
     * @type string,null, iri-reference
    */
    createdByUser?: string | null;
    /**
     * @type string,null, iri-reference
    */
    updatedByUser?: string | null;
};